### ISSUE TITLE
About “The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream”

### ISSUE THREAD

**Issue by rabbit-mom** [Microsoft/mssql-jdbc#171] opened 2017-03-06 10:38 UTC
when I using TVP to bulkinsert to a table,this exception occured,and I do not konw to solve it?
"com.microsoft.sqlserver.jdbc.SQLServerException: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Table-valued parameter 0 (""), row 0, column 0: Data type 0x6C has an invalid precision or scale."
What reason is this?How to solve it?

**Comment by gordthompson** [comment] 2017-03-06 14:30
Can you provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)?

**Comment by rabbit-mom** [comment] 2017-03-07 06:38
```
SQLServerDataTable sourceDataTable=new SQLServerDataTable();
sourceDataTable.addColumnMetadata("actuAmount",Types.DECIMAL);
sourceDataTable.addColumnMetadata("amount",Types.DECIMAL);
sourceDataTable.addRow(new BigDecimal(0.0000).setScale(4,BigDecimal.ROUND_HALF_UP),new BigDecimal(1098.0000).setScale(4,BigDecimal.ROUND_HALF_UP));
SQLServerCallableStatement pStmt = (SQLServerCallableStatement) DataSource.getConnection("DBName").prepareCall("exec spT_TbaleA_i ?");
pStmt.setStructured(1,"TVP_TbaleA",sourceDataTable);
pStmt.execute();
```
I have found the reason, when I using these to bulkinsert to a table,when sourceDataTable addRow first parameter for new BigDecimal (0.0000). setScale (4, BigDecimal. ROUND_HALF_UP)), will be submitted to the mistake just now, and when the first parameter not limit its accuracy, is not an exception.(The above is just an example)

**Comment by rabbit-mom** [comment] 2017-03-07 06:39
```
SQLServerDataTable sourceDataTable=new SQLServerDataTable();
sourceDataTable.addColumnMetadata("actuAmount",Types.DECIMAL);
sourceDataTable.addColumnMetadata("amount",Types.DECIMAL);
sourceDataTable.addRow(new BigDecimal(0.0000).setScale(4,BigDecimal.ROUND_HALF_UP),new BigDecimal(1098.0000).setScale(4,BigDecimal.ROUND_HALF_UP));
SQLServerCallableStatement pStmt = (SQLServerCallableStatement) DataSource.getConnection("DBName").prepareCall("exec spT_TbaleA_i ?");
pStmt.setStructured(1,"TVP_TbaleA",sourceDataTable);
pStmt.execute();
```
I have found the reason, when I using these to bulkinsert to a table,when sourceDataTable addRow first parameter for new BigDecimal (0.0000). setScale (4, BigDecimal. ROUND_HALF_UP)), will be submitted to the mistake just now, and when the first parameter not limit its accuracy, is not an exception.(The above is just an example),but I do not know why  mssql6.0  do such restrictions?

**Comment by rabbit-mom** [comment] 2017-03-07 09:02
Hi,thanks for your response,next is my example:
```
SQLServerDataTable sourceDataTable=new SQLServerDataTable();
sourceDataTable.addColumnMetadata("actuAmount",Types.DECIMAL);
sourceDataTable.addColumnMetadata("amount",Types.DECIMAL);
sourceDataTable.addRow(new BigDecimal(0.0000).setScale(4,BigDecimal.ROUND_HALF_UP),new BigDecimal(1098.0000).setScale(4,BigDecimal.ROUND_HALF_UP));
SQLServerCallableStatement pStmt = (SQLServerCallableStatement) DataSource.getConnection("DBName").prepareCall("exec spT_TbaleA_i ?");
pStmt.setStructured(1,"TVP_TbaleA",sourceDataTable);
pStmt.execute();
```
I found the problem is at "new BigDecimal(0.0000).setScale(4,BigDecimal.ROUND_HALF_UP)",the precision is four and the value is 0.0000,it will throws that exception.Eagerly looking forward to your reply.

**Comment by gordthompson** [comment] 2017-03-07 15:13
I can reproduce the issue using the above Java code along with

```sql
CREATE TYPE [dbo].[TVP_TbaleA] AS TABLE(
    [c1] [decimal](18, 4) NOT NULL,
    [c2] [decimal](18, 4) NULL,
    PRIMARY KEY CLUSTERED 
(
    [c1] ASC
)WITH (IGNORE_DUP_KEY = OFF)
)
```

and

```sql
CREATE PROCEDURE [dbo].[spT_TbaleA_i] 
    @tbl dbo.TVP_TbaleA READONLY
AS
BEGIN
    SET NOCOUNT ON;
    SELECT c1 + c2 AS cSum FROM @tbl;
END
```

As decribed, it is the 

```sql
new BigDecimal(0.0000).setScale(4,BigDecimal.ROUND_HALF_UP)
```

argument to `SQLServerDataTable#addRow` that is causing the exception. Both

```sql
new BigDecimal(1.0000).setScale(4,BigDecimal.ROUND_HALF_UP)
```

and

```sql
new BigDecimal(0.0000)
```

work fine.

**Comment by v-xiangs** [comment] 2017-03-07 18:15
@rabbit-mom which version of the driver do you use? could you please try with a newer version? This bug seems to be fixed since 6.1.2

**Comment by gordthompson** [comment] 2017-03-07 21:58
My repro above was with the latest production release: 6.0.8112.100

Re-tested with "mssql-jdbc-6.1.4.jre8-preview.jar" and the error did not occur, so this appears to be the same issue as #92.

**Comment by v-xiangs** [comment] 2017-03-07 22:01
@gordthompson thank you for getting back to us and confirm with us. I am going to close this issue then. @rabbit-mom please free feel to re-open the issue if you see this issue again with newer version of the driver. Thank you.

**Closed by v-xiangs** 2017-03-07 22:01 UTC
Labels: Waiting for response

**Comment by rabbit-mom** [comment] 2017-03-08 02:48
Thank you very much, the problem has been resolved.
