### ISSUE TITLE
[BUG] getColumns not escaping Wildcards

### ISSUE THREAD

**Issue by Springrbua** [microsoft/mssql-jdbc#1136] opened 2019-08-30 12:50 UTC
## Driver version
Version 7.3.1 or later

## SQL Server version
SQL Server 2017

## Client Operating System
Windows 10 x64

## JAVA/JVM version
OpenJDK 1.8.0_202

## Problem description
1. Expected behaviour:
I have a table with a column `ID_Article`.
When calling `getColumns` with `ID\_Article` as `col` Parameter, it should return the description of table column `ID_Article` .
2. Actual behaviour:
Since version 7.3.1 it does not seem to find the column anymore, as it does not escape the `_` correctly.

3. Error message/stack trace:
No error is thrown, it just does not find the column.

4. Any other details that can be helpful:
The method [`EscapeIDName`](https://github.com/microsoft/mssql-jdbc/blob/dev/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDatabaseMetaData.java#L562) states, that `\_n` will be mapped to `'[_]n'` as the SQL-Server expects this syntax. However, this mapping does not seem to occur anymore.  
The bug was probably introduced by #1016.
Also #1134 might be related to this.

**Comment by peterbae** [comment] 2019-08-30 21:55
Hi @Springrbua, thanks for contacting us. I've identified the issue and I'm testing my fix. As soon as the internal testings are done, I'll create a PR and provide you with a custom jar that contains my fix.

**Comment by peterbae** [comment] 2019-09-03 17:51
Hi @Springrbua, @mprins, I've made a PR that fixes this issue. I've attached the driver jars with the fix in them (for Java 8/12), so if you have time, please try these and confirm if the fix is good. Thanks!

[github-1136-fix.zip](https://github.com/microsoft/mssql-jdbc/files/3570786/github-1136-fix.zip)

**Comment by Springrbua** [comment] 2019-09-04 06:21
@peterbae Thank you very much, the patched driver fixed the issue for me.

**Comment by mprins** [comment] 2019-09-04 10:03
I'm out-of-office, so won't be able to test until (maybe) friday

**Comment by dqmdev** [comment] 2019-09-04 15:58
When will MS release the build to customers?

In other words, when will the successor to 7.4.1 be announced at 

https://techcommunity.microsoft.com/t5/SQL-Server/bg-p/SQLServer/label-name/SQLServerDrivers

**Comment by peterbae** [comment] 2019-09-04 16:00
We're aiming to release the next preview version of the driver by the end of this month, and it will include this fix.

**Comment by mprins** [comment] 2019-09-05 07:47
I had a chance to test this today, I can not reproduce the problem with the attached, patched driver, even though I don't have columns with underscores, but do have tables with underscores, but that also seems to be adressed in #1138

**Comment by ulvii** [comment] 2019-10-02 00:25
#1138 merged.

**Closed by ulvii** 2019-10-02 00:25 UTC
Labels: bug
