### ISSUE TITLE
[FEATURE REQUEST] Sequence increments twice on SelectMethod=cursor.

### ISSUE THREAD

**Issue by oosato-im** [microsoft/mssql-jdbc#1221] opened 2019-12-25 09:27 UTC
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it
In case of SelectMethod=cursor, it increments twice by acquiring value from sequence.

Perform a following code, the result is "sequence: 2" instead of one.
```java
    public static void main(final String[] args) {
        final SQLServerDataSource ds = new SQLServerDataSource();
        ds.setServerName("localhost");
        ds.setPortNumber(1433);
        ds.setDatabaseName("database");
        ds.setUser("user");
        ds.setPassword("password");
        ds.setSelectMethod("cursor");
        // CREATE SEQUENCE sample_seq AS int START WITH 1;
        final String sql = "SELECT NEXT VALUE FOR sample_seq AS seq";
        try (final Connection conn = ds.getConnection();
              final PreparedStatement ps = conn.prepareStatement(sql);
              final ResultSet rs = ps.executeQuery();) {
            while (rs.next()) {
                final int seq = rs.getInt(1);
                System.out.printf("sequence: %d", seq);
            }
        } catch (final SQLException e) {
            e.printStackTrace();
        }
    }
```

## Describe the preferred solution
In case of SelectMethod=cursor, it increments by one each.

**Comment by peterbae** [comment] 2019-12-30 20:38
Hi @oosato-im. I actually can't reproduce the issue with the setup above and the sequence is incremented by 1 in my environment, but if my suspicions are correct, this is a duplicate of the issue https://github.com/microsoft/mssql-jdbc/issues/1174.

The behavior of the sequence incrementing twice is reproducible if the cursor scroll option is FAST_FORWARD, and this is the intended behavior. Please confirm if my understanding is correct and let me know if this answers your question.

**Comment by oosato-im** [comment] 2020-01-07 04:16
Thanks @peterbae, your understanding is correct.
I perform some condition in changing resultSetType and resultSetConcurrency, then it was same results.
Addition the results of #1174, I confirm the same results of TYPE_FORWARD_ONLY and CONCUR_READ_ONLY in circumstance SelectMethod=cursor.

However, I don't know why you are not able to reproduce. Please tell me your environment.

My environment:
SQLServer: Microsoft SQL Server Express (64-bit) 14.0.3192.2
jdbc: 7.4.1.jre8

**Comment by peterbae** [comment] 2020-01-07 18:11
Hi @oosato-im, I didn't mean that I can't reproduce the issue at all - I meant that I can't reproduce the issue with the case you provided above. I can reproduce the issue if I set the server's cursor type to FAST_FORWARD.

Either way, this behavior is expected and by design. Please let me know if there's anything else you need, otherwise I will close this issue in due time.

**Closed** 2020-01-14 19:05 UTC
Labels: enhancement
