### ISSUE TITLE
Cannot use JDBC escape sequence to call stored function in Azure SQL Data Warehouse

### ISSUE THREAD

**Issue by lukaseder** [Microsoft/mssql-jdbc#707] opened 2018-05-28 10:27 UTC
## Driver version or jar name
6.5.2.jre8-preview

## SQL Server version
SQL Data Warehouse

## Client operating system
Windows 10

## Java/JVM version
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

## Table schema
```sql
CREATE FUNCTION f_one()
RETURNS int
AS
BEGIN
  RETURN 1;
END;
```

## Problem description
I want to call the above function using the standard JDBC escape sequence syntax, but it doesn't work

## Expected behavior and actual behavior
I should be able to call that function and get `1` as a result. Instead, I'm getting:

```
Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: Parse error at line: 1, column: 6: Incorrect syntax near '@P0'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:264)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1585)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:554)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:485)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7385)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2750)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:235)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:210)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:430)
	at SQLServer.main(SQLServer.java:66)
```

## Repro code

**This fails**:

```java
try (Connection c = DriverManager.getConnection(url, properties);
    CallableStatement s = c.prepareCall("{ ? = call dbo.f_one() }")) {

    s.registerOutParameter(1, Types.INTEGER);
    s.executeUpdate();

    System.out.println(s.getInt(1));
}
```

**This workaround works**:

```java
try (Connection c = DriverManager.getConnection(url, properties);
    PreparedStatement s = c.prepareStatement("SELECT dbo.f_one()");
    ResultSet r = s.executeQuery()) {

    r.next();
    System.out.println(r.getInt(1));
}
```

**Comment by rene-ye** [comment] 2018-05-28 23:39
Hi @lukaseder, the reason you're receiving that error is due to Azure DW's limited compatibility in certain areas. When you call ```{ ? = call dbo.f_one() }```, the driver is sending:
```SQL
DECLARE @p3 int
SET @p3=1
EXEC sp_executesql N'EXEC @P0 = dbo.f_one         ',N'@P0 int OUTPUT',@p3 OUTPUT
SELECT @p3
```

As it turns out, ```EXEC @P0 = dbo.f_one``` is not valid T-SQL on Azure DW. The following T-SQL will work on regular SQL Servers, but not Azure Data Warehouse.
```SQL
DECLARE @intVar int
EXEC @intVar = dbo.f_one
SELECT @intVar
```

It's worth noting that the escape sequence used in this case was designed to be used with [Stored Procedure Calls](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-sql-escape-sequences?view=sql-server-2017), and not functions. The [SQL Server FUNCTION](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-function-transact-sql?view=sql-server-2017) and [Data Warehouse FUNCTION](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-function-sql-data-warehouse?view=azure-sqldw-latest) are also different and not entirely compatible. The team will have a discussion on whether this is a driver deficiency, and if so, how we'll go about fixing it.

**Comment by cheenamalhotra** [comment] 2018-08-31 23:55
Closing this issue as no solution available from JDBC Driver for this limitation of Azure DW.

**Closed by cheenamalhotra** 2018-08-31 23:55 UTC
