### ISSUE TITLE
Inconsistent updates of ResultSet rows when updating one-to-many tables

### ISSUE THREAD

**Issue by siggemannen** [microsoft/mssql-jdbc#2067] opened 2023-02-05 09:33 UTC
## Driver version
9.1.1.jre8-preview

## SQL Server version
Microsoft SQL Server 2014 (SP3-GDR) (KB4583463) - 12.0.6164.21 (X64) 
	Nov  1 2020 04:25:14 
	Copyright (c) Microsoft Corporation
	Express Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)

## Client Operating System
Windows 7

## JAVA/JVM version
1.8

## Table schema
```sql
drop table edit
drop table editrow
create table edit (i int, data varchar(30))
create table editrow (i int, row int, data varchar(30))

insert into edit select 1, 'testedit'
insert into editrow select 1, 1, 'test1' union select 1, 2, 'test2'

select er.*
from edit e
inner join editrow er
	ON	er.i = e.i
```

## Problem description

I have two tables which are joined together by above SELECT. I want to update columns by selecting the resultSet by using JDBC and ResultSet.updateXXX, but according to my tests, for some reason i can only update columns in the first table, even though it's the table that gets "duplicated" in the SELECT. I can update both tables by using manual UPDATE in SQL Server, but i need to do it through java. I also can't skip the JOIN for various reasons.

I get no exceptions, but that data isn't changed either.

Sample code:
```java
        //this doesn't update
        Connection conn = DriverManager.getConnection(getUrl());
        Statement createStatement = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        ResultSet rs = createStatement.executeQuery("select er.* from edit e inner join editrow er ON  er.i = e.i");
        //Now,move to row 1...
        rs.first();
        //Update data with some string
        rs.updateString(3, "New row edit");
        rs.updateRow();
        rs.close();
        createStatement.close();
        
       //this updates
        Statement createStatement = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        ResultSet rs = createStatement.executeQuery("select * from edit e inner join editrow er ON  er.i = e.i");
        //Now,move to row 1...
        rs.first();
        //Update data with some string
        rs.updateString(2, "New head edit");
        rs.updateRow();
        rs.close();
        createStatement.close();
        
```

Full code attached in the text file.

## Expected behavior

I expect to be able to update all updateable columns. If some column cannot be updated, i expect an exception. But ideally everything that SQL Server itself can update should be updateable by JDBC driver.

## Actual behavior

When updating column from "editrow", it silently accepts it but the data isn't changed. When updating column from "edit", it works.

## Error message/stack trace

There are no errors

## Any other details that can be helpful

I have attached a simple java program which demostrates the behaviour.

## JDBC trace logs
feb 02, 2023 1:02:43 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:1 execute
FINER: ENTRY if object_id('edit') is not null drop table edit
create table edit (i int, data varchar(30))
if object_id('editrow') is not null drop table editrow
create table editrow (i int, row int, data varchar(30))
insert into edit select 1, 'testedit'
insert into editrow select 1, 1, 'test1' union select 1, 2, 'test2'
feb 02, 2023 1:03:56 FM com.microsoft.sqlserver.jdbc.SQLServerStatement doExecuteStatement
FINE: SQLServerStatement:1 Executing (not server cursor) if object_id('edit') is not null drop table edit
create table edit (i int, data varchar(30))
if object_id('editrow') is not null drop table editrow
create table editrow (i int, row int, data varchar(30))
insert into edit select 1, 'testedit'
insert into editrow select 1, 1, 'test1' union select 1, 2, 'test2'
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:1 execute
FINER: RETURN false
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:1 close
FINER: ENTRY
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:1 close
FINER: RETURN
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerConnection:1 createStatement
FINER: ENTRY 1 005 1 008
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:2 setResponseBuffering
FINER: ENTRY adaptive
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:2 setResponseBuffering
FINER: RETURN
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
FINER: Properties for SQLServerStatement:2: Result type:1005 (1005) Concurrency:1008 Fetchsize:128 bIsClosed:false useLastUpdateCount:false
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
FINE: SQLServerStatement:2 created by (ConnectionID:1 ClientConnectionId: 3715addc-0b12-4f86-a437-46f0711d8a56)
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerConnection:1 createStatement
FINER: RETURN SQLServerStatement:2
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:2 executeQuery
FINER: ENTRY select er.* from edit e inner join editrow er ON  er.i = e.i
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerStatement doExecuteStatement
FINE: SQLServerStatement:2 Executing server side cursor select er.* from edit e inner join editrow er ON  er.i = e.i
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerStatement doExecuteCursored
FINER: SQLServerStatement:2 Execute for cursor open SQL:select er.* from edit e inner join editrow er ON  er.i = e.i Scrollability:1 Concurrency:24580
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet <init>
FINE: SQLServerResultSet:1 created by (SQLServerStatement:2)
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:2 executeQuery
FINER: RETURN SQLServerResultSet:1
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:1 first
FINER: ENTRY
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet first
FINER: SQLServerResultSet:1 currentRow:0 numFetchedRows:0 rowCount:2
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet doServerFetch
FINER: SQLServerResultSet:1 fetchType:1 startRow:0 numRows:128
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.ScrollWindow next
FINER: SQLServerResultSet:1 currentRow:0 maxRows:128
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:1 first
FINER: RETURN true
feb 02, 2023 1:03:57 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:1 updateString
FINER: ENTRY 3 New row edit
feb 02, 2023 1:04:02 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:1 updateString
FINER: RETURN
feb 02, 2023 1:04:02 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:1 updateRow
FINER: ENTRY
feb 02, 2023 1:04:02 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet updateRow
FINER: SQLServerResultSet:1 currentRow:1 numFetchedRows:1 rowCount:2
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:1 updateRow
FINER: RETURN
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:1 close
FINER: ENTRY
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet closeServerCursor
FINER: SQLServerResultSet:1 Closing cursor:180150003
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet closeServerCursor
FINER: SQLServerResultSet:1 Closed cursor:180150003
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:1 close
FINER: RETURN
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:2 close
FINER: ENTRY
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:1 close
FINER: ENTRY
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:1 close
FINER: RETURN
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:2 close
FINER: RETURN
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerConnection:1 createStatement
FINER: ENTRY
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerConnection:1 createStatement
FINER: ENTRY 1 003 1 007
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:3 setResponseBuffering
FINER: ENTRY adaptive
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:3 setResponseBuffering
FINER: RETURN
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
FINER: Properties for SQLServerStatement:3: Result type:1003 (2003) Concurrency:1007 Fetchsize:128 bIsClosed:false useLastUpdateCount:false
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
FINE: SQLServerStatement:3 created by (ConnectionID:1 ClientConnectionId: 3715addc-0b12-4f86-a437-46f0711d8a56)
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerConnection:1 createStatement
FINER: RETURN SQLServerStatement:3
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerConnection:1 createStatement
FINER: RETURN SQLServerStatement:3
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:3 executeQuery
FINER: ENTRY select er.data from editrow er where row = 1;
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement doExecuteStatement
FINE: SQLServerStatement:3 Executing (not server cursor) select er.data from editrow er where row = 1;
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet <init>
FINE: SQLServerResultSet:2 created by (SQLServerStatement:3)
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:3 executeQuery
FINER: RETURN SQLServerResultSet:2
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:2 next
FINER: ENTRY
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet next
FINER: SQLServerResultSet:2 currentRow:0 numFetchedRows:0 rowCount:-3
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:2 next
FINER: RETURN true
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:2 getString
FINER: ENTRY 1
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet getterGetColumn
FINER: SQLServerResultSet:2 Getting Column:1
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.BaseInputStream setLoggingInfo
FINER: com.microsoft.sqlserver.jdbc.SimpleInputStreamID:1
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SimpleInputStream read
FINER: com.microsoft.sqlserver.jdbc.SimpleInputStreamID:1 Reading 5 from stream offset 0 payload length 5
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SimpleInputStream close
FINER: com.microsoft.sqlserver.jdbc.SimpleInputStreamID:1Enter Closing SimpleInputStream.
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SimpleInputStream skip
FINER: com.microsoft.sqlserver.jdbc.SimpleInputStreamID:1 Skipping :0
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SimpleInputStream close
FINER: com.microsoft.sqlserver.jdbc.SimpleInputStreamID:1Exit Closing SimpleInputStream.
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:2 getString
FINER: RETURN test1
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:2 close
FINER: ENTRY
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:2 close
FINER: RETURN
test1
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerConnection:1 createStatement
FINER: ENTRY 1 005 1 008
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:4 setResponseBuffering
FINER: ENTRY adaptive
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:4 setResponseBuffering
FINER: RETURN
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
FINER: Properties for SQLServerStatement:4: Result type:1005 (1005) Concurrency:1008 Fetchsize:128 bIsClosed:false useLastUpdateCount:false
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
FINE: SQLServerStatement:4 created by (ConnectionID:1 ClientConnectionId: 3715addc-0b12-4f86-a437-46f0711d8a56)
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerConnection:1 createStatement
FINER: RETURN SQLServerStatement:4
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:4 executeQuery
FINER: ENTRY select * from edit e inner join editrow er ON  er.i = e.i
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement doExecuteStatement
FINE: SQLServerStatement:4 Executing server side cursor select * from edit e inner join editrow er ON  er.i = e.i
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement doExecuteCursored
FINER: SQLServerStatement:4 Execute for cursor open SQL:select * from edit e inner join editrow er ON  er.i = e.i Scrollability:1 Concurrency:24580
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet <init>
FINE: SQLServerResultSet:3 created by (SQLServerStatement:4)
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:4 executeQuery
FINER: RETURN SQLServerResultSet:3
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:3 first
FINER: ENTRY
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet first
FINER: SQLServerResultSet:3 currentRow:0 numFetchedRows:0 rowCount:2
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet doServerFetch
FINER: SQLServerResultSet:3 fetchType:1 startRow:0 numRows:128
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.ScrollWindow next
FINER: SQLServerResultSet:3 currentRow:0 maxRows:128
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:3 first
FINER: RETURN true
feb 02, 2023 1:04:03 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:3 updateString
FINER: ENTRY 2 New head edit
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:3 updateString
FINER: RETURN
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:3 updateRow
FINER: ENTRY
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet updateRow
FINER: SQLServerResultSet:3 currentRow:1 numFetchedRows:1 rowCount:2
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:3 updateRow
FINER: RETURN
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:3 close
FINER: ENTRY
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet closeServerCursor
FINER: SQLServerResultSet:3 Closing cursor:180150005
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet closeServerCursor
FINER: SQLServerResultSet:3 Closed cursor:180150005
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:3 close
FINER: RETURN
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:4 close
FINER: ENTRY
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:3 close
FINER: ENTRY
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:3 close
FINER: RETURN
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:4 close
FINER: RETURN
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerConnection:1 createStatement
FINER: ENTRY
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerConnection:1 createStatement
FINER: ENTRY 1 003 1 007
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:5 setResponseBuffering
FINER: ENTRY adaptive
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:5 setResponseBuffering
FINER: RETURN
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
FINER: Properties for SQLServerStatement:5: Result type:1003 (2003) Concurrency:1007 Fetchsize:128 bIsClosed:false useLastUpdateCount:false
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
FINE: SQLServerStatement:5 created by (ConnectionID:1 ClientConnectionId: 3715addc-0b12-4f86-a437-46f0711d8a56)
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerConnection:1 createStatement
FINER: RETURN SQLServerStatement:5
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerConnection:1 createStatement
FINER: RETURN SQLServerStatement:5
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:5 executeQuery
FINER: ENTRY select er.data from edit er where i = 1;
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerStatement doExecuteStatement
FINE: SQLServerStatement:5 Executing (not server cursor) select er.data from edit er where i = 1;
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet <init>
FINE: SQLServerResultSet:4 created by (SQLServerStatement:5)
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerStatement:5 executeQuery
FINER: RETURN SQLServerResultSet:4
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:4 next
FINER: ENTRY
New head edit
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet next
FINER: SQLServerResultSet:4 currentRow:0 numFetchedRows:0 rowCount:-3
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:4 next
FINER: RETURN true
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:4 getString
FINER: ENTRY 1
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet getterGetColumn
FINER: SQLServerResultSet:4 Getting Column:1
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.BaseInputStream setLoggingInfo
FINER: com.microsoft.sqlserver.jdbc.SimpleInputStreamID:2
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SimpleInputStream read
FINER: com.microsoft.sqlserver.jdbc.SimpleInputStreamID:2 Reading 13 from stream offset 0 payload length 13
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SimpleInputStream close
FINER: com.microsoft.sqlserver.jdbc.SimpleInputStreamID:2Enter Closing SimpleInputStream.
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SimpleInputStream skip
FINER: com.microsoft.sqlserver.jdbc.SimpleInputStreamID:2 Skipping :0
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SimpleInputStream close
FINER: com.microsoft.sqlserver.jdbc.SimpleInputStreamID:2Exit Closing SimpleInputStream.
feb 02, 2023 1:04:05 FM com.microsoft.sqlserver.jdbc.SQLServerResultSet:4 getString
FINER: RETURN New head edit

[RSUpdate.txt](https://github.com/microsoft/mssql-jdbc/files/10563063/RSUpdate.txt)

**Comment by tkyc** [comment] 2023-02-07 00:23
We'll do some investigating and get back to you.

**Comment by tkyc** [comment] 2023-02-10 21:42
So, it looks like `edit` table gets updated rather than the `editrow` table is because of the driver's call to `sp_cursor` (more info on sp_cursor [here](https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-cursor-transact-sql?view=sql-server-ver16)). `sp_cursor` takes in a table name, however the driver does not specify the table name for the column being updated. So, by default the table name used is the first table name after the `FROM` clause.

>when the cursor definition involves a join or ambiguous column names are returned by the value parameter. If no specific table is designated, the default is the first table in the FROM clause

I'm not sure why we are not specifying the table name in the `sp_cursor` call. I'll need to do more investigating on whether this is as designed. In the meantime, you'll need to specify the table name of the column you want to update right after the `FROM` clause.

**Comment by tkyc** [comment] 2023-02-10 22:59
After more investigation, it doesn't look as trivial as just setting the table name param in `sp_cursor` to fix this. If we do set the table name param in `sp_cursor`, it will have implications we need to account for eg. right now `sp_cursor` is called once, doing this table name change may require us to call it multiple times.

**Comment by siggemannen** [comment] 2023-02-11 10:06
I'm not superfamiliar with sp_cursor, but an update shouldn't be able to update several tables at the same time, so to me it would look safe to just pass a single table name for all the columns and error out if someone is trying to commit update through multiple tables?

**Comment by tkyc** [comment] 2023-02-13 18:49
> ...but an update shouldn't be able to update several tables at the same time, so to me it would look safe to just pass a single table name for all the columns and error out if someone is trying to commit update through multiple tables?

The scenario I'm thinking of that is the problem is what if there are multiple updates on multiple tables eg.
```
rs.updateInt(); // update int column on table1
rs.updateString(); //update string column on table2
...
...
rs.updateRow();
```
So, in this case specifying a single table name wouldn't work. Let me know your thoughts as well, I'm still mulling over this scenario.

**Comment by siggemannen** [comment] 2023-02-13 21:35
My code calls "updateRow" once for every column, so for me it would already work if the driver always pass the first column's table name.

It will not make it worse for anyone else either, because there are 4 cases that i can see:

| Case |  Result of current version | Version which sends table name |
|-- | --|-- |
| Update one column without duplicate names | Works | Will work |
| Update one column with duplicate names | Either updates correct or wrong column | Will update correct column |
| Update multiple columns from different tables without duplicate names |  Crashes because sp_cursor will assume table name from first column but not all columns exist in first table | Crashes due to same error | 
| Update multiple columns with column names exist in both tables |  Will work, but if you're unlucky, it will update wrong data | Will work the same way |

But I guess the driver can be nice enough to make one sp_cursor call per distinct column table? Collect table -> columns mappings in a Map and then loop through each key. 

It's probably not easy for the driver user to know about these details and i don't think JDBC requires one to call updateRow in a specific order even if it kind of makes sense. But if the updateRow would crash with some meaningful error, i think it's still better than silent update of wrong table or a crash that says a column doesn't exist (which is what you get now if you update two columns, the second of which doesn't exist in the first table).

**Comment by tkyc** [comment] 2023-02-14 19:48
Totally valid points. I'm discussing with the team about what we want to do exactly at the moment. A fix will be on the way and likely in the next preview.

**Comment by siggemannen** [comment] 2023-02-28 23:26
Hi, any updates on this issue? I also wonder, is there any hope of getting the fix into 9.1.1.jre8-preview? :D Or how far are bugfixes backported in general?

**Comment by tkyc** [comment] 2023-03-01 00:43
Hey @siggemannen sorry for the delay, we were working on other stuff. A PR for this issue should come out some time this week. Once it gets merged we'll update this issue.

We'll likely backport this to only 10.2 and 11.2. So, it probably won't be in 9.1. I'll check with the team and let you know if it's possible to get it in 9.1.

**Comment by tkyc** [comment] 2023-03-07 22:45
Sorry, I spoke with the team, and it looks like it won't be backported to 9.1.

**Closed by tkyc** 2023-03-07 22:45 UTC
