### ISSUE TITLE
Encountered unexpected unknown token (0xA3) from TDSParser when calling native compiled stored procedure in SQL Server 2019

### ISSUE THREAD

**Issue by Genmutant** [microsoft/mssql-jdbc#1225] opened 2020-01-03 15:45 UTC
## Driver version
8.1.1.jre8-preview, 7.4.1.jre8

## SQL Server version
Microsoft SQL Server 2019 (RTM-GDR) (KB4517790) - 15.0.2070.41 (X64)   Oct 28 2019 19:56:59   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

## Client Operating System
Windows 10, Windows Server 2016

## JAVA/JVM version
AdoptOpenJDK jdk8u222

## Table schema
```
CREATE PROCEDURE dbo.NativeProdForTesting WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
     AS BEGIN ATOMIC WITH ( TRANSACTION ISOLATION LEVEL = SNAPSHOT,  LANGUAGE = N'us_english')
	 SELECT NULL AS testcol
         RETURN 0
     END
```

## Problem description
1. Expected behaviour: No exception, result returned successfully
2. Actual behaviour: SQLServerException
3. Error message/stack trace:

> Jan 03, 2020 4:33:28 PM com.microsoft.sqlserver.jdbc.TDSParser throwUnexpectedTokenException
> SCHWERWIEGEND: ConnectionID:1 ClientConnectionId: 16074f9e-4a1b-4d50-8f67-1abd12daba82: getNextResult: Encountered unexpected unknown token (0xA3)
> Jan 03, 2020 4:33:28 PM com.microsoft.sqlserver.jdbc.TDSReader throwInvalidTDSToken
> SCHWERWIEGEND: ConnectionID:1 ClientConnectionId: 16074f9e-4a1b-4d50-8f67-1abd12daba82 got unexpected value in TDS response at offset:0

```
com.microsoft.sqlserver.jdbc.SQLServerException: Ungültiger Datenstrom in TDS-Protokoll. Unerwartetes token unknown token (0xA3).
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2924)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2913)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.throwInvalidTDSToken(SQLServerConnection.java:2903)
	at com.microsoft.sqlserver.jdbc.TDSReader.throwInvalidTDSToken(IOBuffer.java:6335)
	at com.microsoft.sqlserver.jdbc.TDSParser.throwUnexpectedTokenException(tdsparser.java:149)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:134)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1620)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:594)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2979)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:505)
	at Starter.main(Starter.java:21)
```

4. Any other details that can be helpful: Same problem with dotnet, see [here](https://github.com/dotnet/SqlClient/issues/365), also works with SQL Server 2017.

## Reproduction code
```
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;

public class Starter
{
  public static void main(String[] argv) throws ClassNotFoundException
  {
    String username = "username";
    String password = "password";
    String url = "jdbc:sqlserver://localhost;databaseName=TestDb";
    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
    try{
      Connection conn = DriverManager.getConnection(url, username, password);
      final CallableStatement prepareCall = conn.prepareCall("{call dbo.NativeProdForTesting}");
      prepareCall.execute();
    }catch (Exception e){
      e.printStackTrace();
    }
  }
}
```

**Comment by Genmutant** [comment] 2020-01-03 16:12
> Introduced in TDS 7.4, the DATACLASSIFICATION token SHOULD<39> describe the data
classification of the query result set.
Token Stream Comments:
 The token value is 0xA3.
 This token only be sent by the server if the client sends a DATACLASSIFICATION FeatureExt in the
Login message and the server responds with a DATACLASSIFICATION FeatureExtAck. When this
token is used, the token is sent by the server in response to every SQLBatch request.

**Comment by rene-ye** [comment] 2020-01-03 17:08
Hi @Genmutant, thanks for reporting this, we'll take a look into this.

**Comment by ulvii** [comment] 2020-01-22 21:26
Hi @Genmutant ,
We are working with server team on resolving the issue. Please stay tuned.

**Comment by Genmutant** [comment] 2020-02-18 13:30
Fixed in Sql Server 2019 CU2: https://support.microsoft.com/en-us/help/4538342/fix-latest-drivers-fail-to-work-with-in-memory-compiled-queries-in-sql

**Comment by ulvii** [comment] 2020-02-18 18:56
Hi @Genmutant ,
Glad the issue is resolved. I am closing the issue, please let us know if you have any other questions.

**Closed by ulvii** 2020-02-18 18:56 UTC
