### ISSUE TITLE
issue due to rounding of timestamps

### ISSUE THREAD

**Issue by AlBundy33** [microsoft/mssql-jdbc#1843] opened 2022-06-03 13:25 UTC
## Driver version
10.2.0

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2 (X64) 
	Jan 12 2022 22:30:08 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 20.04.3 LTS) <X64>

## Client Operating System
Windows 10 but also affects Ubuntu

## JAVA/JVM version
OpenJDK 11 but also affects Oracle Java 8

## Description

We've recently tried to switch from jTDS to mssql-jdbc-driver which seems to work pretty good in most cases.
But there seems to be an issue due to the rounding of timestamps in mssql-jdbc because if we write a tiemstamp with System.currentTimeMillis() in the database, read the value from the database and try to update all records with timestamp >= the previous read tiemstamp this doesn't work for some values.

## Test-case

I hope this test-case will describe the problem better :-)
-> This test-case is similar to some logic in our application that currently fails in our integration tests.

I've used com.microsoft.sqlserver.jdbc.preparedStatement.SetObjectTest as base - not sure if this is the right place.

```
    @Test
    public void testTimestampRounding()
        throws SQLException
    {
      try (Connection con = getConnection())
      {
        final String tableName = "sometesttable";
        try (Statement stmt = con.createStatement())
        {
          stmt.executeUpdate("CREATE TABLE " + AbstractSQLGenerator.escapeIdentifier(tableName)
              + " (id INT PRIMARY KEY, ts datetime)");

          try
          {
            final long millis = System.currentTimeMillis();
            for (int i = 0; i < 100; i++)
            {
              // 1. create a timestamp
              final Timestamp preparedTimestamp = new Timestamp(millis + i);
              // 2. insert timestamp
              try (PreparedStatement pstmt = con.prepareStatement(
                  "INSERT INTO " + AbstractSQLGenerator.escapeIdentifier(tableName) + " (id, ts) VALUES (?, ?)"))
              {
                pstmt.setInt(1, i);
                pstmt.setObject(2, preparedTimestamp);
                pstmt.executeUpdate();
              }

              // 3. read timestamp from db
              Timestamp timestampFromDatabase = null;
              try (PreparedStatement select = con.prepareStatement("select ts from " + AbstractSQLGenerator.escapeIdentifier(tableName)
                + "where id = ?"))
              {
                select.setObject(1, i);
                try (ResultSet rs = select.executeQuery())
                {
                  Assert.assertTrue(rs.next());
                  timestampFromDatabase = rs.getTimestamp(1);
                }
              }
              Assert.assertNotNull(timestampFromDatabase);

              // 4. now try to update all records for our ID (I know - it's the PK ...) and where the ts >= as the timestamp read from database
              // -> the expceted behavior is, that the record is updated but this doesn't work allways - I think this is due to some roundings in the driver
              try (PreparedStatement update = con.prepareStatement("update " + AbstractSQLGenerator.escapeIdentifier(tableName) + " set ts = null where id = ? and ts >= ?"))
              {
                update.setObject(1, i);
                update.setObject(2, timestampFromDatabase);
                assertEquals(1, update.executeUpdate(),
                    "i=" + i + ", timestampFromDatabase=" + timestampFromDatabase + ", millies=" + timestampFromDatabase.getTime() + ", nanos=" + timestampFromDatabase.getNanos()
                    + ", preparedTimestamp=" + preparedTimestamp);
              }
            }
          }
          finally
          {
            TestUtils.dropTableIfExists(AbstractSQLGenerator.escapeIdentifier(tableName), stmt);
          }
        }
      }
    }
```

I don't know if step 3 or 4 is the problem but this test always fails with my local database with very low values of i.

The expected behavior would be that I could search with the original values from database.

**Comment by v-zhangw** [comment] 2022-06-03 23:18
Hi @AlBundy33, thanks for reaching out, we will take a look at this issue soon.

**Comment by v-zhangw** [comment] 2022-06-07 20:14
Hi @AlBundy33,

Could you elaborate on what your expected behavior is? The program appears to be "working" properly when I run it. The assert will fail whenever it encounters a row where it doesn't need to update anything.

**Comment by AlBundy33** [comment] 2022-06-07 20:50
If you get a timestamp (ts) from db and then query or update all records where the timestamp-column >= ts i would expect that also the row is updated where i got the timestamp from.

In my first example the row with the timestamp was not updated even the timestamp >= ts because i got it first from database.



Another example (not tested but makes it hopefully clear)
`ts = select min(timestamp_column) from sometable`

This should now get all records including the row where we get the timestamp from in first place
`select * from sometable where timestamp_column >= ts`

but depending on the used millis it seems that the original record is skipped.

If you execute the posted test it should fail.

**Comment by v-zhangw** [comment] 2022-06-07 21:18
Comparing a java Timestamp to a datetime column on sql server will not have accurate results.
https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver16
Datetime actually rounds to the .000, .003, or .007 of seconds.

**Comment by David-Engel** [comment] 2022-06-07 23:30
This is an issue with how the database handles comparisons between datetime and datetime2 values. The driver sends timestamp parameters as datetime2, but the column is a datetime. (This worked great up until SQL Server 2016.) When the database converts the datetime to a datetime2 for comparison with the more precise datetime2 parameter, you can get unexpected results.

For more details and workarounds, see these links:
https://github.com/Microsoft/mssql-jdbc/wiki/Addressing-datetime-to-datetime2-conversion-behavior-change-starting-from-SQL-Server-2016

https://github.com/microsoft/mssql-jdbc/issues/680
(Particularly this comment: https://github.com/microsoft/mssql-jdbc/issues/680#issuecomment-382472960)

> Due to the data handling accuracy "improvements" in 2016, datetime values are made more "accurate" when converting to datetime2 since datetime is actually granular to 1/300 of a second.

Regards,
David

**Comment by AlBundy33** [comment] 2022-06-08 08:28
So you don't think that this behafior is a bug?

If I read a valie A from database and query all records with value A afterwards I would expect to get all the records including that one where I've got value A from in first place.

With jTDS driver for example this issue doesn't exists.

**Comment by v-zhangw** [comment] 2022-06-10 17:40
Hello @AlBundy33,
Does that answer your queries regarding this issue?

**Comment by AlBundy33** [comment] 2022-06-10 19:35
I'm not really sure about that. 😄 
I totally understand the problem mapping a timestamp to datetime and datetime2.
And I would also choose the datatype with the higher precission.

The problem is that the current behavior is totally unxpected when working with datetime.
and because there is no exception and "just" missing or to much rows that may result in unexpected application states.

Setting compatibility mode to an older version may workaround the problem but if we forget to change the settings in existing and future customer database we have rhe same problem as mentioned above.
Also I'm not sure how long a specific compat-mode is supported by sql server.

Is there really no chance that you can handle this on driver side?
What about a "low-precission-datetime-mode" that sends timestamps always as datetime?
I would expect that most applications using just one of the datatypes.

**Comment by v-zhangw** [comment] 2022-06-10 20:47
There probably are ways to handle it driver side, and you are free to make a feature request, however this is simultaneously 
1. Probably not trivial to implement
2. Would have to have server version specific behavior
3. Not high priority since datetime2 does exist and works

So it would take a long time and likely a rather unexpectedly smooth semester to get this in.

**Comment by AlBundy33** [comment] 2022-06-12 19:50
It seems that #443 describes the same issue and already has a linked feature-request #1590 with a pull-request.

It would be really good to have an option to choose between how timestamps are interpreted.

**Comment by AlBundy33** [comment] 2022-06-14 23:41
Problem is also described in #1520

**Comment by Jeffery-Wasty** [comment] 2023-01-31 21:04
#1687 resolves this by allowing users to specify the datatype to use for date/timestamp parameters. @AlBundy33, please let us know if this fix (included in 12.2+) works for you. Closing issue, but can reopen if needed.

**Closed by Jeffery-Wasty** 2023-01-31 21:04 UTC

**Comment by AlBundy33** [comment] 2023-02-16 11:24
thank you - seems to work 👍

**Comment by rlconst** [comment] 2025-08-26 08:52
`ALTER DATABASE database_name SET COMPATIBILITY_LEVEL = 120` seems the easies fix.
IMO this should be explicitly stated in javadocs on `setDate` and especially `setTimestamp` methods
