### ISSUE TITLE
Bulk copy: Conversion failed on OffsetDateTime to DATETIME2

### ISSUE THREAD

**Issue by tlopesPT** [microsoft/mssql-jdbc#2518] opened 2024-09-23 14:20 UTC
## Driver version
- 12.8.1.jre11

## SQL Server version
- Microsoft SQL Server 2022 (RTM-CU13) (KB5036432) - 16.0.4125.3 (X64) 
- Azure SQL
- AWS RDS with latest available engine (2022)

## Client Operating System
MacOS

## JAVA/JVM version
- Azul Zulu version 11.0.22

## Table schema
`CREATE TABLE dt_bug(dt DATETIME2);` 

## Problem description
When inserting an OffsetDateTime with both **seconds and nanoseconds set to zero** using Bulk copy, the insert fails with `java.sql.BatchUpdateException: Conversion failed when converting date and/or time from character string.` 

```
// testing against local docker container https://hub.docker.com/r/microsoft/mssql-server
final SQLServerDataSource ds = new SQLServerDataSource();
ds.setURL("jdbc:sqlserver://;serverName=localhost;databaseName=db-name");
ds.setEncrypt("false");
ds.setUser("username");
ds.setPassword("password");
ds.setUseBulkCopyForBatchInsert(true);
final Connection con = ds.getConnection();

final OffsetDateTime odt = OffsetDateTime.now().withSecond(0).withNano(0);
final PreparedStatement ps = con.prepareStatement("insert into dt_bug(dt) values(?)");
ps.setObject(1, odt);
ps.addBatch();
ps.executeBatch();
```

However, this prepared statement succeeds with Bulk copy disabled: `ds.setUseBulkCopyForBatchInsert(false);`

## Expected behavior
Prepared statement succeeds when using Bulk copy.

## Actual behavior
Prepared statement fails when using Bulk copy.

## Error message/stack trace
```
Conversion failed when converting date and/or time from character string.
java.sql.BatchUpdateException: Conversion failed when converting date and/or time from character string.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2231)
```

**Comment by Jeffery-Wasty** [comment] 2024-09-23 23:08
Hi @tlopesPT,

I'm looking into this. Curiously, this looks like a problem we already resolved with a previous PR, yet you are using the latest version. I'll let you know what we find out.

**Comment by Jeffery-Wasty** [comment] 2024-09-24 20:04
Hi @tlopesPT,

Looks like I was incorrect, the previous PR was concerning `LocalDateTime`, not `OffsetDateTime`. 

Regarding `OffsetDateTime`, this has actually been brought up previously (https://github.com/microsoft/mssql-jdbc/issues/1363) and the reply we gave was that users "are expected to provide a `DateTimeOffset` object along with providing `microsoft.sql.DateTimeOffset` as the column type when performing bulk copy". Using only an `OffsetDateTime` object is not supported, neither is there a conversion we can do on our end. I'll bring this up with the team, maybe there is something else we can do that I'm missing, but it appears the scenario you are executing above is not supported.

**Comment by Jeffery-Wasty** [comment] 2024-09-25 17:32
Since this is intended behavior we'll move forward with closing this issue. Please let us know if you have any additional questions.

**Closed** 2024-09-25 18:31 UTC

**Comment by tlopesPT** [comment] 2024-09-26 09:16
Using microsoft.sql.DateTimeOffset is not an option since that is listed as [not supported on Bulk copy API for batch insert](https://learn.microsoft.com/en-us/sql/connect/jdbc/use-bulk-copy-api-batch-insert-operation?view=sql-server-ver16#known-limitations), which is why we're using DATETIME2 instead.
Regardless, thank you for the explanation, I'll look into alternatives.
