### ISSUE TITLE
[BUG] Parameter metadata checking incorrectly parses column names preceded by "(" parenthesis in WHERE clause

### ISSUE THREAD

**Issue by drewclauson** [Microsoft/mssql-jdbc#921] opened 2019-01-07 22:27 UTC
## Driver version
7.0.0

## SQL Server version
Microsoft SQL Server 2008 R2 (SP2) - 10.50.4000.0 (X64) 
	Jun 28 2012 08:36:30 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

## Client Operating System
Mac OS Mojave

## JAVA/JVM version
jre8
## Table schema
```
CREATE TABLE Foo
(
  Bar VARCHAR(50) NOT NULL
)
```

## Problem description

1. Expected Behaviour: When executing the following query, return the correct data
`SELECT Bar from Foo WHERE (Bar = 'test')`
2. Actual behaviour:
Error thrown: "Incorrect syntax near the keyword 'FROM'."
3. Error message/stack trace:
`Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'FROM'.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:254) ~[mssql-jdbc-7.0.0.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1608) ~[mssql-jdbc-7.0.0.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:859) ~[mssql-jdbc-7.0.0.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:759) ~[mssql-jdbc-7.0.0.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7240) ~[mssql-jdbc-7.0.0.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2869) ~[mssql-jdbc-7.0.0.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:243) ~[mssql-jdbc-7.0.0.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:218) ~[mssql-jdbc-7.0.0.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQuery(SQLServerStatement.java:688) ~[mssql-jdbc-7.0.0.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerParameterMetaData.<init>(SQLServerParameterMetaData.java:653) ~[mssql-jdbc-7.0.0.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getParameterMetaData(SQLServerPreparedStatement.java:3057) ~[mssql-jdbc-7.0.0.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getParameterMetaData(SQLServerPreparedStatement.java:3068) ~[mssql-jdbc-7.0.0.jre8.jar:na]
	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.getParameterMetaData(DelegatingPreparedStatement.java:221) ~[tomcat-dbcp.jar:7.0.92]
	at org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement.getParameterMetaData(DelegatingPreparedStatement.java:221) ~[tomcat-dbcp.jar:7.0.92]
`
4. Any other details that can be helpful:
It looks like the parser for getting the metadata is including preceding parenthesis when it parses for column names.  If turn off metadata checking, it works just fine with the preceding parenthesis  When I re-enable metadata checking, the following SQL statement works just fine, returning rows.  Note the space between `(` and `Bar`
`SELECT Bar from Foo WHERE ( Bar = 'test')`

**Comment by peterbae** [comment] 2019-01-07 22:51
Hi @drewclauson, thanks for contacting us. I'm not able to reproduce the issue - could you let us know how you're turning off metadata checking, and if possible, provide us with a standalone java application (using our driver) that can repro this issue? Thanks.

**Comment by drewclauson** [comment] 2019-01-08 01:15
Whoops, I didnt explicitly state that I'm using a prepared statement.  I'll send a better example tomorrow.

SELECT Bar from Foo WHERE (Bar = ?)

**Comment by drewclauson** [comment] 2019-01-08 15:35
If you use this, it works and returns rows.
`String SQL = "SELECT * FROM Foo WHERE ( Bar LIKE ?)";`

However, this throws an error and debugging shows that the column name in the parameter query includes the leading parenthesis:
`String SQL = "SELECT * FROM Foo WHERE (Bar LIKE ?)";`

![image](https://user-images.githubusercontent.com/10655807/50840705-236a3900-1331-11e9-8177-2862154271f8.png)
(above is SQLServerStatement.java)

**Comment by peterbae** [comment] 2019-01-08 17:37
Thanks @drewclauson. Currently our driver relies on FMTONLY instead of `sp_describe_undeclared_parameters` when calling `getParameterMetaData()` in SQL Server 2k8R2, and it seems like there's an issue with the parse logic using FMTONLY. This is related to other FMTONLY related issues (such as https://github.com/Microsoft/mssql-jdbc/issues/493), and we'll keep this issue in mind going forward.

**Comment by drewclauson** [comment] 2019-01-08 17:57
@peterbae - Thanks.  Looks to me like the opening parenthesis just may need to be included in the delimiter string in the StringTokenizer on line 82 of SQLServerParameterMetaData.java.  Hope that helps, thanks!

**Comment by peterbae** [comment] 2019-01-09 18:02
Issue is being tracked in #927, closing this issue.

**Closed by peterbae** 2019-01-09 18:02 UTC
Labels: bug
