### ISSUE TITLE
Getting "[S0102][9105] The provided statistics stream is corrupt." on Update Statistics in Azure sql Datawarehouse

### ISSUE THREAD

**Issue by souravjha77** [microsoft/mssql-jdbc#1257] opened 2020-02-06 18:38 UTC
## Driver version
8.1.1.jre8-preview

## SQL Server version

Effective version: Azure SQL Database (ver. 12.0.2531)
## JAVA/JVM version

Cent OS 7 

## Table schema

Number of columns: 7
Total Number of rows : 0.5 Million
Data types of columns:  int,int, varchar, varchar, float,float,date

## Problem description

Ran following command: "Update statistics <table_name>"
1. Expected behaviour: The above query should pass
2. Actual behaviour:  failed with below mentioned error.
3. Error message/stack trace: [S0102][9105] The provided statistics stream is corrupt." 
4. Any other details that can be helpful: I have tried rebuilding the index as well as creating new statistics. But, both failed with same error mentioned in 3.

## Reproduction code

Just run the code "Update statistics <table_name>" from  intellij database tool / azure synapse ui

**Comment by ulvii** [comment] 2020-02-06 20:26
@souravjha77 , please feel out the template and provide more details.

**Comment by souravjha77** [comment] 2020-02-07 10:53
@ulvii I have added the command. let me know if you need any other details

**Comment by rene-ye** [comment] 2020-02-07 16:57
Please fill out the sections "Table schema" as well as "Reproduction Code".

**Comment by souravjha77** [comment] 2020-02-07 17:27
@rene-ye updated details of the column and table

**Comment by ulvii** [comment] 2020-02-07 18:21
Hi @souravjha77 ,
A quick search of the error message makes me think that the issue is happening on the server side. Are you seeing the same error message when you run the query on SSMS or Azure query editor? If yes, please contact Azure support team instead.

**Comment by ulvii** [comment] 2020-02-18 19:15
This does not seem to be a driver issue, closing. Please feel free to re-open it in case if you have any questions.

**Closed by ulvii** 2020-02-18 19:15 UTC
