### ISSUE TITLE
Memory leak in driver version 10.2.0?

### ISSUE THREAD

**Issue by marthursson** [microsoft/mssql-jdbc#1760] opened 2022-03-03 16:06 UTC
## Driver version
10.2.0

## SQL Server version
Tested against several different SQL server versions; this is clearly not server version dependent.

## Client Operating System
Tested on various Windows versions, as well as OSX; this is clearly not operating system dependent.

## JAVA/JVM version
Corretto 17

## Table schema
Not applicable

## Problem description
Following update from version 9.4.1.jre11 to 10.2.0.jre17 our application consumes considerably more memory and exhibits clear signs of a memory leak when pooling a a number of JDBC connections. Everything except the driver version (Client OS, SQL server, JRE, application code)  is exactly the same, so the only reasonable explanation is that the driver update causes the problems.
Example heap memory consumptions in our application (i.e. amount of memory not available for GC) with 50 pooled, mostly idle connections (only a query or two per second):

- 9.4.1.jre11: 206MB; GC will reliably release memory down to this level over time, i.e. no signs of memory leak.
- 10.2.0.jre17: 244MB; this floor quickly increases over time - after only a couple of minutes it's up to 273MB, eventually causing an OutOfMemoryError.

Again: everything is exactly the same except for the driver update, and this behaviour is consistent on different platforms. We have been using this driver in previous versions for years in the exact same way without any indication of these kinds of problems.

## Expected behavior
After deploying a new version without any documented breaking changes I would have expected everything to work as it did before.
## Error message/stack trace
OutOfMemoryError eventually follows, as the memory incrementally consumed by the connections appears to be difficult to GC.

**Comment by Jeffery-Wasty** [comment] 2022-03-03 17:34
Hi @marthursson, 

Thank you for your report, we'll look into it further and get back to you as soon as we can. To assist us in handling this issue, any additional details or documentation that you can provide, would be appreciated. The most useful would be:

- A application reproducing the bug seen above
- A complete stack trace of the error
- Any queries and table schema used leading to the appearance of the bug

**Comment by marthursson** [comment] 2022-03-04 09:14
@Jeffery-Wasty

- There is no specific stack trace to point out (the `OutOfMemoryError` doesn't necessarily occur related to JDBC access, it's just that eventually there's no more heap space so that error can happen pretty much anywhere). I'm monitoring the memory usage in `jconsole`and the occupied memory after GC increases over time.
- As far as I can see it's not related to any specific query; this happens when the application is is in idle mode so there are no statements executed that returns any data; only very simple select queries. Pretty much all of the actual statements are initiated periodically by the DB pool to verify that the connections are still alive (i.e. `SELECT 1`).

At this time I don't have the time to set up an isolated application demonstrating the problem or dive too deeply into troubleshooting. We're basically fine with the previous version of the driver for now, but it felt reasonable to report this problem since clearly something significant has changed in the latest version. However the relevant basics of our application is as follows:

- A Spring (version 5.3.10) application using Spring JDBC for DB access, running in Tomcat 9
- Connection pooling is managed by the application (as opposed to the Tomcat container) using [Commons DBCP2](https://commons.apache.org/proper/commons-dbcp/) (version 2.9.0)
  - Relevant settings are: `initialSize` = `maxTotal` = `maxIdle` = `minIdle` = 50, `testWhileIdle` = `testOnBorrow`= true, `validationQuery=SELECT 1`. 
  - Connection properties:
    - `encrypt=false`
    - `socketTimeout=1000000`
    - `queryTimeout=`900`
    - prepared statement caching is off (more specifically: on or off doesn't appear to make any difference).

I do hope the above will help you figure out what's happening.

**Comment by Jeffery-Wasty** [comment] 2022-03-04 18:21
Hi @marthursson,

Thank you for the above, it certainly helps. If you're able to, can you try using the 10.1.0 preview release, and verify whether the same issues arise? This will help us in narrowing down the problem to either the 10.1.0 or 10.2.0 release.

**Comment by waynerijsdijk** [comment] 2022-03-07 16:35
I've encountered the exact same problem after migrating from 9.4.1.jre11 to 10.2.0.jre11.  This application used 200mb on average at 9.4.1. After the migration to 10.2.0 it repeatedly OOM'd at 500mb+. One of my colleagues made a heap dump to analyze this problem. Does that help? Screenshot below:

![image](https://user-images.githubusercontent.com/1432815/157076284-0adc213a-095f-48dc-b1f0-d9e43df00ca0.png)

**Comment by Jeffery-Wasty** [comment] 2022-03-07 17:39
Hi @waynerijsdijk,

Thank you, this does help. Can I ask of you the same thing I asked the original poster, that is, does this still happen with the 10.1.0 preview release? A reproduction app would also be useful, but in lieu of this, would you be able to provide your application setup and/or environment?

**Comment by lilgreenbird** [comment] 2022-03-07 19:54
hi @waynerijsdijk 

do you have a standalone java repro app for the issue?

**Comment by waynerijsdijk** [comment] 2022-03-08 18:48
The application that I have checked today had an average memory usage of around 144mb (max mem usage in 3 weeks of runtime was around 350mb) with driver 9.4.1-jre11. It has setting encrypt=false and it uses integrated security as authentication. That's my baseline.

The exact same application uses 553mb after running for two hours with driver 9.5.0-jre11-preview. The memory usage seems to grow way faster starting from 10.1.0-jre11-preview. It took about 45 minutes to reach 500mb+. The same behavior as 10.1.0-jre11-preview is seen in 10.2.0-jre11.

I checked 10.2.0-jre11 with user/pass auth (instead of integrated security authentication), but that does not provide me with any better results.

It looks like the troubles started in 9.5.0-jre11-preview somehow and got worse after that. I don't have a standalone reproduction app for this problem (yet) @lilgreenbird.

**Comment by Jeffery-Wasty** [comment] 2022-03-09 17:32
The information provided so far has been very helpful, but we're still unsure on a few key points. We're mostly interested in what happens before memory leak occurs, that is, while the leak may be observed during application idle, or during a few small queries, knowing what is done beforehand is probably more useful for our purposes.

@marthursson I know you mentioned its not related to any specific query, but is there some other commonality that could be present? Could the leak be showing up after many successive queries, does it show after both reads and writes?

@waynerijsdijk Is the leak also observed during an idle state? Similarly, is there any common traits between what happens before the leak is observed?

Again, thank you both for all the information provided so far, any further information you can supply would be greatly appreciated.

**Comment by marthursson** [comment] 2022-03-10 07:54
@Jeffery-Wasty In this case idle mode means that the open connections are mostly just sitting there, waiting for stuff to do. There are no updates, and the only queries that happen are:

- `SELECT 1` (issued by the connection pool for checking that the connections are still alive)
- `SELECT TOP 1 id FROM stuff_to_do WHERE start_time <= GetDate()` (this is obviously not the exact SQL; the point is that it's a very simple query, and it never returns any data when the application is in this state).

Without any knowledge of the inner workings of the driver, my guess would be that this is related to long-living connections in general. Note that the application connection pool will keep the connections alive for the entire application lifetime. Dead connections will be discarded by the driver and new ones will be created immediately, so if connections actually die and the driver fails to properly clean up resources related to that it could also possibly be a problem (note that I have not noticed anything to indicate that the connections actually die, I'm merely speculating).

**Comment by marthursson** [comment] 2022-03-10 13:01
@Jeffery-Wasty Tried with 10.1.0.jre11-preview and it appears the problem is present in that version as well.

**Comment by Jeffery-Wasty** [comment] 2022-03-10 20:29
@marthursson Thank you for the update. It would help us narrow the problem down even more if you would be able to confirm whether the problem persists with the 9.5.0-jre11 preview.

**Comment by Jeffery-Wasty** [comment] 2022-03-16 23:42
An update on our end. We've been unable to replicate the leak so far, testing in version 10.2.0jre17. This includes tests designed to mimic the results posted @waynerijsdijk, where large amounts of data are read and written. And where the connection is kept alive for a long time.

To proceed with this, we'll need a little bit more info on the situation:

@marthursson - What does the application do before it becomes idle? You're absolutely right that nothing done during the idle state should lead to a problem, but some more information about what happens beforehand would be useful. Is it a transaction with a large amount of data? Many transactions? Is the same type of operation performed before the application is idle? What about the type of data being used? Anything helps here.

@waynerijsdijk - Similar to above. What is happening in your situation before the memory leak. You mention it takes ~45mins to get to ~500mb of usage. Is it similar to @marthursson where the application is in an idle state? If not what is being done during that time?

This is an issue we would like to solve as soon as we can and so any information you can provide will immediately be put to use.

**Comment by Jeffery-Wasty** [comment] 2022-03-23 17:59
Regarding our status on the issue: we're still unable to replicate the bug in the versions mentioned above. Without further information we are unable to progress on this issue. From previous comments it would seem that both of you do have some workaround the problem, by using older versions, so, unless new information is provided, we will move forward on closing this issue one week from this date.

**Comment by lilgreenbird** [comment] 2022-03-25 19:42
hi @marthursson @waynerijsdijk 

As mentioned we have tried our best to try to reproduce this issue by running stress tests and profiling to mimic the results as seen above however we are unable to see any memory issues despite our efforts. It seems this may exist in some edge cases that we are unable to see at the moment that is why we were asking for more information to help identify the root cause. Without more info there is not much more we could do at this point so we regret to have to close this issue for now. If you have more info please feel free to request re-opening. Thanks.

**Closed by lilgreenbird** 2022-03-25 19:42 UTC
Labels: Under Investigation

**Comment by dballardgh** [comment] 2022-04-21 17:21
Hi @lilgreenbird,

I'm encountering what appears to be the same memory leak as reported by @marthursson and @waynerijsdijk. While I don't have a standalone test case that I can share with you at this time, I can recreate the problem easily in my test environment, so perhaps I can help. My test uses a connection pool. In my test scenario, I'm only changing the driver. What I see is:

- 9.2.1.jre11 works
- 9.4.1.jre16 works
- 9.5.0-SNAPSHOT.jre17-preview leak present
- 10.2.0.jre17 leak present

Using 9.4.1.jre16, memory looks like:
![image](https://user-images.githubusercontent.com/8827919/164509646-9c1a64fd-b8fc-4771-8457-a65e5b4465ba.png)

Using 9.5.0-SNAPSHOT.jre17-preview or 10.2.0.jre17:
![image](https://user-images.githubusercontent.com/8827919/164509878-fbc77dd2-9048-467d-a718-e6ee4e72da74.png)

Visualvm memory profile shows the following near the end of the run for 9.4.1.jre16:
![image](https://user-images.githubusercontent.com/8827919/164514981-90a6a5e3-96c5-4391-b32e-7475d26368f0.png)

The profile near the end of the 10.2.0.jre17 run shows:
![image](https://user-images.githubusercontent.com/8827919/164515069-b4f071b4-94ce-4261-a124-4247db8fb81d.png)

So this superficially looks like a leak of prepared statements, but only after some triggering event. Not sure what that event is yet though.

**Comment by dballardgh** [comment] 2022-04-22 01:09
Upon reviewing the heap, I think the issue I've encountered has been reported as #1781.

**Comment by lilgreenbird** [comment] 2022-04-27 20:19
hi @dballardgh 

Thanks for the info, yes we have fixed that in our [11.1.1 release,](https://github.com/microsoft/mssql-jdbc/releases/tag/v11.1.1) could you please verify if this fixed your issue?
