### ISSUE TITLE
Prepared statement with named parameters throws Exception

### ISSUE THREAD

**Issue by ighack** [microsoft/mssql-jdbc#1569] opened 2021-04-22 07:45 UTC
```
<dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>9.2.1.jre8</version>
        </dependency>

```

`select * from tablename t where t.GOODS_ID=@GOODS_ID and GOODS_LONTO=@GOODS_LONTO`

```
SQLServerCallableStatement scall = null;
SQLServerConnection connection = conn.unwrap(SQLServerConnection.class);
scall = (SQLServerCallableStatement)connection.prepareCall(SQL);
scall.setObject(obj.getString("ParameterName"), obj.get("Value"), obj.getInteger("Type"));
```

I get "com.microsoft.sqlserver.jdbc.SQLServerException"

**Comment by v-zhangw** [comment] 2021-04-22 17:04
Hi ighack,

Could you please provide a db schema and more complete reproduction? It is very difficult to extrapolate a repro with just what is given. In addition could you provide the full stack trace for the error?

**Comment by v-chojas** [comment] 2021-04-22 23:11
Could #553 and #1314 be related?

**Comment by ighack** [comment] 2021-04-23 00:38
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.join.lmis.dao.impl.ExecFunCommon.ExecutePCFun(ExecFunCommon.java:281)
	at com.join.lmis.controller.PCAccessController.PCSerCall(PCAccessController.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: com.microsoft.sqlserver.jdbc.SQLServerException: com.microsoft.sqlserver.jdbc.SQLServerException: 没有为存储过程  定义参数 GOODS_ID。
	at com.join.lmis.sqlhelper.AccessCommon.getResultBySQLName_SqlServer(AccessCommon.java:1649)
	at com.join.lmis.common.Method.GetDataByBindPara(Method.java:462)
	... 59 more

**Comment by ighack** [comment] 2021-04-23 00:45
SQLServerCallableStatement scall = null;
SQLServerConnection connection = conn.unwrap(SQLServerConnection.class);
scall = (SQLServerCallableStatement)connection.prepareCall(SQL);
scall.setObject(obj.getString("GOODS_ID"), obj.get("Value"), obj.getInteger("Type"));

I just use SQL like "select * from tablename t where t.GOODS_ID=@GOODS_ID and GOODS_LONTO=@GOODS_LONTO"
I want bind value with name.

in  scall.setObject(obj.getString("GOODS_ID"), obj.get("Value"), obj.getInteger("Type"));  I get error

com.microsoft.sqlserver.jdbc.SQLServerException: com.microsoft.sqlserver.jdbc.SQLServerException: No parameters defined for stored procedure  GOODS_ID。

I'm not good at english, so I use machine translate "没有为存储过程 定义参数 GOODS_ID"

**Comment by lilgreenbird** [comment] 2021-04-24 01:33
hi @ighack 

As per @v-zhangw 's request, could you please send us a more complete repro of the issue? The above is just a code fragment it doesn't show the definition of obj? Please provide the full Java application and the database schema used.

In addition, please also fill in the [fields in the new issue template](https://github.com/microsoft/mssql-jdbc/issues/new) when opening a new issue that would provide us with more info.

Thanks

**Comment by ighack** [comment] 2021-04-25 01:28
## Driver version
mssql-jdbc:9.2.1.jre8

## SQL Server version
Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64)   Apr  2 2010 15:48:46   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) 

## Client Operating System
windows 10

## JAVA/JVM version
1.8.0_281

## Table schema


四月 25, 2021 9:15:06 上午 com.microsoft.sqlserver.jdbc.TDSChannel enableSSL
警告: TLSv1 was negotiated. Please update server and client to use TLSv1.2 at minimum.
com.microsoft.sqlserver.jdbc.SQLServerException: com.microsoft.sqlserver.jdbc.SQLServerException: 没有为存储过程  定义参数 GOODS_ID。
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234)
	at com.microsoft.sqlserver.jdbc.SQLServerCallableStatement.findColumn(SQLServerCallableStatement.java:1340)
	at com.microsoft.sqlserver.jdbc.SQLServerCallableStatement.setObject(SQLServerCallableStatement.java:1576)
	at App.main(App.java:36)

## JDBC trace logs


## Reproduction code
Logger logger = Logger.getLogger("com.microsoft.sqlserver.jdbc");
logger.setLevel(Level.ALL);
Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
String connectionUrl = "jdbc:sqlserver://10.76.37.24:1433;Database=PictureManage;integratedSecurity=false;";
Properties pro = new Properties();
pro.put("user","****");
pro.put("password","*****");
Connection con = DriverManager.getConnection(connectionUrl,pro);
CallableStatement st = con.prepareCall("select * from tablename t where t.GOODS_ID=@GOODS_ID");
st.setObject("GOODS_ID","dfasdf");
ResultSet rs = st.getResultSet();

**Comment by karinazhou** [comment] 2021-04-27 21:50
Hi @ighack ,

After looking at your repro code, it looks like the way you pass the parameter to CallableStatement is not proper. Could you try it with the following code and see how it works?

```
CallableStatement st = con.prepareCall("select * from tablename t where t.GOODS_ID=?");
st.setStringg(1,"dfasdf");
```

You can also refer to this wiki page for using PreparedStatement:
https://github.com/microsoft/mssql-jdbc/wiki/PreparedStatement-metadata-caching

Thanks,

**Comment by ighack** [comment] 2021-04-28 01:52
I know PreparedStatement .but I need name parameters not index.
In C# we can 
```
SqlParameter sp = new SqlParameter("@GOODS_ID" SqlDbType.VarChar);
sp.Value ="dfasdf";
m_Command.Parameters.Add(sp);
m_Command.CommandText = "select * from tablename t where t.GOODS_ID=@GOODS_ID";
if (m_Adapter == null)
{
	m_Adapter = new SqlDataAdapter();
}
m_Adapter.SelectCommand = m_Command;
m_Adapter.Fill(dataSet, p_strTableName);
```

**Comment by ighack** [comment] 2021-04-28 02:12
I need name parameter like java with oracle

```
OracleCallableStatement ocall = (OracleCallableStatement) connection.prepareCall("select * from tablename t where t.GOODS_ID=:GOODS_ID");
ocall.setObjectAtName("GOODS_ID", "sfasdf");
rs = ocall.executeQuery();
```

**Comment by karinazhou** [comment] 2021-04-28 19:12
@ighack 
I am afraid that the ways using the named parameters in C# and oracle are not supported by mssql-jdbc. Your application needs to use `?` as the placeholder to pass the values. If you would like to use a designated parameter name like `@GOODS_ID`, 
you will need to use the stored procedure which wraps the query on the SQL Server. Define the parameter `@GOODS_ID` inside the sp and call it with CallableStatement. Here is an [example](https://github.com/microsoft/mssql-jdbc/issues/1314) for using stored procedure with CallableStatement.

**Comment by karinazhou** [comment] 2021-05-17 22:21
Hi @ighack ,
We are closing this issue due to no activities. Please feel free to contact us to reopen it if you have further questions.
Thanks!

**Closed by karinazhou** 2021-05-17 22:21 UTC
Labels: question

**Comment by ighack** [comment] 2021-05-18 00:48
SQLs are wrote by user, so I can't wraps the query.

**Comment by karinazhou** [comment] 2021-05-18 18:21
@ighack    I understood. We are sorry that mssql-jdbc doesn't support designated parameter names that cannot work as expected like C# and Oracle. To bypass the difficulty currently, you may either use PreparedStatement or change the query accordingly.
