### ISSUE TITLE
[QUESTION]  What is the right way to query a column with spaces in it? [getting Invalid column name]

### ISSUE THREAD

**Issue by nandinir-db** [microsoft/mssql-jdbc#2388] opened 2024-04-10 20:09 UTC
## Question
What is the right way to query a column with spaces in it?
SELECT * FROM xx.xx.xx 
WHERE "Name Space" = 'John' --1 // returns no result although we have a row with data John
WHERE `Name Space` = 'John' --2 // says Invalid column name '`Name Space`'.
WHERE [Name Space] = 'John' --3 // Invalid syntax - [PARSE_SYNTAX_ERROR] Syntax error
Stacktrace says it is from the com.microsoft.sqlserver.jdbc.SQLServerConnection

SELECT `Name Space` FROM xx.xx.xx works.

**Comment by barryw-mssql** [comment] 2024-04-11 18:38
I don't think there is anything wrong with the driver. This definitely looks like you have a incorrectly formatted SQL query. I have been able to successfully create 2 different queries, one in SQL Server Management Studio and the other in a test app:

select * from DemoDatabase.dbo.tblCountries where [Country Name]='Norway';
select * from DemoDatabase.dbo.tblCountries where "Country Name"='Norway';

Both queries successfully return the expected data.

Please let us know if this answers your question.

**Comment by Jeffery-Wasty** [comment] 2024-04-16 19:48
Hi @nandinir-db, 

Does the response above answer your question? Without further communication we'll assume the issue is resolved, and move forward with closing the issue.

**Comment by barryw-mssql** [comment] 2024-04-19 17:21
Hi @nandinir-db,

As we have not heard back from you, we will be closing this issue. Please feel free to reopen the issue if you need further assistance.

**Closed by barryw-mssql** 2024-04-19 17:21 UTC
Labels: Question
