### ISSUE TITLE
Jdbc driver not handling schema properly when using tvp parameters in stored procedures

### ISSUE THREAD

**Issue by gstojsic** [Microsoft/mssql-jdbc#37] opened 2016-11-27 16:07 UTC
This issue is referred to [here](https://connect.microsoft.com/SQLServer/Feedback/Details/3102655). Essentially the driver throws an error complaining that Sql server could not find the proper TVP type. The test that illustrates the problem can be found [here](https://github.com/gstojsic/mssql-jdbc-test/blob/master/src/test/java/com/skunkworks/MssqlJdbcTestApplicationTests.java#L82).

**Comment by v-xiangs** [comment] 2016-12-03 00:00
@gstojsic The issue is fixed by PR #47 based on your idea. thank you

**Closed by v-xiangs** 2016-12-03 00:00 UTC
Labels: bug, under testing
