### ISSUE TITLE
Azure WebApp, MSI Token Failure, missing 'expires_on' field in response

### ISSUE THREAD

**Issue by Nyffeneggerr** [microsoft/mssql-jdbc#2103] opened 2023-03-29 11:01 UTC
## Driver version
>=10.2.3 + 11.x

## Client Operating System
Linux / Docker

## JAVA/JVM version
Java 17

## Problem description
We are using Azure WebApp to run our Java/SpringBoot applications. For the authentication we are using the system assigned identity. That works well so far with JDBC version 9.4.1. Now we wanted to upgrade the JDBC driver version to 11.2.3.
With all JDBC versions from 10.2.3 on, we are getting the following error: `com.microsoft.sqlserver.jdbc.SQLServerException: MSI Token failure: Failed to acquire token from MSI Endpoint`.

After investigation, I found the following code change to be responsible for the issue (version 10.2.2 --> 10.2.3):
![image](https://user-images.githubusercontent.com/36026352/228512269-af50dd3d-3988-4f79-9155-01f0bec1dd11.png)

Before 10.2.3 the library was using the _expires-on_ field of the response. But with version 10.2.3 it now uses the _expires-in_ field. But this field is not existing in the response of the provided token service. Here is a (shorted) response example:
```
{"access_token":"ey...w","expires_on":"1680169483","resource":"https://database.windows.net/","token_type":"Bearer","client_id":"51481984-5176-4f0f-b02e-7812ea679522"}
```

As you can see, the _expires-in_ field is completely missing there. Any idea what is wrong here?

**Comment by Nyffeneggerr** [comment] 2023-03-30 05:42
Hi @Jeffery-Wasty 

Thanks a lot for your answer. We also tried to directly go to version 12.2.0, but there we get the following exception (again it is working in a VM but not on a Azure WebApp:
```
java.io.IOException: Server returned HTTP response code: 401 for URL: http://169.254.132.2:8081/msi/token?resource=https%3A%2F%2Fdatabase.windows.net%2F&api-version=2017-09-01
```

Do you have any idea about this issue?

Disabling TokenCache would be a valid option, I would say. Can this property be set in the JDBC connection string? Or does it need to be configured programmatically?

**Comment by Nyffeneggerr** [comment] 2023-03-31 06:44
Hi @Jeffery-Wasty again
Sorry for coming back again. Your suggestion to use a `msiTokenCacheTtl` of 0 doesn't solve the issue at all:
![image](https://user-images.githubusercontent.com/36026352/229043637-e413022b-ca54-4a25-bf3d-9c2e4a4d557a.png)

Still getting the famous 
```
com.microsoft.sqlserver.jdbc.SQLServerException: MSI Token failure: Failed to acquire token from MSI Endpoint
```

**Comment by Jeffery-Wasty** [comment] 2023-03-31 17:40
Hi @Nyffeneggerr,

It looks like there might be some confusion on our end. The changes we made for 12.1 should work for Azure _Functions_, but may not work for Azure _WebApps_. We're now examining whether we'll need to make additional changes to ensure compatibility for your use case. Thank you for bringing this to our attention.

**Comment by tkyc** [comment] 2023-03-31 17:52
Hi @Nyffeneggerr, for 10.2.3 it looks like a regression on webapps with MSI (I was able to reproduce your issue) we are in progress of doing more investigating. For 12.2.0, we were able to successfully auth with msi. Your `Server returned HTTP response code: 401` error makes me think it may be a permissions issue. Does the managed identity used on the azure webapp with 12.2.0 work on a VM as well?

**Comment by Nyffeneggerr** [comment] 2023-04-03 06:01
Hi @tkyc
I'm not 100% sure what you mean. We are using system assigned identities and they cannot be used across different services. But I always used the same webapp for testing different versions of JDBC drivers. With 10.2.2. everything worked for the given identity and I could fetch example data from database. With 12.1 + 12.2, the 401 appears.
I tested the same drivers with the same (test-) application on a VM (but with a different system assigned identity, because it's another service). There, everything with each version (9.x + 10.x + 11.x + 12.x) is working flawless.
Does this answer your question?

**Comment by tkyc** [comment] 2023-04-03 19:27
@Nyffeneggerr Yes, that answers my question thanks. This very strange, can you share a repro application that reproduces your 401 error? I want to test it on my end as I'm able to use system managed identities with webapps.

**Comment by tkyc** [comment] 2023-04-03 22:54
In case it helps, and for visibility, I've attached my test app to this comment that I used to perform a successful auth with 12.2.0.

[test-app.zip](https://github.com/microsoft/mssql-jdbc/files/11143018/test-app.zip)

**Comment by vitorcsbrito** [comment] 2023-04-04 09:20
Found the same issue after upgrading my app to spring boot 3.0.5. Updated the JDBC driver to 12.2 and added the msal4j and azure-identity dependencies according to the above test-app. The connection worked fine on spring boot 2.7.x where the JDBC driver used the 10.2.1.jre8 version without explicitly specifying the msal4j and azure-identity dependencies.

**Comment by Nyffeneggerr** [comment] 2023-04-04 11:01
Hi @tkyc 
Yes, I can give you the demo application. Its not much more than the demo code from the Microsoft website here: https://learn.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver16#connect-using-activedirectorymanagedidentity-authentication-mode

[database-jdbc-test-app.zip](https://github.com/microsoft/mssql-jdbc/files/11147705/database-jdbc-test-app.zip)

**Comment by tkyc** [comment] 2023-04-04 19:47
@Nyffeneggerr Thanks. I'm able to reproduce the error and I was able to fix it. So, you'll need to specify `msal4j 1.13.3` and `azure-identity 1.7.0` in your gradle file to fix the issue. These are the exact dependency versions the 12.2.0 driver are built with.

@vitorcsbrito Can you confirm the `msal4j` and `azure-identity` versions you used? 

Let me know if that resolves the issue for you guys.

**Comment by tkyc** [comment] 2023-04-04 21:54
Our doc [work-with-azure-active-directory-authentication](https://learn.microsoft.com/en-us/sql/connect/jdbc/feature-dependencies-of-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver16#work-with-azure-active-directory-authentication) should specify the dependency versions appropriate with each driver version. It looks like for 12.2.0 `msal4j 1.13.3` wasn't specified, we'll make an update.

**Comment by lilgreenbird** [comment] 2023-04-04 22:51
Just to add to the above, we should explicitly add to the doc @tkyc mentioned for reference however all the versions of dependent libaries are in explicit in the pom file in each release. One should always make sure to use the exact versions as specified in the pom file otherwise unexpected results may occur.

Please let us know if this resolves your issue or if you have more questions otherwise we will be closing this issue soon.

**Comment by vitorcsbrito** [comment] 2023-04-05 08:24
I had initially tried with the same version for `msal4j` but `azure-identity 1.8.1`.  Just gave a go at `azure-identity 1.7.0` and it worked perfectly! Thanks a lot for the help

**Comment by Nyffeneggerr** [comment] 2023-04-05 10:48
I can also confirm that `azure-identity 1.7.0` works as expected with JDBC `12.2.0`. So far you can close the ticket from my side. It would still be interesting (maybe not for us, but for others) if there is a chance that versions `>10.2.2<12.0.0` can work with system assigned identity in Azure WebApps.
Thanks a lot for your help!

**Comment by tkyc** [comment] 2023-04-05 17:07
Awesome, glad it worked. As for drivers `>10.2.2<12.0.0` we'll be releasing a hotfix and when that comes around I'll let you guys know in this thread.

**Comment by David-Engel** [comment] 2023-08-29 22:43
Closing since it's addressed in hotfix releases.

**Closed by David-Engel** 2023-08-29 22:43 UTC
Labels: Documentation

**Comment by OleksandrShkurat** [comment] 2023-10-09 14:05
Is it possible to publish these hotfix releases to Maven Central? 
They're still unavailable there and, as a result, they aren't included in the Spring-Boot BOM
Thank you in advance.
