### ISSUE TITLE
Batch fails when always encrypted is enabled in connection string

### ISSUE THREAD

**Issue by jezbera** [microsoft/mssql-jdbc#1301] opened 2020-04-02 07:17 UTC
## Driver version
8.2.2.jre11 (older versions are affected, too)

## SQL Server version
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Express Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 18363: ) (Hypervisor) 

## Client Operating System
Windows/Linux

## JAVA/JVM version
11.0.6

## Table schema
_Table will be created by test._
`create table TEST2 (KEY1 numeric(19,0) not null, KEY2 numeric(19,0) not null, primary key (KEY1, KEY2))`

## Problem description
Prepare database with always encrypted feature. Update connection details in ExecuteBatchTest.java and run tests in attached gradle project.
1. Expected behaviour:
No column is encrypted, so it does not matter, whether columnEncryptionSetting is enabled or not.
2. Actual behaviour:
Only test with connection string containing "columnEncryptionSetting=Enabled" fails.
3. Error message/stack trace:
`java.lang.AssertionError
	at com.microsoft.sqlserver.jdbc.TDSCommand.onRequestComplete(IOBuffer.java:7397)
	at com.microsoft.sqlserver.jdbc.TDSWriter.writePacket(IOBuffer.java:4071)
	at com.microsoft.sqlserver.jdbc.TDSWriter.endMessage(IOBuffer.java:3185)
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7556)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatementBatch(SQLServerPreparedStatement.java:2786)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtBatchExecCmd.doExecute(SQLServerPreparedStatement.java:2675)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2979)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2076)
	at ExecuteBatchTest.executeBatch(ExecuteBatchTest.java:65)
	at ExecuteBatchTest.test(ExecuteBatchTest.java:38)`
4. Any other details that can be helpful:
Second batch fails.

## JDBC trace logs
[mssql-jdbc-trace.txt](https://github.com/microsoft/mssql-jdbc/files/4419378/mssql-jdbc-trace.txt)

## Reproduction code
[mssql-batch-sample.zip](https://github.com/microsoft/mssql-jdbc/files/4419329/mssql-batch-sample.zip)

**Comment by shayannyc25** [comment] 2020-06-13 01:38
when will this fix be released?

**Comment by ulvii** [comment] 2020-06-15 20:52
#1334 is under view, we will try to include it for the next release, which is scheduled for July 31st.

**Comment by ulvii** [comment] 2020-06-16 00:39
Hi @jezbera ,
PR #1334  has binaries attached to it, would you give them a try and let us know if the issue is resolved for you?

**Comment by jezbera** [comment] 2020-06-18 17:04
> Hi @jezbera ,
> PR #1334 has binaries attached to it, would you give them a try and let us know if the issue is resolved for you?

All tests in sample are ok. Issue is resolved for me.

**Comment by peterbae** [comment] 2020-07-07 20:05
Fixed in #1378.

**Closed by peterbae** 2020-07-07 20:05 UTC
