### ISSUE TITLE
TLS 1.3 not working with application

### ISSUE THREAD

**Issue by 4devwithgit** [microsoft/mssql-jdbc#2157] opened 2023-06-30 13:19 UTC
## Driver version
mssql-jdbc-12.2.0.jre8.jar

## SQL Server version
SQL 2022

## Client Operating System
both the application and DB are running on Windows 2022.

## JAVA/JVM version
C:\Users\naher>java -version
java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) Client VM (build 25.333-b02, mixed mode)

## Table schema
--

## Problem description
My standalone java application is working fine with TLS 1.3 using the encrypt=strict option. However, my actually application is not working with the exact same DB, with matching settings of the stand alone java application.

## Expected behavior
Successful communication with Database with TLS 1.3

## Actual behavior
Application not working with SQL database with TLS 1.3.

[2023-06-30 02:54:43.802] ERROR [1688118883802] The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 1 (""): Data type 0x00 is unknown.
[2023-06-30 02:54:43.802] ERRORDTL [1688118883802]com.microsoft.sqlserver.jdbc.SQLServerException: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 1 (""): Data type 0x00 is unknown.

## Error message/stack trace
[2023-06-30 02:54:43.802] ERROR getSIVersion()
[2023-06-30 02:54:43.802] ERROR [1688118883802] The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 1 (""): Data type 0x00 is unknown.
[2023-06-30 02:54:43.802] ERRORDTL [1688118883802]com.microsoft.sqlserver.jdbc.SQLServerException: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 1 (""): Data type 0x00 is unknown.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1695)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:539)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7685)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4048)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:272)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:246)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:457)
	at com.sterlingcommerce.security.lc.LM.getSIVersion(LM.java:955)
	at com.sterlingcommerce.security.lc.LM.loadMap(LM.java:2582)
	at com.sterlingcommerce.security.lc.LM.loadOldSet(LM.java:3114)
	at com.sterlingcommerce.security.lc.LM.reload(LM.java:3380)
	at com.sterlingcommerce.security.lc.LM.refresh(LM.java:3319)
	at com.sterlingcommerce.security.lc.LM.<clinit>(LM.java:3454)
	at com.sterlingcommerce.security.lc.LicenseVerify.checkAndInstallLicense(LicenseVerify.java:57)
	at com.sterlingcommerce.security.lc.LicenseVerify.checkSfgLicense(LicenseVerify.java:28)
	at com.sterlingcommerce.security.lc.LicenseVerify.checkLicenses(LicenseVerify.java:17)
	at com.sterlingcommerce.woodstock.ops.server.PassPhrase.startup(PassPhrase.java:325)
	at com.sterlingcommerce.woodstock.ops.server.PassPhrase.main(PassPhrase.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.sterlingcommerce.woodstock.noapp.NoAppLoader.main(NoAppLoader.java:99)
[2023-06-30 02:54:43.802] ERROR 000000000000 GLOBAL_SCOPE getSIVersion()

## Any other details that can be helpful
Its puzzling why the standalone program is working but not working with application. The same works with TLSv1.2.

## JDBC trace logs
Not available.

**Comment by Jeffery-Wasty** [comment] 2023-06-30 16:03
Hi @4devwithgit,

What is the connection string you are using?

**Comment by 4devwithgit** [comment] 2023-06-30 17:14
This is the connection properties, which is not working with TLSv1.3,

mssqlPool.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
mssqlPool.url=jdbc:sqlserver://b2biqawinmk2.in.syncsort.dev:1433;databaseName=B2BTEST13;SelectMethod=cursor

**mssqlPool.trustStore=C:/B2BI/6200/MSSQLServer2022_TLS1.3_103.35/truststore.jks
mssqlPool.trustStorePassword=password
mssqlPool.encrypt=strict
mssqlPool.hostNameInCertificate=b2biqawinmk2.in.syncsort.dev
mssqlPool.trustServerCertificate=false
mssqlPool.sslProtocol=TLSv1.3**

mssqlPool.user=b2biuser
mssqlPool.password=password
#mssqlPool.maxconn=20
mssqlPool.storedProcClassName=com.sterlingcommerce.woodstock.util.frame.jdbc.SybaseStoredProcQuery
mssqlPool.varDataClassName=com.sterlingcommerce.woodstock.util.frame.jdbc.MSSQLVarData
mssqlPool.catalog=B2BTEST13
mssqlPool.type=remote
mssqlPool.transaction=true
mssqlPool.testOnReserve=true
mssqlPool.testOnReserveQuery=SELECT PRODUCT_LABEL from SI_VERSION where PRODUCT_LABEL = ?
mssqlPool.testOnReserveInterval=60000
mssqlPool.maxRetries=100
mssqlPool.blobPageSize=1024000
mssqlPool.compressBlob=true
mssqlPool.dbvendor=mssql
mssqlPool.buffersize=500
mssqlPool.maxsize=30
mssqlPool.initsize=1
mssqlPool.factory=com.sterlingcommerce.woodstock.util.frame.jdbc.ConnectionFactory
mssqlPool.behaviour=2
mssqlPool.lifespan=0
mssqlPool.idletimeout=86400000
mssqlPool.housekeepinginterval=3600000
mssqlPool.waittime=1000
mssqlPool.errorMissingTable=16945
mssqlPool.systemPool=true
useNewStateAndStatusLogic=true
useMSSQLConvert=

**Comment by Jeffery-Wasty** [comment] 2023-06-30 17:28
Okay and what is the statement? This - `Parameter 1 (""): Data type 0x00 is unknown` makes me think there is an issue there.

**Comment by 4devwithgit** [comment] 2023-06-30 17:43
The above parameters worked fine in simple java application. So, there are two possibilities, 
1) either application is not reading them properly, doing some additional stuff
2) Some additional settings are required on DB or application to make TLSv1.3 work inspite of working correctly in java program, and query were run from java program as well.

**Comment by Jeffery-Wasty** [comment] 2023-06-30 20:46
If TLS 1.3 is working fine in the "simple" Java application, then the issue is in whatever the difference is between the "simple" application and the "actual" application.

I was asking for information on the query because that's what the error points to, please look into what is being passed in at that point by your application.

Since you are able to use the driver correctly with TLS 1.3, this seems to me like an issue with either your application or the data being passed in. We'll keep this open for a bit, and please update us if you run into further issues or get more information from testing on your end.

**Comment by lilgreenbird** [comment] 2023-07-05 18:56
hi @4devwithgit 

Given that everything works fine in a standalone java application and only not in your "actual" app this points to the problem being in your "actual" app and not a driver issue so you will need to debug that at your end. We will be closing this please feel free to request reopening if you have more driver related questions.

**Closed by lilgreenbird** 2023-07-05 18:56 UTC
Labels: Question

**Comment by 4devwithgit** [comment] 2023-07-19 13:14
In my standalone program too if I use "SelectMethod=cursor" in the url as,
String url = "jdbc:sqlserver://b2biqawinmk2.in.syncsort.dev:1433;databaseName=B2BTEST13;SelectMethod=cursor";

I get below error in SQL query statement execution, which is similar,
Querying values from table
 
**Connection Failed! Check output console
com.microsoft.sqlserver.jdbc.SQLServerException: The incoming tabular data stream (TDS) protocol stream is incorrect. The stream ended unexpectedly.**
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1695)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteCursored(SQLServerStatement.java:2093)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:894)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:814)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7685)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4048)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:272)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:246)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQuery(SQLServerStatement.java:736)
	at SQLServer.main(SQLServer.java:120)

And without **SelectMethod**, it goes to completion without any errors. Not sure why this is coming into picture only when TLS version in use is TLSv1.3, which is using TDS 8.0 stream.

**Comment by 4devwithgit** [comment] 2023-07-19 13:32
I see the errors are not in getting the connection objects, but rather in the execution of the Prepared Statement. 
Below are two examples, where code is throwing errors with tls1.3 but not with tls 1.2

1)
            prep_stmt = conn.prepareStatement("select LIC_PROD_VER from SI_VERSION where UPPER(PRODUCT_LABEL) = ?");
            prep_stmt.setString(1, LICENSED_PRODUCT_LABEL.toUpperCase());
            **rs = prep_stmt.executeQuery();**

2)
	  connect();
      PreparedStatement stmt = conn.prepareStatement(sql);
      System.out.println("-------------------------------------------------");
      System.out.println("command: " + sql);
      System.out.println("-------------------------------------------------");
      **stmt.execute();**
      int count = stmt.getUpdateCount();

**Comment by nkmadala-qumu** [comment] 2024-08-22 06:44
I'm also seeing the same error. Were you able to resolve the issue?

**Comment by 4devwithgit** [comment] 2024-08-22 07:01
yeah, it required the correct driver, and also the correct SQL version. It was an issue with the SQL Server.

**Comment by nkmadala-qumu** [comment] 2024-08-22 08:59
I just figured out that I need to install the cumulative update to fix this bug. Thank you!
