### ISSUE TITLE
Changed behavior of PreparedStatement.execute() with the handling of warnings in 6.1.7

### ISSUE THREAD

**Issue by jubax** [Microsoft/mssql-jdbc#364] opened 2017-06-29 11:01 UTC
In 6.1.0 you could call `PreparedStatement.execute()` and retrieve warnings immediately after the statement was executed.

This code worked in 6.1.0 (and earlier):

```
try (PreparedStatement statement: connection.prepareStatement(...)) {
    statement.execute();
    SQLWarning warning = statement.getWarnings();
    assertNotNull(warning);
}
```

In 6.1.7 this code will not work. Instead we have to write:

```
try (PreparedStatement statement: connection.prepareStatement(...)) {
    statement.execute();
    SQLWarning warning = statement.getWarnings();
    assertNull(warning);
    while (statement.getMoreResults() || statement.getUpdateCount() != -1) {}
    warning = statement.getWarnings();
    assertNotNull(warning);
}
```

In order to reproduce you need a more complex example:
```

try (Connection connection = DriverManager.getConnection(jdbcUrl, user, password)) {
    try (PreparedStatement statement = connection.prepareStatement(""
            + "IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SRC')"
            + "BEGIN"
            + "  CREATE TABLE SRC (id BIGINT)"
            + "END")) {
        statement.execute();
    }
    try (PreparedStatement statement = connection.prepareStatement(""
            + "INSERT INTO SRC VALUES (33)")) {
        statement.execute();
    }
    try (PreparedStatement statement = connection.prepareStatement("" +
            "SELECT id INTO #MY_TMP FROM SRC\n" +
            "" +
            "IF EXISTS (SELECT * FROM #MY_TMP)\n" +
            "BEGIN\n" +
            "	RAISERROR(N'My Warning Message', 1, 1);\n" +
            "	RETURN;\n" +
            "END")) {
        statement.execute();

        // XXX: If this while loop is missing when 6.1.7 is used then then
        // statement.getWarnings().getMessage() throws a NPE because getWarnings() is null
        while (statement.getMoreResults() || statement.getUpdateCount() != -1) { }

        assertEquals("My Warning Message", statement.getWarnings().getMessage());
    }
}
```

In both 6.1.0 and 6.1.7 the first TDS token is 255 (TDS_DONE). The 6.1.0 parser continues to read. The next token is again 255 and the next is 171 (where the warning is read from the stream). The 6.1.7 parser does not continue after the first TDS_DONE.

The 6.1.0 SQLServerStatement.NextResult.onDone() always returns `true`, causing the parser to continue. The 6.1.7 onDone() callback has a more complex logic which returns `false` in this concrete example.

Not sure if this is a bug, but it is certainly a changed behavior which requires users to change their code.

**Comment by v-xiangs** [comment] 2017-06-29 18:50
Hello @jubax , Thank you for the report. After our investigation, we believe this is expected behaviour.
This behaviour change is due to PR #175 

Prior to 6.1.5, we did not support getting number of affected rows for `Select Into` query. Therefore, user was able to get SQL Server warnings without calling `getMoreResults()`, since warning was the first result.

After 6.1.5, we starts to support getting number of affected rows for `Select Into` query. Therefore, after calling `execute()`, the first result now is the number of affected rows. In the scenario you provided, user needs to call `getMoreResults()` to get the second result, which contains the warning.

We are sorry for the inconvenience, but this is expected behaviour.

**Comment by v-nisidh** [comment] 2017-06-29 19:16
Adding Ref of Javadocs. [PreparedStatement#execute()](http://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#execute--)

```
You must call either the method getResultSet or getUpdateCount to retrieve the result; 
you must call getMoreResults to move to any subsequent result(s).
```

**Comment by jubax** [comment] 2017-06-30 08:40
Sounds reasonable. Thanks for the quick answer.

May I ask how stable 6.1.7 is from your point of view? I mean, are you still developing (possibly breaking) features on this branch or are you currently stabilizing? I'm just wondering if I should stay with 6.1.0 or switch to 6.1.7.

Anyway, it's fine for me to close this issue (maybe a hint in the release/change notes or in the JavaDoc would be a good idea).

**Comment by v-nisidh** [comment] 2017-07-06 01:58
@jubax : Agreed to have hint in release / change logs. Keeping this issue open for documentation purpose. 

After validating / updating docs we can close this defect.

**Comment by v-xiangs** [comment] 2017-07-14 21:39
@jubax thank you for reporting the issue. We already have this in our 6.1.5 change log. I am closing this issue now since we all agreed to close this issue.

Thank you again for filing the issue.

**Closed by v-xiangs** 2017-07-14 21:39 UTC
Labels: docs
