### ISSUE TITLE
Cast exception when getting value of a sql_variant

### ISSUE THREAD

**Issue by zoladkow** [microsoft/mssql-jdbc#1302] opened 2020-04-02 19:03 UTC
## Driver version
- 7.4.1
- 8.2.1

## SQL Server version
12.0.2000.8

## Client Operating System
Win10

## JAVA/JVM version
Oracle's 1.8.0

## Table schema
INFORMATION_SCHEMA

## Problem description
1. Expected behaviour: `resultset.getLong(colName)` to return numeric value as long
2. Actual behaviour: `java.lang.ClassCastException`: `java.lang.Integer` cannot be cast to `java.lang.Long`
3. Error message/stack trace:
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getLong(SQLServerResultSet.java:2340)
```
4. Any other details that can be helpful:
 - Detected while investigating problem why `StoredProcedureQuery` parameters were not bound by name, but instead indexes. 
 - Currently Hibernate is using `select * from INFORMATION_SCHEMA.SEQUENCES` for obtaining sequence information - using `getLong(...)` for `start_value` etc. 
 - **BUT** since `start_value` is a `sql_variant` and if particular sequence is of `int` data type class cast exception is thrown, when reading that value and Hibernate falls back to using safe defaults instead of actual capabilities (including `supportsNamedParameters = false`)
 - Quick workaround in the project was to correct the datatype of two sequences. But clearly there is a problem in the driver with `sql_variant` support.
 - normally a `BIGINT` parameter is propagated down the call stack, but if the the actual column type is `sql_variant` another logic overrides the expected `BIGINT` type with the type detected from `sql_variant`. So an `Integer` is being returned up the stack where explicit casting is performed to `Long`. Which fails.
 - `sql_variant` reading logic should consider the data type provided by the caller to avoid class cast exception. Normally it is expected that a wider data type should contain the narrow data type implicitly.

## JDBC trace logs
[jdbcTrace.log](https://github.com/microsoft/mssql-jdbc/files/4423110/jdbcTrace.log)

## Reproduction code
```java
ResultSet rs = conn
                .prepareStatement("select cast(1 as sql_variant) as [sad_face]")
                .executeQuery();
if (rs.next()) {
     println ("Long value: " + rs.getLong("sad_face"));
}
```

**Comment by peterbae** [comment] 2020-04-02 21:45
Hi @zoladkow, thanks for reporting this issue. This definitely seems like it should work, and we will work on a fix on this issue soon.

**Comment by techy16** [comment] 2020-04-21 16:22
Hi @jvalkeal/peterbae  Any plans or tentative dates that you are going to fix this issue and release a updated version of jdbc jar for SQLServer?

**Comment by peterbae** [comment] 2020-04-21 17:12
Hi @techy16, we are targeting this fix to go into the next preview or the next RTW release, which happen at the end of May / end of July respectively,

**Comment by peterbae** [comment] 2020-04-27 18:03
Hi @zoladkow, @techy16. I've been looking into the issue a bit more, and I have a different perspective on this issue now. I think that the driver might be behaving correctly.

The reason why this case fails is because in this query below:

`select cast(1 as sql_variant) as [sad_face]`

We're inserting an int value into the sql_variant column. sql_variant columns internally track which type the data was inserted as, and when we retrieve the column, it returns the data to the driver as what was originally inserted. The problem here is that cast(1 as sql_variant) is inserting an int value into the column, and we're trying to select it as a Long. Even though at first glance it looks like it should work, unfortunately Java doesn't allow this conversion. Ideally, we should be doing one of the two scenarios below:

1) do `select cast(cast(1 as BIGINT) as sql_variant) as [sad_face]`
2) call rs.getInt() instead of rs.getLong()

I understand the point that @zoladkow has made, and I think it's unfortunate that the framework is querying the data incorrectly (perhaps this is a Java specific limitation). Even though I could easily make a change in the SQLServerResultSet.getLong() method to check for this exception and try to correctly convert it to int in this specific scenario, I think this is probably a hacky workaround to an incorrect use case scenario, and therefore I'm hesitating to make this change. Please let me know of what you think.

**Comment by techy16** [comment] 2020-04-27 18:35
Hi @peterbae what is the alternative you have if you think it is hacky workaround? 
I am not sure about the use case as i haven't gone deep into the code base. What are you suggesting as a solution to this issue?

**Comment by peterbae** [comment] 2020-04-27 18:38
The alternative to this hacky workaround is for the user (or the framework) to change their query to what I suggested above, or call rs.getInt() instead of calling rs.getLong() against a sql_variant column that contains an `int` value.

**Comment by techy16** [comment] 2020-04-27 18:52
Here User means that we should update this change in the code or the framework team should come up with this change and release an updated version?

**Comment by peterbae** [comment] 2020-04-27 19:02
Yes, you should update this change in the code. If that's not feasible, then you could contact the framework, but hopefully this problem is solvable just by modifying your code.

**Comment by techy16** [comment] 2020-04-27 19:29
we can make this change but the problem is that i dont see the docker files present in the code base. if you can provide the dockerfile so that i can push my docker images with lastest code changes. Ultimately i have to deploy SCDF to Kubernetes so i have to have the updated docker image with this fix. Also if you can specify the package path and class name where we have to make changes would be easy to quickly turnaround.

**Comment by peterbae** [comment] 2020-04-27 19:34
I'm not sure which docker files you mention. We're only responsible for the MSSQL JDBC driver part, and it's up to the user as to how they want to use our driver / setup their environment. Our driver doesn't have any dockerfiles on our GitHub repo.

**Comment by techy16** [comment] 2020-04-27 19:56
oh if this code change belongs to jdbc driver jar only then pls share the code base repo for the same, will create a new jar with the changes. i dont need dockerfile for jdbc driver but now i have to build the SCDF server code base again using the udpated JDBC jar so in order to do that i need to build the new jar for SCDF server and also build a new docker image as well to deploy to Kubernetes. If you do have idea on this specific piece to deploy to Kubernetes can you pls help who can help me on this to provide the dockerfile for SCDF server.

**Comment by zoladkow** [comment] 2020-04-27 23:47
@peterbae Hi Peter, I don't want to come across as impolite and disrespectful, but your response and proposed solutions got me very emotional. To put it simply - I think your new perspective is **COMPLETELY AND UTERLY WRONG**. 

Now having established that, let me get back to my original post, where I clearly mentioned that the issue occurred while reading sequence information from SQL standard `INFORMATION_SCHEMA.SEQUENCES`. SQL STANDARD. But you have focused all your perspective on just my plain simple example which is there only to illustrate what the driver does wrong.

Of course - have I decided to use `sql_variant` personally I would know it requires SqlServer specific handling... duh!

But how `INFORMATION_SCHEMA.SEQUENCES` is defined for specific RDBMSes I have no control of. To read it in standard way, over all of possible RDBMSes, I should not just go about detecting `sql_variant` -> then detecting which actual type is stored in each particular row -> then using the correct getter, now can I? Should I? And reading from `SEQUENCES` is not even me - it's **Hibernate**.

Now imagine what, the numerical values there, should be just that - NUMERICAL VALUES. If I was to use either `getLong()` or `getInt()` on INT or BIGINT, it is supposed to **just work** https://docs.microsoft.com/en-us/sql/connect/jdbc/understanding-data-type-conversions?view=sql-server-ver15
If `sql_variant` should not be covered by implicit conversion (the documentation actually states, that `sql_variant` should be treated as object) then why is there this big chunk of code trying to accomplish just that? According to the doc :

> There is no implicit conversion on assignment from the sql_variant data type, but there is implicit conversion to sql_variant.

Shouldn't the exception be different? Type mismatch detected early, by the driver, instead letting it pass until the a `ClassCastException` happens without much more detail?

Restating my point - the current `sql_variant` support in the driver is flawed. 

My suggestion are:
- **DON'T do any kind of implicit conversion** and throw informative exception about it (this would follow what's in the datatype conversion doc - which clearly indicates no conversion for this type)
- **Do EXACTLY same type of implicit conversion** which is already happening for standard datatypes & JDBC getters and do it right.

**Comment by peterbae** [comment] 2020-04-27 23:58
Hi @zoladkow, thanks for your response. I actually reached the same conclusion as you did after looking over the JDBC specs on my own, and I was working on a few details before I wanted to update this thread with that conclusion. I agree with your original point, and I'll make a PR soon that fixes this issue.

**Comment by zoladkow** [comment] 2020-04-27 23:59
> Even though I could easily make a change in the SQLServerResultSet.getLong() method to check for this exception and try to correctly convert it to int in this specific scenario, I think this is probably a hacky workaround to an incorrect use case scenario, and therefore I'm hesitating to make this change. Please let me know of what you think.

**ABSOLUTELY DON'T DO IT LIKE THAT!!** I cannot even begin to explain how wrong an approach that is on a CRITICAL piece of software like a DB driver that's supposed to work on production systems 😅 If such conversion is forbidden by database - conflict of actual and expected type should be detected early and a dedicated `SQLException` thrown. Just like SqlServer would report an invalid cast, the driver should do that too. Seeing the code which is done already, detecting this type mismatch is easy to code. 

My proposal instead is to follow general implicit conversion for all implicitly convertible types based on the actual data type stored in sql_variant. Just tie the pieces that are already there. And that would be perfect ;)

**Comment by zoladkow** [comment] 2020-04-28 00:03
@peterbae Ok, you've beat me with your last answer.


Thank you. Now I'm reassured this case well understood and will be addressed properly. With benefit of having JDBC portability maintained - the driver covering the SqlServer specifics as much as possible.

**Comment by peterbae** [comment] 2020-05-12 00:47
PR #1320 merged, closing issue.

**Closed by peterbae** 2020-05-12 00:47 UTC
