### ISSUE TITLE
Using cancelQueryTimeout and queryTimeout

### ISSUE THREAD

**Issue by saurabh29789** [microsoft/mssql-jdbc#1179] opened 2019-11-08 10:39 UTC
## Question
Driver Version: 7.4.1.jre8
SQL Server : SQL Azure (RTM) - 12.0.2000.8
Client OS: Ubuntu 18.04
Java Version : Openjdk8

I have the following code that is executed after the Server has dropped the connections from its end. 
```
      Statement s = connection.createStatement();
      s.setQueryTimeout(5);
      ((SQLServerStatement)s).setCancelQueryTimeout(5);
      s.execute("SELECT 1");
```
I observe the following logs when the above executes, hence confirming the timeouts were indeed set:

```
<record>
  <date>2019-11-08T10:31:13</date>
  <millis>1573209073472</millis>
  <sequence>4864</sequence>
  <logger>com.microsoft.sqlserver.jdbc.Statement</logger>
  <level>FINER</level>
  <class>com.microsoft.sqlserver.jdbc.SQLServerStatement:15</class>
  <method>getCancelQueryTimeout</method>
  <thread>78</thread>
  <message>ENTRY</message>
</record>
<record>
  <date>2019-11-08T10:31:13</date>
  <millis>1573209073472</millis>
  <sequence>4865</sequence>
  <logger>com.microsoft.sqlserver.jdbc.Statement</logger>
  <level>FINER</level>
  <class>com.microsoft.sqlserver.jdbc.SQLServerStatement:15</class>
  <method>getCancelQueryTimeout</method>
  <thread>78</thread>
  <message>RETURN 5</message>
</record>
<record>
  <date>2019-11-08T10:31:13</date>
  <millis>1573209073472</millis>
  <sequence>4866</sequence>
  <logger>com.microsoft.sqlserver.jdbc.Statement</logger>
  <level>FINER</level>
  <class>com.microsoft.sqlserver.jdbc.SQLServerStatement:15</class>
  <method>getQueryTimeout</method>
  <thread>78</thread>
  <message>ENTRY</message>
</record>
<record>
  <date>2019-11-08T10:31:13</date>
  <millis>1573209073472</millis>
  <sequence>4867</sequence>
  <logger>com.microsoft.sqlserver.jdbc.Statement</logger>
  <level>FINER</level>
  <class>com.microsoft.sqlserver.jdbc.SQLServerStatement:15</class>
  <method>getQueryTimeout</method>
  <thread>78</thread>
  <message>RETURN 5</message>
</record>
```

After a 5 second delay, the following is observed:

```
<record>
  <date>2019-11-08T10:31:18</date>
  <millis>1573209078477</millis>
  <sequence>4882</sequence>
  <logger>com.microsoft.sqlserver.jdbc.internals.TDS.Command</logger>
  <level>FINEST</level>
  <class>com.microsoft.sqlserver.jdbc.TDSCommand</class>
  <method>interrupt</method>
  <thread>355</thread>
  <message>TDSCommand@26dd3ba8 (SQLServerStatement:15 executeXXX): Raising interrupt for reason:The query has timed out.</message>
</record>


```

There are no logs where a timeout = 10 secs expires. Thus, even with these timeouts set, the connection hangs for a pretty long duration before an exception is observed with the following Stack Trace:

```
 com.microsoft.sqlserver.jdbc.SQLServerException: Connection timed out (Read failed)
 at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2924) ~[mssql-jdbc-7.4.1.jre8.jar:?]
 at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2031) ~[mssql-jdbc-7.4.1.jre8.jar:?]
 at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6418) ~[mssql-jdbc-7.4.1.jre8.jar:?]
 at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7579) ~[mssql-jdbc-7.4.1.jre8.jar:?]
 at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:866) ~[mssql-jdbc-7.4.1.jre8.jar:?]
 at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:768) ~[mssql-jdbc-7.4.1.jre8.jar:?]
 at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194) ~[mssql-jdbc-7.4.1.jre8.jar:?]
 at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2979) ~[mssql-jdbc-7.4.1.jre8.jar:?]
 at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248) ~[mssql-jdbc-7.4.1.jre8.jar:?]
 at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223) ~[mssql-jdbc-7.4.1.jre8.jar:?]
 at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:744) ~[mssql-jdbc-7.4.1.jre8.jar:?]
 Caused by: java.net.SocketException: Connection timed out (Read failed)
 at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_222]
 at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_222]
 at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_222]
 at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_222]
 at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1003) ~[mssql-jdbc-7.4.1.jre8.jar:?]
 at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:993) ~[mssql-jdbc-7.4.1.jre8.jar:?]
 at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[?:1.8.0_222]
 at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[?:1.8.0_222]
 at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975) ~[?:1.8.0_222]
 at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933) ~[?:1.8.0_222]
 at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[?:1.8.0_222]
 at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2023) ~[mssql-jdbc-7.4.1.jre8.jar:?]
 ... 44 more

```
According to issue 525, the cancelQueryTimeout has solved the same problem. Not sure why I'm still observing the same issue.

## Relevant Issues and Pull Requests
https://github.com/Microsoft/mssql-jdbc/issues/525
https://github.com/microsoft/mssql-jdbc/pull/560
https://github.com/microsoft/mssql-jdbc/pull/674

**Comment by peterbae** [comment] 2019-11-08 18:04
Hi @saurabh29789, thanks for letting us know. The team will look into this issue and get back to you.

**Comment by ulvii** [comment] 2019-11-12 20:04
Hi @saurabh29789,

Are you seeing this behavior intermittently? Would you also try 7.0 version of the driver? We made changes to query timer in 7.2, I wonder if it is related.

**Comment by saurabh29789** [comment] 2019-11-13 11:05
I'm seeing this everytime I issue the SELECT after connection has been invalidated from the server. Seeing the same for both 7.0.0 and 7.4.1 although the logs are different in each case.
In both the cases, the thread issuing the SELECT is stuck with the same stack trace as per the Opening Post.

With v7.4.1, the following is observed:

1. The MS Sql logs show an interrupt raised after 5 secs     
2. Thread status:
```
   Thd name mssql-jdbc-shared-timer-core-0
   a. in WAIT state before SELECT query
   b. in TIMED_WAITING state after SELECT query
   c. in WAIT state after 10 sec
```
3. Connection timeout after about 16 min
<hr>

With v7.0.0, the following is observed:

1. I see two threads being created here
```
    Thd Id 351   name mssql-jdbc-TimeoutTimer-2
    Thd Id 351   name mssql-jdbc-TimeoutTimer-3
```
2. As per MS Sql Logs,
       a. After 5 sec : Thd id 351                                                  
```
<record>
  <date>2019-11-13T09:08:11</date>
  <millis>1573636091582</millis>
  <sequence>4210</sequence>
  <logger>com.microsoft.sqlserver.jdbc.internals.TDS.Command</logger>
  <level>FINEST</level>
  <class>com.microsoft.sqlserver.jdbc.TDSCommand</class>
  <method>interrupt</method>
  <thread>351</thread>
  <message>TDSCommand@39f88a90 (SQLServerStatement:13 executeXXX): Raising interrupt for reason:The query has timed out.</message>
</record>
```
   b. After 10 sec: Thd id 352                                                  
```
<record>
  <date>2019-11-13T09:08:16</date>
  <millis>1573636096584</millis>
  <sequence>4217</sequence>
  <logger>com.microsoft.sqlserver.jdbc.internals.SQLServerException</logger>
  <level>FINE</level>
  <class>com.microsoft.sqlserver.jdbc.SQLServerException</class>
  <method>logException</method>
  <thread>352</thread>
  <message>*** SQLException:ConnectionID:1 ClientConnectionId: ac11c44f-1ba8-42b9-bde2-e2ebba2fb14c com.microsoft.sqlserver.jdbc.SQLServerException: The connection is closed. The connection is closed.</mes
sage>
</record>
<record>
  <date>2019-11-13T09:08:16</date>
  <millis>1573636096585</millis>
  <sequence>4218</sequence>
  <logger>com.microsoft.sqlserver.jdbc.internals.SQLServerException</logger>
  <level>FINE</level>
  <class>com.microsoft.sqlserver.jdbc.SQLServerException</class>
  <method>logException</method>
  <thread>352</thread>
  <message>com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2826)com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2815)com.microsoft.sq
lserver.jdbc.TimeoutTimer.run(IOBuffer.java:7054)java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)java.util.concurrent.FutureTask.run(FutureTask.java:266)java.util.concurrent.ThreadPo
olExecutor.runWorker(ThreadPoolExecutor.java:1149)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)java.lang.Thread.run(Thread.java:748)</message>
</record>

```                              
3. Thread status:                                                               
   a. Thd name: mssql-jdbc-TimeoutTimer-2   ;  Thd Id : 351                                                              
```
      i) TIMED_WAITING (sleeping) after SELECT -- does not exist before         
      ii) TIMED_WAITING (parking) after 5 sec                                   
      iii) Goes away after a while but before 352 (atleast 2 min prior)
```
   b. Thd name: mssql-jdbc-TimeoutTimer-3   ; Thd Id : 352                                                              
```
      i) TIMED_WAITING (sleeping) after SELECT -- does not exist before         
      ii) TIMED_WAITING (sleeping) after 5 sec                                  
      iii) Blocked (on object monitor) after 10 sec at                          
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:966)    
        - waiting to lock <0x00000002b76c7958> (a java.lang.Object)             
        at sun.security.ssl.SSLSocketImpl.waitForClose(SSLSocketImpl.java:1761) 
        at sun.security.ssl.SSLSocketImpl.closeSocket(SSLSocketImpl.java:1571)  
        at sun.security.ssl.SSLSocketImpl.closeInternal(SSLSocketImpl.java:1705)
        at sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:1594)        
        at com.microsoft.sqlserver.jdbc.TDSChannel.disableSSL(IOBuffer.java:718)
                                                                                
      iv) Still Blocked when (351) had gone away                                
      v) Goes away after about 16 min at Socket Timeout                         

```
   c. Primary Thread that executed the SELECT statement
```

        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:999)
        at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:989)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        - locked <0x00000002b76c7958> (a java.lang.Object)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        - locked <0x00000002b76c8da0> (a sun.security.ssl.AppInputStream)
        at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:1971)

```
It appears that atleast for v.7.0.0 the Timer Thread is awaiting to fetch a lock (0x00000002b76c7958) already taken up by the execute() thread.

**Comment by ulvii** [comment] 2019-11-14 01:32
Hi @saurabh29789,
I am having a trouble with reproducing the issue. How are you dropping connections from server side?
Also, is using `socketTimeout` an option for you?

**Comment by saurabh29789** [comment] 2019-11-15 06:37
@ulvii 
I tried the same test on a different machine. There I don't see any connectivity Issues. The primary machine shows the issue consistently, though. I'm trying to figure out why it is behaving so. The only thing I'm sure of is that this behaviour shows up only if there is a delay ( roughly 10 min ) between two queries !! Is there something specific I can look for that might help in root-causing this ? 

> How are you dropping connections from server side?

I'm not really dropping it myself. My assumption was that the SQL Server might be having a low value of the wait_timeout param equivalent of MySql Server, and that the Server might be dropping them off. Now, I'm not very sure of this as the behaviour is not universal anymore.

> Also, is using socketTimeout an option for you?
Too low a value would not be preferred. I have some workarounds but without a proper root-cause those are not reliable.

**Comment by ulvii** [comment] 2019-11-19 02:42
Hi @saurabh29789,

> The only thing I'm sure of is that this behaviour shows up only if there is a delay ( roughly 10 min ) between two queries !! Is there something specific I can look for that might help in root-causing this ?

I am not aware of any driver issues that might cause this behavior. Based on the logs, looks like socket.close() hangs. I can investigate if you provide reproductions instructions.

**Comment by saurabh29789** [comment] 2019-11-20 05:28
@ulvii 

> Hi @saurabh29789,
> 
> > The only thing I'm sure of is that this behaviour shows up only if there is a delay ( roughly 10 min ) between two queries !! Is there something specific I can look for that might help in root-causing this ?
> 
> I am not aware of any driver issues that might cause this behavior. Based on the logs, looks like socket.close() hangs. I can investigate if you provide reproductions instructions.

The following steps are all what I am using to reproduce the issue.

```
Connection conn = DriverManager.getConnection(uri);
conn.setAutoCommit(false);

String sql = "INSERT INTO " + tbl + "VALUES (" + val + ")";
Statement s = conn.createStatement();
s.executeUpdate(sql);
conn.commit();

//  10 minute sleep here

Statement s2 = connection.createStatement();
s2.setQueryTimeout(5);
((SQLServerStatement)s2).setCancelQueryTimeout(5);
s2.execute("SELECT 1");  // Hangs here
```

Couple of things to note:
1. The **netstat -atn**  for this socket has a non-zero Send-Q value when it hangs. I am trying to root-cause this instead. 
2. Not all machines hang; others hang everytime. So, I am considering if there could be some machine or machine-config issue playing some role here. The OS is the same on both.

**Comment by ulvii** [comment] 2020-06-15 21:02
Hi @saurabh29789 ,
Were you able to find the root cause for the issue?

**Comment by ulvii** [comment] 2020-06-30 19:40
Closing the issue. Please feel free to contact us if you have any other questions.

**Closed by ulvii** 2020-06-30 19:40 UTC
Labels: question
