### ISSUE TITLE
SQLServerCallableStatement issue with BigDecimal scale/precision

### ISSUE THREAD

**Issue by rabbit-mom** [Microsoft/mssql-jdbc#235] opened 2017-04-05 10:23 UTC
Hi,when I using  SQLServerCallableStatement.execute(),it will be prompted to "The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Table-valued parameter 20 (""), row 0, column 0: Data type 0x6C has an invalid precision or scale.",I think  it is caused by BigDecimal  with precision =18 and scale=8,hope can get help,looking forward to reply.

**Comment by v-afrafi** [comment] 2017-04-05 16:58
Hi @rabbit-mom. Can you provide any example code that could help us with fixing the issue?

**Comment by v-afrafi** [comment] 2017-04-17 22:04
@rabbit-mom since we did not hear back from you, will close this issue. Please feel free to reopen it once you have more details on this. Thank you!

**Comment by rabbit-mom** [comment] 2017-04-20 10:59
![image](https://cloud.githubusercontent.com/assets/25653454/25227422/02c792d0-25fb-11e7-8913-a4e1cde53e2d.png)
Hi~I encountered this problem again , it throws exception with the message "The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Table-valued parameter 7 (""), row 0, column 0: Data type 0x6C has an invalid precision or scale".My application scenario is As shown in the above picture.I use the "6.1.4.jre7-preview" version. I am desperately want to get your reply.Thanks!

**Comment by rabbit-mom** [comment] 2017-04-20 11:03
I met a problem When I was using this framework(mssql-jdbc,version:6.1.4.jre7-preview),I'm a bit worried because I need online my  products,So Ask for your help.
Thanks very much!






在 2017-04-18 06:04:02，"Afsaneh Rafighi" <notifications@github.com> 写道：


Closed #235.

**Comment by rabbit-mom** [comment] 2017-04-20 11:06
I met a problem When I was using this framework(mssql-jdbc,version:6.1.4.jre7-preview),I'm a bit worried because I need online my  products,So Ask for your help.
And I have asked questions on Github.The link is  https://github.com/Microsoft/mssql-jdbc/issues/235 .
Thanks very much!








在 2017-04-18 06:04:02，"Afsaneh Rafighi" <notifications@github.com> 写道：


Closed #235.

**Comment by rabbit-mom** [comment] 2017-04-20 12:35
![image](https://cloud.githubusercontent.com/assets/25653454/25230973/a3d4323e-2608-11e7-8595-8843e2156a36.png)
The error field  is in the red box.

**Comment by v-suhame** [comment] 2017-04-20 16:18
@rabbit-mom can you share the input that is causing this exception? what is the table or store-procedure schema you are accessing? It will be helpful if you can share the code to reproduce it.

**Comment by v-nisidh** [comment] 2017-05-10 18:38
@rabbit-mom : Is this problem is reproducible? Can you share appropriate data/query/storeproc which can reproduce this problem. 

Appreciate if you able to share data which can reproduce this problem. Give a try with our latest release 6.1.7-preview & let us know if you have similar problem or not.

**Comment by v-afrafi** [comment] 2017-07-18 20:49
Closing this issue since we did not hear back. @rabbit-mom feel free to open this once you have any updates. Thanks!

**Closed by v-afrafi** 2017-07-18 20:49 UTC
Labels: in progress, Waiting for response
