### ISSUE TITLE
[QUESTION] Decimal values scale on bulk insert

### ISSUE THREAD

**Issue by RazmikMkrtchyan** [microsoft/mssql-jdbc#1021] opened 2019-04-04 10:04 UTC
## Relevant Issues and Pull Requests

During bulk insert decimal values get rounding.
I did the profile and  got the following query:

  **exec sp_executesql N'insert into DE_PartnerPayment 
(PaymentDescription, PartnerPaymentID, PartnerID, Amount, PlannedPaymentDate, PlannedFinancialReportDate)
values (P0, P1, P2, P3, P4, P5), (P6, P7, P8, P9, P10, P11)',
N'@P0 nvarchar(4000),P1 int,@P2 int,P3 **decimal(38,1)**,P4 datetime2,P5 datetime2,P6 nvarchar(4000),P7 int,P8 int,P9 **decimal(38,4)**,P10 datetime2,P11 datetime2',
N'aaaa',1060,744,**13.1**,'2019-04-02 09:28:55','2019-04-02 09:28:55',N'aaaa',1061,744,**13.9999**,'2019-04-02 09:28:55','2019-04-02 09:28:55'**

For each bigDecimal  value its scale is puts In the query, but ms-sql  does not understand and takes only the type of the first one.

In Parameter.java works following code
                **void execute(DTV dtv, BigDecimal bigDecimalValue) throws SQLServerException {
                         if (null != bigDecimalValue) {
                        scale = bigDecimalValue.scale();
                        if (scale < 0)
                          scale = 0;
                       }
                  setTypeDefinition(dtv);
                 }**

Wouldn't it be right to define the scale with column type?

**Comment by cheenamalhotra** [comment] 2019-04-04 20:55
Hi @RazmikMkrtchyan 

> For each bigDecimal value its scale is puts In the query, but ms-sql does not understand and takes only the type of the first one.

Could you elaborate with an example of what exactly went wrong? I tried with multiple decimal columns in a table, and passed different values (with different Scales) tried Bulk Insert and normal Insert both. SQL Server rightly interprets passed values in parameters and stores them correctly.

**Comment by RazmikMkrtchyan** [comment] 2019-04-05 07:30
Hi @cheenamalhotra ,thank you for response.
I meant the same column.

The query of prepared statement made from the profile has the following form 

```create table TEST_TABLE(DEC_COLUMN DECIMAL(26,4))

     exec sp_executesql N'INSERT INTO TEST_TABLE (DEC_COLUMN) 
                                      VALUES (@P0), (@P1)',N'
                                     @P0 decimal(38,1),@P1 decimal(38,4)',13.1,13.9999
```

After executing  this query ,the result is following 
         
<img width="1268" alt="Screen Shot 2019-04-05 at 11 28 48 AM" src="https://user-images.githubusercontent.com/11534590/55611253-08735d80-5796-11e9-90cf-f0e382da7d0e.png">

            
Ms takes only the type of the first one, and the second row converted as that type.

**Comment by RazmikMkrtchyan** [comment] 2019-04-08 19:32
@cheenamalhotra  any news?

**Comment by cheenamalhotra** [comment] 2019-04-08 19:59
Hi @RazmikMkrtchyan 

I was able to reproduce the problem and I think the source of problem is from SQL Server end, and however we provide support for setting scale, does not make any change in the way data is sent to SQL Server.

According to me, and as you mentioned above, we can see in the query, `@P0 decimal(38,1),@P1 decimal(38,4)` is sent correctly from the driver based on `BigDecimal` values set on `PreparedStatement` and that does define different scales for both values but SQL Server fails to understand the difference and uses the first one.

Let me know if I'm missing something and if you have a solution to solve this issue by modifying driver?

**Comment by RazmikMkrtchyan** [comment] 2019-04-09 07:16
Hi @cheenamalhotra ,
Yes I think that the problem is from  SQL Server. 

But if query was generated with  table column type, the query would work properly.

**Comment by RazmikMkrtchyan** [comment] 2019-04-15 08:02
Hi @cheenamalhotra , I am waiting for your response :) .

**Comment by cheenamalhotra** [comment] 2019-04-15 18:11
Hi @RazmikMkrtchyan 

I understand the solution and it does make sense in this scenario if we somehow figure out the metadata of the underlying column. However, as of now, it's not feasible to capture metadata of column in all situations (e.g. when AE is enabled on underlying column - #493). We're working on #927 to provision use of SET FMTONLY ON/OFF to capture table and parameter metadata, which once supported can be called before execution and table column type can be passed with parameters.

So, we have to wait till #927 is resolved after which we can attempt solution for this problem.

**Comment by RazmikMkrtchyan** [comment] 2019-04-16 12:37
Hi @cheenamalhotra 
Thank you very much!

**Comment by sudhiriyer** [comment] 2021-09-08 05:42
I encountered this issue when doing a CDC between Oracle (source) and Azure SQL ( sink). The latest update I have had from Microsoft Azure SQL DB team is "..This issue with decimals is not new but is a relatively high priority on our radar to fix, as of now there is no clear ETA but we expect that to be fixed during the next deployment quarter..", and I have been direct to this link to keep myself updated.

**Comment by Jeffery-Wasty** [comment] 2023-11-21 17:48
I believe this issue is due to how we parse BigDecimal input, or rather, don't parse them. 12.5.0 introduces a connection string option `calcBigDecimalScale` that, when set to true, will compute a BigDecimal's scale accurately as opposed to passing in maximum (38) regardless of input. This setting has performance issues, which is why its a connection string option, and not default behavior. If you're able to, we recommend trying out the newest preview release to see if this resolves the issue you're experiencing.

**Comment by Jeffery-Wasty** [comment] 2023-11-27 21:01
Closing due to lack of reply, see 12.5.0 and later releases for solution to issue.

**Closed by Jeffery-Wasty** 2023-11-27 21:01 UTC
Labels: Enhancement, Question
