### ISSUE TITLE
DATETIMEOFFSET loses 60 minutes

### ISSUE THREAD

**Issue by palatam** [microsoft/mssql-jdbc#1769] opened 2022-03-15 15:39 UTC
## Driver version
10.2.0.jre17

## SQL Server version
mcr.microsoft.com/azure-sql-edge:latest

## Client Operating System
Docker/openjdk17

## JAVA/JVM version
17.0.2+8

## Table schema
```
CREATE TABLE demo
(
    timestamp1 DATETIMEOFFSET
);
```

```
@Column(columnDefinition = "DATETIMEOFFSET")
private OffsetDateTime timestamp1;
```

## Problem description
data type conversion between SQL Server Type "DATETIMEOFFSET" and Java Type "OffsetDateTime" looses a full hour.
## Expected behavior
correct conversion
## Actual behavior
incorrect conversion, loosing 60 minutes

running same IT once with DATETIME2 and once with DATETIMEOFFSET:

```
OffsetDateTime expected = ... from INSERT with ZoneOffset.MAX ...
OffsetDateTime actual = ... from SELECT of previous INSERT ...

System.out.println(expected);
System.out.println(actual);
long diff = expected.until(actual, ChronoUnit.MINUTES);
System.out.println("Diff: " + diff + " minutes");
```

Using DATETIME2 without columnDefinition:

```
2022-03-15T16:29:17.846914+18:00
2022-03-14T23:29:17.846914+01:00
Diff: 0 minutes
```

Using DATETIMEOFFSET and columnDefinition="DATETIMEOFFSET"

```
2022-03-15T16:33:55523522+18:00
2022-03-15T00:33:55523522+01:00
Diff: 60 minutes
```

**Comment by v-zhangw** [comment] 2022-03-15 17:38
Hi @palatam,
Thanks for bringing this to our attention, we will take a look soon.

**Comment by palatam** [comment] 2022-03-18 13:56
FYI my offset is UTC+01:00 so maybe this is why the 1 hour is lost?

**Comment by palatam4ubs** [comment] 2022-03-21 16:11
@v-zhangw as soon as I find some time, I need to extract the problematic components out of our current code base, give me some time

**Comment by v-zhangw** [comment] 2022-04-05 20:49
HI @palatam,
Thanks and we will take a look soon. There has been a lot of support issues lately which have caused delays.

**Comment by palatam** [comment] 2022-05-04 15:24
I am using JDK 17 (Temurin) and doing `mvn clean verify` I get:

```
[...]
2022-05-04 17:17:55.500  INFO 4842 --- [           main] org.example.ExampleIT                    : Started ExampleIT in 1.932 seconds (JVM running for 10.499)
Hibernate: select next value for hibernate_sequence
Hibernate: insert into date_time2entity (value, id) values (?, ?)
Hibernate: select datetime2e0_.id as id1_0_0_, datetime2e0_.value as value2_0_0_ from date_time2entity datetime2e0_ where datetime2e0_.id=?
2022-01-31T12:12:34.000056789+18:00
2022-01-30T19:12:34.000056800+01:00
Diff: 0 minutes
Hibernate: select next value for hibernate_sequence
Hibernate: insert into date_time_offset_entity (value, id) values (?, ?)
Hibernate: select datetimeof0_.id as id1_1_0_, datetimeof0_.value as value2_1_0_ from date_time_offset_entity datetimeof0_ where datetimeof0_.id=?
2022-01-31T12:12:34.000056789+18:00
2022-01-30T20:12:34.000056800+01:00
Diff: 60 minutes
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.467 s <<< FAILURE! - in org.example.ExampleIT
[ERROR] org.example.ExampleIT.testDateTimeOffset  Time elapsed: 0.043 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <0> but was: <60>
	at org.example.ExampleIT.assertEquals(ExampleIT.java:80)
	at org.example.ExampleIT.testDateTimeOffset(ExampleIT.java:72)
```

so uhm ...

**Comment by v-zhangw** [comment] 2022-05-10 17:51
It sounds like these errors are just not happening for you...

Is it possible to boil down this repro to just a short pure java application?

**Comment by Sheldor5** [comment] 2022-05-10 18:08
I cloned the repo on both Windows 10 and MacOS (private and company PC) and i worked perfectly fine ...

**Comment by v-zhangw** [comment] 2022-05-19 23:45
That's strange. It appears that the DateTime2Entity class simply doesn't have some of these functions (like setValue) which are being called of it?

Regardless I will try again on a clean machine in case there's an issue with mine.

**Comment by palatam** [comment] 2022-05-20 06:56
Hi @v-zhangw , the project is using lombok so maybe there is an issue with lombok and your JDK, try removing lombok from maven and implement the getters/setters/constructors on your own.

**Comment by v-zhangw** [comment] 2022-06-14 20:43
Hello,
It has been a while, apologies for the lack of response. We have been quite busy and have not had time to investigate this issue yet. It will likely be a couple of weeks until this reaches the top of the priority queue.

**Comment by Jeffery-Wasty** [comment] 2022-08-11 08:35
Hello @palatam,

An update from us. We're currently revisiting this issue to see if we can provide a resolution this time around. I'll be continuing where v-zhangw left off and try to reproduce this on our end. If you're able to provide any additional information since your last update that would be great.

**Comment by Jeffery-Wasty** [comment] 2023-09-18 16:49
Hi @palatam,

After looking into this issue further, this is intended behavior. `datetimeoffset` is relative to UTC, and so a straight conversion will see the loss/gain in time you're seeing. In your example, you convert an `OffsetDateTime` to some `DateTimeOffset` entity. The timezone will need to be passed in somehow as well, I'm not familiar enough with Spring to say how. Conversion between `DateTimeOffset` and other datetime objects will also need the timezone, as can be seen in this previous issue here: https://github.com/microsoft/mssql-jdbc/issues/758.

Please let us know if this resolves the issue for you. We'll be closing this issue in a few weeks without any further reply.

**Comment by Sheldor5** [comment] 2023-09-18 18:50
Are you talking about `DateTimeOffsetEntity` in my example code? Because this is just a JPA Entity class, a wrapper for the database table and has nothing to do with this issue.

But then I think this IS a bug in your JDBC Implementation:

If the value stored in the DB is relative to UTC does this mean you simply remove the timezone/offset without converting the `OffsetDateTime` to UTC first? Because I think this is what is happening.

**Comment by Jeffery-Wasty** [comment] 2023-09-19 21:18
On initial examination, this appeared to be intended behavior when looking at the conversions being done in driver, past issues, and user discussion on here and other forums regarding `datetimeoffset`, but I'm taking another look. One thing I want to make sure of is how this discrepancy is being found. The original users code snippets were truncated, and the provided code samples from the additional repository makes use of Spring in ways I'm not familiar with. 

The flow is, I believe, as follows:
* Create an `OffsetDateTime` value with some time zone other than UTC
* Insert into a table with column type `datetimeoffset`
* Retrieve the value, convert back to `OffsetDateTime`
* Compare to original and see the time zone information wasn't translated across correctly. 

Please let me know if this isn't the case, as when I do the above, I'm instead seeing the value being stored and retrieved correctly. A java only repro would be preferred, but at minimum I need to know how the value is being retrieved from the result set.

**Comment by Sheldor5** [comment] 2023-09-19 22:21
The flow is correct, points 2 and 3 are handled by your JDBC driver.

> * Create an `OffsetDateTime` value with some time zone other than UTC

`OffsetDateTime.now()` will always create a value with non-UTC offset if your system time zone is not set to UTC/GMT but Java Applications by default will always use the system time zone.

Looking into https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetimeoffset-transact-sql?view=sql-server-ver16 I don't find any information that the stored/inserted value must be in UTC, actually it states that it preserves timeoffset information.

In my example code I create a simple `OffsetDateTime` at a non-UTC offset, store it in the database, retrieve the value again and compare them which results in different values, only Hibernate is between my code and your JDBC driver, so either Hibernate is doing some conversion (don't believe so because it only uses your JDBC driver under the hood) or your JDBC driver is doing wrong conversions on INSERT or SELECT ...

The exact same logic is working fine if I use the `DATETIME2` column type.

> but at minimum I need to know how the value is being retrieved from the result set

It is retrieved by your JDBC driver ... but looking at your JDBC driver's conersion table at https://learn.microsoft.com/en-us/sql/connect/jdbc/using-basic-data-types?view=sql-server-ver16#data-type-mappings I don't see an entry for `java.time.OffsetDateTime` so maybe this mapping between Java Type and Database Type is not fully supported?

**Comment by David-Engel** [comment] 2023-09-19 23:24
I'm not seeing incorrect data. Seems to me like there is probably a conversion error happening somewhere **_outside_** of the driver in your scenario. It helps troubleshooting to eliminate frameworks.

My JDBC-only code snippet:

```
        OffsetDateTime odt = OffsetDateTime.now();

        try (Connection conn = DriverManager.getConnection(conStr)) {
            try (Statement s = conn.createStatement()) {
                s.execute("drop table if exists foo12345; create table foo12345 (dto_col1 datetimeoffset)");
            }
            try (PreparedStatement ps = conn.prepareStatement("insert into foo12345 (dto_col1) values (?)")) {
            	ps.setObject(1, odt);
            	ps.execute();
            	System.out.println("Value inserted: " + odt.toString());
            }
            try (Statement s = conn.createStatement()) {
                ResultSet rs = s.executeQuery("select dto_col1 from foo12345");
                while (rs.next()) {
                    System.out.println("Value returned: " + rs.getObject(1).toString());
                }
            }
            try (Statement s = conn.createStatement()) {
                s.execute("drop table if exists foo12345");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
```

Output:

```
Value inserted: 2023-09-19T16:16:53.538260400-07:00
Value returned: 2023-09-19 16:16:53.5382604 -07:00
```

**Comment by Sheldor5** [comment] 2023-09-20 00:12
It indeed looks like Hibernate is doing the conversion from java.time.OffsetDateTime (unknown by JDBC API) to String (which is known by JDBC API) wrong, I was curious and found the same issue including the fix on SO: https://stackoverflow.com/q/35808423

Can be closed, sorry for any inconveniences.

**Closed** 2023-09-20 16:38 UTC
