### ISSUE TITLE
add support for native Active Directory (AD) domain authentication

### ISSUE THREAD

**Issue by bboles** [Microsoft/mssql-jdbc#730] opened 2018-06-26 23:16 UTC
## Driver version or jar name
6.4

## SQL Server version
Any supported SQL version

## Client operating system
Any Linux OS.

## Java/JVM version
Any supported java/jvm.

## Table schema
N/A

## Problem description
Currently there is no native support for Active Directory domain logins.  There is kerberos authentication support, but this requires changes to be made to the SQL servers in order to make it work.  In some environments, this is not an easy change to make.  Lack of integrated AD support for the official MSSQL driver is a bit surprising since there are [other](http://www.freetds.org/userguide/domains.htm) [drivers](http://jtds.sourceforge.net/features.html) that do have native AD auth support built-in.

## Expected behavior and actual behavior
N/A

## Repro code
N/A

**Comment by David-Engel** [comment] 2018-07-03 21:49
@bboles
Kerberos authentication **IS** Active Directory authentication. What you are referring to is legacy [NTLM authentication](https://docs.microsoft.com/en-us/windows-server/security/kerberos/ntlm-overview). Those [other](http://www.freetds.org/userguide/domains.htm) [drivers ](http://jtds.sourceforge.net/features.html) are quite old and implemented NTLM because that was the primary method for authenticating on Windows back then. NTLM is **much** less secure than Kerberos. 

That said, we do understand that customers still desire the functionality that NTLM authentication offered (Windows/Domain username and password authentication) and it is on our roadmap to add that to the JDBC driver (with any security caveats documented).
Regards,
David

**Comment by bboles** [comment] 2018-07-03 21:59
Thanks for your response @David-Engel !

> it is on our roadmap to add that to the JDBC driver

Any idea on when this will happen?

**Comment by David-Engel** [comment] 2018-07-03 23:54
@bboles I can't promise anything. But I'm hoping we will be able to investigate and add it to the driver over the next 6 months.

**Comment by gordthompson** [comment] 2018-07-15 13:29
(Duplicate of #696.)

**Comment by cheenamalhotra** [comment] 2018-08-31 23:54
Closing this as Duplicate of #696

**Closed by cheenamalhotra** 2018-08-31 23:54 UTC
