### ISSUE TITLE
"GetColumns "call returning only one column for Azure sql datawarehouse

### ISSUE THREAD

**Issue by souravjha77** [microsoft/mssql-jdbc#1206] opened 2019-12-09 12:09 UTC
## Driver version
7.4.1.jre8

## SQL Server version
Azure sql datawarehouse

## Client Operating System
Linux

## JAVA/JVM version
OpenJdk 1.8.0_222

## Problem description
On using "GetColumns" method with all null value arguments, it returns only one column.
1. Expected behaviour: It should return all the columns
2. Actual behaviour: Returning only one column.
3. Error message/stack trace: NA
4. Any other details that can be helpful: NA

**Comment by rene-ye** [comment] 2019-12-09 16:40
Duplicate of issue #1192; already resolved in dev.

**Closed by rene-ye** 2019-12-09 16:40 UTC

**Comment by souravjha77** [comment] 2019-12-09 19:47
what's the expected date for release in maven repo for 8.1.1

**Comment by ulvii** [comment] 2019-12-11 20:38
8.1.1-preview is released both on Maven and GitHub.
