### ISSUE TITLE
MS-SQL driver closes prepared statements on endRequest but Ironjacamar cache still produces them

### ISSUE THREAD

**Issue by vtuonone** [microsoft/mssql-jdbc#1703] opened 2021-12-04 08:18 UTC
## Driver version
At least 7.4.1, 8.4.1, 9.2.1,  9.5-Preview

## SQL Server version
Any

## Client Operating System
Any

## JAVA/JVM version
JVM 11

## Table schema
Any

## Problem description
Discovered in WIldFly 24.0.1 (ironjacamar 1.4.35) with ms-sql JDBC drivers jre11 variants of versions 7.4.1, 8.4.1, 9.2.1, 9.5-Preview

Application code calls prepareStatement() then immediately executeQuery and gets error
com.microsoft.sqlserver.jdbc.SQLServerException: The statement is closed.

What I think is going on is that the application has got a connection, used it as above, closed it, then later got the same connection again from the pool to use as above. When the application closes the connection Ironjacamar calls endRequest() on the connection which calls com.microsoft.sqlserver.jdbc.SQLServerConnection.endRequestInternal(), which closes all the open prepared statements on the connection.

If the problem is as above I would not be able to say which side, Ironjacamar or ms-sql JDBC, is doing the right thing.

[https://issues.redhat.com/browse/JBJCA-1434](https://issues.redhat.com/browse/JBJCA-1434)

## Reproduction code
Please look
[https://issues.redhat.com/browse/WFLY-15493](https://issues.redhat.com/browse/WFLY-15493)

**Comment by v-zhangw** [comment] 2021-12-06 20:25
Hello @vtuonone,

Could you please provide a stand-alone Java repro?

**Comment by vtuonone** [comment] 2021-12-07 10:28
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.DriverManager;

public class TestSqlStatement {

	public static void main(String[] a) throws Exception {
		Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
		String dbName="TestDB";
		String connectionStr=
				"jdbc:sqlserver://localhost;database="+dbName+";sendStringParametersAsUnicode=false;disableStatementPooling=false;statementPoolingCacheSize=100;serverPreparedStatementDiscardThreshold=100;enablePrepareOnFirstPreparedStatementCall=true";
		String dbUser="sa";
		String dbPwd="Password";
		String tableName="TestTable";
		workingSet(connectionStr,dbUser,dbPwd,tableName);
		workingSet2(connectionStr,dbUser,dbPwd,tableName);
		nonWorkingSet(connectionStr,dbUser,dbPwd,tableName);
	}
	
	private static void workingSet(String connectionStr,String dbUser,String dbPwd,String tableName) throws SQLException {
		Connection con = DriverManager.getConnection(connectionStr,dbUser, dbPwd);
		//This works no beginRequest & endRequest at all
		Statement stmt = con.createStatement();
		printIds("workingSet",tableName,stmt);
		printIds("workingSet",tableName,stmt);
		con.close();
	}
	
	private static void workingSet2(String connectionStr,String dbUser,String dbPwd,String tableName) throws SQLException {
		Connection con = DriverManager.getConnection(connectionStr,dbUser,dbPwd);
		//This works Statement create berfore fist beginRequest call 
		Statement stmt = con.createStatement();
		con.beginRequest();
		printIds("workingSet2",tableName,stmt);
		con.endRequest();
		con.beginRequest();
		printIds("workingSet2",tableName,stmt);
		con.endRequest();
		con.close();
	}
	
	private static void nonWorkingSet(String connectionStr,String dbUser,String dbPwd,String tableName) throws SQLException {
		Connection con = DriverManager.getConnection(connectionStr,dbUser,dbPwd);
		//beginRequest before Statement creation first work second gives error
		con.beginRequest();
		Statement stmt = con.createStatement();
		printIds("nonWorkingSet",tableName,stmt);
		con.endRequest();
		con.beginRequest();
		printIds("nonWorkingSet",tableName,stmt);
		con.endRequest();
		con.close();
	}
	
	private static void printIds(String testSet,String tableName, Statement stmt) throws SQLException {
		ResultSet rs = stmt.executeQuery("select id from "+tableName);
		while (rs.next()) {System.out.println(testSet+":"+rs.getLong(1));}
	}
}

**Comment by vtuonone** [comment] 2021-12-07 15:25
@v-zhangw example added with and without beginRequest&endRequest calls

**Comment by v-zhangw** [comment] 2021-12-09 17:56
Hi @vtuonene,
EndRequest closing open prepared statements in this scenario is intended and is by design for the JDBC Driver.

**Comment by vtuonone** [comment] 2021-12-09 19:05
OK I understand and found it also from documentation now
[https://docs.microsoft.com/bs-cyrl-ba/sql/connect/jdbc/jdbc-4-3-compliance-for-the-jdbc-driver?view=sql-server-2016](https://docs.microsoft.com/bs-cyrl-ba/sql/connect/jdbc/jdbc-4-3-compliance-for-the-jdbc-driver?view=sql-server-2016)
 but it as JDBC 4.3 wanted it to be because for example Oracle DB works differently it does not close prepared statements
 when  real connection is checked out and back to the pool.
[https://docs.oracle.com/en/database/oracle/oracle-database/21/jjdbc/statement-and-resultset-caching.html](https://docs.oracle.com/en/database/oracle/oracle-database/21/jjdbc/statement-and-resultset-caching.html)
[ https://docs.oracle.com/javase/9/docs/api/java/sql/Connection.html#endRequest--]( https://docs.oracle.com/javase/9/docs/api/java/sql/Connection.html#endRequest--)
[ https://docs.oracle.com/javase/9/docs/api/javax/sql/PooledConnection.html]( https://docs.oracle.com/javase/9/docs/api/javax/sql/PooledConnection.html)

How prepared statement cache can be used with begin+end request calls. (external connection pool)
The main purpose of those calls is to be a hint provided by the connection pool to the driver that a connection has been checked out of the pool (beginRequest) or checked back into the pool (endRequest).
[https://dba.stackexchange.com/questions/189543/what-is-the-new-jdbc-4-3-connection-request-feature-with-beginrequest-endre](https://dba.stackexchange.com/questions/189543/what-is-the-new-jdbc-4-3-connection-request-feature-with-beginrequest-endre)

**Comment by lilgreenbird** [comment] 2021-12-23 19:39
closing due to non-driver issue, please free free to request re-opening if you have other driver related questions

**Closed by lilgreenbird** 2021-12-23 19:39 UTC
Labels: wontfix, Waiting for response

**Comment by roeltje25** [comment] 2022-11-03 14:18
According to Wildfly this IS a driver issue. please refer here:

https://issues.redhat.com/browse/WFLY-15493

**Comment by roeltje25** [comment] 2022-11-03 14:20
maybe if you guys talk with them guys you can try to fix this, because everybody pointing to each other is not very productive!

**Comment by Jeffery-Wasty** [comment] 2022-11-03 20:43
Hi @roeltje25,

I'm not seeing where Wildfly says this IS a driver issue. It's acknowledged that this is an intentional decision by our driver, and I see a potential workaround proposed by "vtuonone" using driver version 10.2 and configuring data source as xa-datasource. There appears to be a linked thread by Dennis Read that we do not have access to, I'm not sure if this is what you're referring to. Is there any news on a resolution from WildFly's side?

**Comment by roeltje25** [comment] 2022-11-10 13:58
Dear Jeffery-Wasty,

I agree that Wildfly as such is not saying this IS a driver issue. but that it should be worked around. The problem is that it requires a XA Datasource, which will require MS DTS to be available, which requires a more recent SQL server than the one we have available.

Also regarding this issue I find the documentation of SQLServerConnection confusing:

> Prepared statements are prepared once and typically executed many times with different data values for their parameters. Prepared statements are also maintained across logical (pooled) connection closes.

This seems not to be the case in when using the driver in wildfly.... the prepared statements gtet closed between requests...

**Comment by Jeffery-Wasty** [comment] 2022-11-15 21:22
Hi @roeltje25,

I agree this presents an issue, at least from how you describe it, and should be worked around. But as stated before, the current behavior around endRequest and prepared statements is by design, and we cannot change it. It appears that there is work to resolve the issue ongoing on WildFly's side, and if there are additional ways the driver can help, we're more than happy to take a look at it. We'll keep an eye on the issue you linked, for updates.

Regarding the docs: Connection.endRequest() will explicitly close open prepared statements. Therefore, the documentation is correct, the statements are maintained unless they are explicitly closed by something like endRequest(). We can take a look at adding clarification here for the next release.

**Comment by roeltje25** [comment] 2022-12-21 09:16
Dear @Jeffery-Wasty ,

To give a little push-back on the claim that this is not a driver issue. The JDBC spec is not at all requiring prepared statements to be closed on an endRequest call.  As can be seen in the javadoc of the endRequest call [here](https://javadoc.scijava.org/Java9/java/sql/Connection.html#endRequest--). The methods were added to JDBC to indicate that a unit of work was done and are supposed to be used by connection pool managers (like the one in wildfly). (refer to [here](https://groups.google.com/g/r2dbc/c/zZ09hFMR9N8/m/aTKoFU8pBwAJ)) These managers are likely to cache prepared statements as well. Transparently using the endRequest method hint, as specified, may then in some vendors work fine, and other vendors (=Microsoft SQL JDBC Driver) clean the statements, making the prepared statement cache break.... While the spec actually defines this should be supported in [JSR 221](https://download.oracle.com/otn-pub/jcp/jdbc-4_3-mrel3-spec/jdbc4.3-fr-spec.pdf?AuthParam=1671613668_ad8b575d94e8b7dd8d5dd742ddd0b3f6) Section 11.6. It seems the MS SQL Driver is one of the few drivers actually implementing the JDBC 4.3 behavior to close the PreparedStatements. Even open-liberty [here](https://github.com/OpenLiberty/open-liberty/issues/4734) claims this a very strict and not specified behavior.

As such, I would strongly suggest that the prepared statements should not be closed on endRequest calls. Or at least, there should be an option in the driver to bypass this - I must say problematic - behavior. Would you guys be open for a driver option that can bypass the cleanup of prepared statements?

thanks for your consideration,

Roel

**Comment by liebsche** [comment] 2022-12-21 17:14
Good comment. But will anyone see your comment on a closed issue?!
Perhaps could you open another issue?

**Comment by tadamski** [comment] 2023-01-03 13:47
hello everyone

The fix for this issue was implemented in IronJacamar and is present in recent WildFly.
