### ISSUE TITLE
Performance difference in prepared statements compared to Open Source jTDS due to BigDecimal

### ISSUE THREAD

**Issue by dospencer** [microsoft/mssql-jdbc#1749] opened 2022-02-03 00:20 UTC
## SQL Server version

Microsoft SQL Azure (RTM) - 12.0.2000.8   Sep 18 2021 19:01:34   Copyright (C) 2019 Microsoft Corporation 

## Client Operating System

Windows

## JAVA/JVM version

java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

## Problem description

1. Expected behaviour: Insert of 85K records in less than 1 minute.
2. Actual behaviour: I encountered a performance issue with the MS JDBC driver. It takes about 39 minutes to insert 85K records into a MS SQL Server table using the MS SQL Server driver. If I use the Open Source JTDS driver then it takes only 39 seconds. The issue is only occurring when I have fields defined as BigDecimal in the application and that generates setBigDecimal for the prepared statement. If I change the data type from BigDecimal to Int, Float or Double, I do not get that performance issue.
3. Error message/stack trace:
4. Any other details that can be helpful:

**Comment by lilgreenbird** [comment] 2022-02-08 21:37
hi @dospencer 
Could you please provide the schema and the code to repro the issue?
Thanks

**Comment by Jeffery-Wasty** [comment] 2022-03-03 00:38
This issue has been inactive for >2 weeks, so we'll go ahead and close. @dospencer, if the issue persists, let us know, and can re-open the issue.

**Comment by vwarchu** [comment] 2022-03-11 18:57
@Jeffery-Wasty We should determine if this is A) Reproducible as a generic case, and B) Related or duplicate of issue #1489

**Comment by tkyc** [comment] 2022-04-04 16:58
Closing as it's been inactive, feel to re-open as necessary.

**Closed by tkyc** 2022-04-04 16:58 UTC
