### ISSUE TITLE
Query on NVARCHAR (encrypted with AE), not matching target column type

### ISSUE THREAD

**Issue by fairglen** [Microsoft/mssql-jdbc#476] opened 2017-09-04 16:36 UTC
## Driver version or jar name
6.3.1.jre8-preview.jar (also 6.2.0 and 6.3.2)

## SQL Server version
Microsoft SQL Azure (RTM) - 12.0.2000.8 

## Client operating system
Windows 10

## Java/JVM version
Zulu 8u144(OpenJdk)

## Table schema
lodb

## Problem description
Having a column defined as follows:
`[email] [nvarchar](255) COLLATE Latin1_General_BIN2 ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = [CEK_Auto1], ENCRYPTION_TYPE = Deterministic, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NULL,`

And then querying on it,(` select *** where email = 'johndoe@email.com'` ) generates the following error:
```
...
could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet] with root cause
com.microsoft.sqlserver.jdbc.SQLServerException: The data types **nvarchar(255)** encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'CEK_Auto1', column_encryption_key_database_name = 'lodbqassqldb') and **varchar(22)** encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'CEK_Auto1', column_encryption_key_database_name = 'lodbqassqldb') collation_name = 'SQL_Latin1_General_CP1_CI_AS' are incompatible in the equal to operator.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:260) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1547) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:528) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:461) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7346) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2688) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQueryInternal(SQLServerPreparedStatement.java:396) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getParameterEncryptionMetadata(SQLServerPreparedStatement.java:781) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:500) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:461) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7346) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2688) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:383) ~[mssql-jdbc-6.3.1.jre8-preview.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
...
```

## Expected behavior and actual behavior
Expected to match the target column type, seems to ignore database column type.

## Repro code
Not sure, if related to the following switch case:
https://github.com/Microsoft/mssql-jdbc/blob/55f0b7f40611c0985ea6122ecd3fef0f4bea16ca/src/main/java/com/microsoft/sqlserver/jdbc/Parameter.java#L804

**Comment by v-afrafi** [comment] 2017-09-05 18:07
Hello @fairglen. 
In order to retrieve values from encrypted columns, you need to make sure you are using preparedStatements and use parameters to send data for encrypted columns. I am adding this reference from SQL Server [Docs ]( https://docs.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver): 

> 
>  **Errors due to Passing Plaintext instead of Encrypted Values**
> 
>  Any value that targets an encrypted column needs to be encrypted inside the application. An attempt to insert/modify or to filter by a plaintext value on an encrypted column will result in an error similar to this:
> 
> 

> _com.microsoft.sqlserver.jdbc.SQLServerException: Operand type clash: varchar is incompatible with varchar(8000) encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'MyCEK', column_encryption_key_database_name = 'ae') collation_name = 'SQL_Latin1_General_CP1_CI_AS'_

> To prevent such errors, make sure:
> - always Encrypted is enabled for application queries targeting encrypted columns (for the connection string or for a specific query).
> - you use prepared statements and parameters to send data targeting encrypted columns. The below example shows a query that incorrectly filters by a literal/constant on an encrypted column (SSN), instead of passing the literal inside as a parameter. This query will fail.
>  

> `ResultSet rs = connection.createStatement().executeQuery("SELECT * FROM Customers WHERE SSN='795-73-9838'"); `

**Comment by v-afrafi** [comment] 2017-09-18 20:37
Hi @fairglen . Just wanted to follow up and check if the issue is resolved? Thanks.

**Comment by v-afrafi** [comment] 2017-09-21 17:52
Closing this issue. Please feel free to re open it if you needed further help. Thanks!

**Closed by v-afrafi** 2017-09-21 17:52 UTC
Labels: Waiting for response
