### ISSUE TITLE
STAsBinary is not returning in WKB format

### ISSUE THREAD

**Issue by humada05** [microsoft/mssql-jdbc#1280] opened 2020-03-06 04:07 UTC
## Driver version

7.4.1.jre8 (but includes all versions up til now)

## Problem description

1. Expected behaviour:
`STAsBinary()` method should return the spacial object in WKB format, [as detailed here](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry#Well-known_binary).

2. Actual behaviour:
`STasBinary()` returns the spacial object in CLR format.

Issue created from discussion in #1277.

**Comment by peterbae** [comment] 2020-03-06 17:41
Thanks for creating this issue @humada05. The team will look into this as discussed.

**Comment by ulvii** [comment] 2020-03-09 18:48
Potentially related to #1270.

**Comment by peterbae** [comment] 2020-06-18 20:06
Hi @humada05, I've created PR #1364 that fixes this issue. I'm attaching the jars here with the fix included. Could you try it out and let me know if STAsBinary is working as intended now? Thanks.
[github-1280.zip](https://github.com/microsoft/mssql-jdbc/files/4800948/github-1280.zip)

**Comment by peterbae** [comment] 2020-06-28 20:38
@humada05 were you able to find some time to test out my fix? Just double checking.

**Comment by humada05** [comment] 2020-06-29 18:59
Hey @peterbae, awesome! I'll be sure to test this out when i get some free time this week.

**Comment by peterbae** [comment] 2020-07-07 20:05
Fixed in #1364. Please let me know if you encounter any issues.

**Closed by peterbae** 2020-07-07 20:05 UTC
