### ISSUE TITLE
[Incident]Can't query the timestamp field  with  Timestamp type value

### ISSUE THREAD

**Issue by zfkang-talend** [microsoft/mssql-jdbc#1402] opened 2020-08-06 07:11 UTC
## Driver version

mssql-jdbc-8.3.1.jre8-preview.jar
## SQL Server version

liunx docker: mcr.microsoft.com/mssql/server:2017-latest
## Client Operating System

liunx docker
## JAVA/JVM version

java8
## Table schema

```
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[taskexecutionhistory](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[idquartzjob] [int] NULL,
	[taskstartdate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```
## Problem description

1. Expected behaviour:
2. Actual behaviour:
3. Error message/stack trace:
4. Any other details that can be helpful:
For the timestamp filed, don't query with the value of timestamp type, but used the string type, the result will be fetched. 
but for the windows sqlserver, use the timestap type value, will be fetched the data.

## Reproduction code

```
try {
    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
    String url = "jdbc:sqlserver://localhost:1433;databaseName=tac";
    String user = "sa";
    String password = "Root1234!";
    Connection connection = DriverManager.getConnection(url,user,password);
    String sql = "select * from taskexecutionhistory this_ where this_.idquartzjob=? and this_.taskstartdate=?";
    PreparedStatement stmt = connection.prepareStatement(sql);
    stmt.setInt(1, 1);
    stmt.setTimestamp(2, new Timestamp(1595457304057L)); 
    ResultSet rs = stmt.executeQuery();
    System.out.println("Office Timestamp===================");
    while(rs.next()){
        System.out.println(rs.getString("id"));
        System.out.println(rs.getString("idquartzjob"));
        System.out.println(rs.getString("taskstartdate"));
    }
    stmt.setString(2, "2020-07-23 06:35:04.057"); 
    rs = stmt.executeQuery();
    System.out.println("Office String===================");
    while(rs.next()){
        System.out.println(rs.getString("id"));
        System.out.println(rs.getString("idquartzjob"));
        System.out.println(rs.getString("taskstartdate"));
    }
    Class.forName("net.sourceforge.jtds.jdbc.Driver");
    url = "jdbc:jtds:sqlserver://localhost:1433/tac";
    connection = DriverManager.getConnection(url,user,password);
    stmt = connection.prepareStatement(sql);
    stmt.setInt(1, 1);
    stmt.setTimestamp(2, new Timestamp(1595457304057L)); 
    rs = stmt.executeQuery();
    System.out.println("JTDS timestamp===================");
    while(rs.next()){
        System.out.println(rs.getString("id"));
        System.out.println(rs.getString("idquartzjob"));
        System.out.println(rs.getString("taskstartdate"));
    }
    stmt.setString(2, "2020-07-23 06:35:04.057"); //new Timestamp(1595426707000L)
    rs = stmt.executeQuery();
    System.out.println("JTDS String===================");
    while(rs.next()){
        System.out.println(rs.getString("id"));
        System.out.println(rs.getString("idquartzjob"));
        System.out.println(rs.getString("taskstartdate"));
    }
} catch (Exception e) {
    e.printStackTrace();
}
```
the output:
Result:
1. Execute on Liunx which contains MSSQL
```
Office Timestamp===================      
Office String===================         
1                                        
1                                        
2020-07-23 06:35:04.057                  
JTDS timestamp===================        
JTDS String===================           
1                                        
1                                        
2020-07-23 06:35:04.057                  
```
2. Execute on windows and remote connect liunx MSSQL
```
Office Timestamp===================
Office String===================
1
1
2020-07-23 06:35:04.057
JTDS timestamp===================
1
1
2020-07-23 06:35:04.057
JTDS String===================
1
1
2020-07-23 06:35:04.057
```
3. Execute on windows and local MSSQL：
```
Office Timestamp===================
1
1
2020-07-23 10:12:12.433
Office String===================
1
1
2020-07-23 10:12:12.433
JTDS timestamp===================
1
1
2020-07-23 10:12:12.433
JTDS String===================
1
1
2020-07-23 10:12:12.433
```

**Comment by rene-ye** [comment] 2020-08-07 22:13
Hi @zfkang-talend, I'll see if I can reproduce the issue on our end and get back to you.

**Comment by rene-ye** [comment] 2020-08-13 17:16
Hi @zfkang-talend, so the reason this is happening is because the driver expects a java.sql.TIMESTAMP to be a datetime(2). And datetime cannot be implicitly converted to a datetime(2) on the server side. JTDS works because their TIMESTAMP supports smalldatetime and datetime, whereas we technically have it mapped to datetime and datetime(2). There's no fix for this currently, and the team will discuss what to do moving forward.

**Comment by rene-ye** [comment] 2020-08-31 22:11
Hi @zfkang-talend, do you have any question regarding my comment above? Does the workaround resolve your issue? We've added a note on the datetime data type mapping on our [MSDN site](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-basic-data-types?view=sql-server-ver15) to clarify this interation.

**Comment by rene-ye** [comment] 2020-09-15 20:04
Closing due to inactivity, please feel free to re-open/create a new issue if there are anymore questions.

**Closed by rene-ye** 2020-09-15 20:04 UTC
