### ISSUE TITLE
Search String Escape does not work for  SQLServerDatabaseMetaData.getColumns

### ISSUE THREAD

**Issue by uffeweil** [microsoft/mssql-jdbc#1195] opened 2019-11-28 09:20 UTC
## Driver version
7.4.1.0

## SQL Server version
Microsoft SQL Server 2017 (RTM-CU8) (KB4338363) - 14.0.3029.16 (X64) 
	Jun 13 2018 13:35:56 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 16.04.4 LTS)
## Client Operating System
macOS 10.14.6

## JAVA/JVM version
Java Version: 1.8.0_181
Java VM: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation

## Problem description
SQLServerDatabaseMetaData.getColumns("master", "dbo", "spt\_fallback\_db", "%") returns no columns when using Driver version 7.4.1. When using 7.2.2 it works fine. 

## JDBC trace logs
Logging driver not possible.

## Reproduction code
See above

**Comment by ulvii** [comment] 2019-11-28 20:34
Hi @uffeweil,
Seems like duplicate of #1136 , which is already fixed in 7.5.0 version of the driver, please give it a try.

**Comment by uffeweil** [comment] 2019-11-28 20:46
Thanks, can't believe I missed that one. Is the 7.5.0 version published anywhere?
I have looke in https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server
and https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc

**Comment by ulvii** [comment] 2019-11-28 20:49
Apologies, the fix is in 8.1.0 version. You can find the artifacts on [Maven](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc) and [GitHub](https://github.com/microsoft/mssql-jdbc/releases/tag/v8.1.0).

**Comment by uffeweil** [comment] 2019-11-28 20:56
Thanks!

**Comment by ulvii** [comment] 2019-11-28 23:23
Closing the issue. Please let us know if you have any more questions.

**Closed by ulvii** 2019-11-28 23:23 UTC
