### ISSUE TITLE
SqlServerResultSetMetaData.getTableName returns blank

### ISSUE THREAD

**Issue by thlv** [Microsoft/mssql-jdbc#753] opened 2018-07-20 05:37 UTC
## Driver version or jar name
mssql-jdbc:6.4.0.jre8

## SQL Server version
SQL Server 2016

## Client operating system
Windows 10

## Java/JVM version
 java version "1.8.0_172"

## Problem description
After executing a statement and getting the SqlServerResultSetMetaData from the result set, calling SqlServerResultSetMetaData.getTableName(columnIndex) resulted in an empty string.

## Expected behavior and actual behavior
Expected to see the table name the column is associated with.
Actual result is an empty string.

## Repro code
```
String sql = "select * from table1";
try (Statement stmt = connection.createStatement())
{
      try (ResultSet resultSet = stmt.executeQuery(sql))
      {
             ResultSetMetaData metadata = resultSet.getMetaData();
             String tableName = metadata.getTableName(1);
      }
}
```

**Comment by rene-ye** [comment] 2018-07-24 22:38
Hi @thlv, the JDBC specs allow for these functions to return an empty string if inapplicable. The Oracle JDBC driver currently also exhibits the same behavior due to some complications in implementing this feature. For example: if a user joins 2 tables on 'column A' and then calls getTableName on 'column A', what is the "expected behavior" that the driver should exhibit? One "solution" is to return the underlying table name, while another is to return an empty string if there are multiple tables used to create the ResultSet (which is a little weird because a user wouldn't be using this API if they were only selecting data from a single table). Another issue is that the driver would have to do an extra query to obtain information such as table/schema name on a specific column; this information is not sent by the database when returning the ResultSet.

The team will discuss what can be done, and possibly add a "solution" as a feature in the future.

**Comment by rene-ye** [comment] 2019-01-07 19:03
**Update:** SQL Server currently only sends the TableName column information for text, ntext, and image columns. This behavior is described as "The TableName element is specified only if a text, ntext, or image column is included in the result set." in the MS TDS document. Users are able to retrieve the Table Name only from text, ntext, or image columns from said result set. The server does not send table name information for the rest of the columns, even if they were part of the same result set as a text, ntext, or image column.

SQL Server supports sending table name when in cursor mode. Users can turn this on by specifying "selectMethod=cursor" in the connection properties or using the corresponding setter method `setSelectMethod("cursor")` in `SQLServerDataSource`.

**Comment by cheenamalhotra** [comment] 2019-01-10 19:11
@thlv 

As mentioned by @rene-ye above, the table name info can be retrieved by running query in Cursor Mode, as that is what SQL Server supports. We'll close the issue as driver is working as expected, and no fix is needed.

**Closed by cheenamalhotra** 2019-01-10 19:11 UTC
Labels: enhancement
