### ISSUE TITLE
[QUESTION] Unexpected BulkWrite behavior with new JDBC driver

### ISSUE THREAD

**Issue by hiumingw** [microsoft/mssql-jdbc#1879] opened 2022-07-27 18:00 UTC
## Question
We are currently evaluating the new JDBC driver 8.4.1 and found a couple unexpected issues. 

1. We have a column with type VARCHAR in SQLServer table, after performing bulk write to this table with String values, the table column type got converted to NVARCHAR.  ( Expected: type and collation stay the same after bulkwrite)

2. We have a column with type BIT in SQL Server table, after performing bulk write to the table with INT values, the table column type got converted to INT (Expected: throw exception instead of converting the column type)

3. We have a column with type SMALLDATETIME in SQLServer table, after performint bulk write to this table with TimeStamp values, the table column type got converted to DATETIME( Expected: either convert TimeStamp to SmallDateTime or throw conversion exception)

**Comment by tkyc** [comment] 2022-07-28 19:11
Is 8.4.1 the correct driver version (just making sure as you referred to that as "new" because that is actually old)? Could also provide us the SQL Server version and Java version you're using as well? If possible, a reproduction app that reproduces your issue would help also.

That sounds odd that doing a bulk insert would change the column type. Just clarifying, do you mean you inserted data that's different from the column type? If so, I'd recommend that you be more explicit with the data type you're inserting.

**Comment by hiumingw** [comment] 2022-08-01 17:37
Hello, our app is Spark application deployed in HDInsight. It uses Microsoft spark-mssql-connector to bulk write data to SQLServer DB, this library uses JDBC 8.4.1.   
Java Version - 1.8
SQL Server version - 14

We can easily reproduce the issue with below steps, for example for Bit to Int type

1. create a table with original column type
  CREATE TABLE BitTable
 ( 
 	flag Bit NOT NULL
 )

2. In Jupyter notebook, import spark-mssql-connector
%%configure
{ "conf": {"spark.jars.packages": "com.microsoft.azure:spark-mssql-connector:1.0.2" }}

3. In the same Jupyter notebook, run below code to insert Int values to the BitTable, 
val collationDF = Seq(
  (111),
  (222),
  (333),
(0)
).toDF("flag")

import com.microsoft.azure.sqldb.spark.config._
import com.microsoft.azure.sqldb.spark.connect._
import com.microsoft.azure.sqldb.spark.query._
import com.microsoft.azure.sqldb.spark._
import com.microsoft.azure.sqldb.spark.bulkcopy._

val bulkCopyConfig = Config(Map(
  "url"               -> "xxxx",
  "databaseName"      -> "Staging",
  "user"              -> "xxxx",
  "password"          -> "xxxx",
  "dbTable"           -> "dbo.BitTable",
  "bulkCopyBatchSize" -> "250000",
  "bulkCopyTableLock" -> "true",
  "bulkCopyTimeout"   -> "3000"
))
collationDF.bulkCopyToSqlDB(bulkCopyConfig)

4. Check the column type after step 3 completed and the type is changed to INT
BitTable	flag	NULL	int

I also have the sample codes for the other conversion issues. Please let me know if you need them to reproduce

thanks

**Comment by Jeffery-Wasty** [comment] 2022-08-10 19:19
Hi @hiumingw,

Addressing of this issue has been delayed a bit, as we've been focused on our 11.2.0 release. With the release out, we'll be returning to look at key issues, this one included. 

Thank you for the repro code, we'll look into this further, and get back to you with our findings.

**Comment by Jeffery-Wasty** [comment] 2022-08-10 19:23
Can you include the additional sample code you have? Like you said, the first one should work, but to save back and forth it would be great to get it now if needed.

**Comment by hiumingw** [comment] 2022-08-11 17:13
Thanks Jeffery. I am listing below two other issues we observed

1. varchar type was converted to nvarchar
- First, create a table with varchar type
 CREATE TABLE CollationTable
 ( 
 	PostalCode varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
 )

- Confirm column type as below
 CollationTable	PostalCode	SQL_Latin1_General_CP1_CI_AS	varchar

- Run below sample code to bulkWrite 
%%configure
{ "conf": {"spark.jars.packages": "com.microsoft.azure:spark-mssql-connector:1.0.2" }}

import spark.implicits._

val collationDF = Seq(
  ("88888"),
  ("52803-2459"),
  (" "),
  ("")
).toDF("PostalCode")

val server_name = "SQLServer"
val database_name = "Staging"
val url = server_name + ";" + "databaseName=" + database_name + ";"

(collationDF.write 
    .format("com.microsoft.sqlserver.jdbc.spark") 
    .mode("overwrite") 
    .option("url", url) 
    .option("dbtable", "dbo.CollationTable") 
    .option("user", "USER") 
    .option("password", "PWD")
    .option("batchSize", "250000") 
    .option("tableLock", "true") 
    .option("bulkCopyTimeout", "3000") 
    .save())

- after write the collation for this column changed
//CollationTable	PostalCode	SQL_Latin1_General_CP1_CI_AS	nvarchar

**Comment by Jeffery-Wasty** [comment] 2022-08-17 17:24
Hi @hiumingw,

We're still struggling on reproducing this using Jupyter notebook and the spark-mssql-connector. Is there any way you can provide repro code that we can run without the use of Jupyter?

**Comment by hiumingw** [comment] 2022-08-22 17:43
@Jeffery-Wasty, I will try to create sample codes to reproduce these issues

**Comment by lilgreenbird** [comment] 2022-08-22 21:27
hi @hiumingw 

Could you please provide a standalone java repro that use the driver directly without any 3rdparty products?
Thanks..

**Comment by Jeffery-Wasty** [comment] 2022-08-30 22:24
Hi @hiumingw,

Is there any update on the sample repro code?

**Comment by hiumingw** [comment] 2022-08-31 16:09
Hi @Jeffery-Wasty, sorry I am planning to work on this next week, have been really busy with production last few weeks

**Comment by Jeffery-Wasty** [comment] 2022-08-31 16:45
No need to apologize, we're thankful you're able to spend time providing this repro code in the first place. Please keep us up to date on any changes, we'll keep the issue open in the meantime.

**Comment by hiumingw** [comment] 2022-09-09 22:59
@Jeffery-Wasty, after i wrote a standalone program directly calling JDBC and another one calling through sql-spark-connector. It looks like the issue occur with the latter. I will check with sql-spark-connector team to confirm and will update once we determine the cause

**Comment by lilgreenbird** [comment] 2022-09-13 00:11
hi @hiumingw 

So am I understanding this correctly that there are no issues with a standalone java program calling the driver directly and you will be following this up with Spark? If so, we will be closing this issue at our end.
Thanks.

**Comment by hiumingw** [comment] 2022-09-13 16:14
@lilgreenbird @Jeffery-Wasty. Please close the issues and thanks for the help.

**Comment by Jeffery-Wasty** [comment] 2022-09-13 16:47
@hiumingw Thanks for confirming the source of the issue, we'll close this issue now.

**Closed by Jeffery-Wasty** 2022-09-13 16:47 UTC
Labels: Under Investigation
