### ISSUE TITLE
[QUESTION] How to use NTLM properly (jdbc string and "untrusted domain") 

### ISSUE THREAD

**Issue by gpow81** [microsoft/mssql-jdbc#2127] opened 2023-05-11 17:49 UTC
## Question
Hi I am hopping that this is the right place and I can ask multiple questions in one thread. I really struggle with this and vendors are not helpful at all 
I am installing a product (on Linux SLES)  which is using jdbc driver to connect to MS SQL database and I need to use Windows login for the connection (it works fine with a local SQL login but I can't use that). 

From all my reaserch so far, I should be using authenticateScheme=NTLM but everything I tried so far failed. 
Also the database is not using an encryption. 

**Is encryption a requirement for NTLM by any chance?**

Here is the jdbc string which got me closest so far:
jdbc:sqlserver://server:port;DatabaseName=db_name;encrypt=false;integratedSecurity=true;domain=MYDOMAIN;user=blabla;password=blabla;authenticationScheme=NTLM

Error I get:
com.microsoft.sqlserver.jdbc.SQLServerException: Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication

**Does linux need to be a member of the windows domain? ** It is in my case (with winbind and samba) but I just want to make sure I understand this. 

I am logged in as root user when I do the install. I tried switching to the domain user and run install from it but I was getting same error. 

Please let me know what else I should check. Thank you

**Comment by tkyc** [comment] 2023-05-12 19:23
@gpow81 So for NTLM, it's not necessary to enable encryption, having `encrypt=false` is just fine.

> Does linux need to be a member of the windows domain?

Yes, your client linux machine needs to be part of the domain. Since you confirmed your linux machine is domain joined, the one other reason I can think of as to why it failed to connect is because of your connection string. Try the following connection string instead:

`jdbc:sqlserver://<your-server's-FQDN>:port;DatabaseName=db_name;encrypt=false;integratedSecurity=true;user=blabla;password=blabla;authenticationScheme=NTLM`

So, exclude the `domain=MYDOMAIN` property/value pair, and rather have the domain name included in the server field in the connection string.

Can you also provide more details, what driver version are you using and JDK version? Could you also provide the SQL Server logs as well when that error occurs? Thanks.

**Comment by tkyc** [comment] 2023-05-12 19:32
I realize you confirmed you're domain joined, but just for my own confirmation can you verify by running `realm list` on your linux client?

**Comment by gpow81** [comment] 2023-05-12 20:06
Thank you for your help. 
Unfortunately removing the domain property and adding to the server name did not change the error. 
This linux (SLES15) server didn't have realm used/installed for domain join. There is a net tool which I believe might have been used to join the domain. And allows me to show some information (I replaced the actual vales):

net ads info
LDAP server: 192.x.x.x
LDAP server name: host.domain.com
Realm: DOMAIN.COM
Bind Path: dc=DOMAIN,dc=COM
LDAP port: 389
Server time: Fri, 12 May 2023 14:53:54 CDT
KDC server: 192.x.x.x
Server time offset: 0
Last machine account password change: Fri, 12 May 2023 07:36:26 CDT

Is it possible that I am still missing something in the domain for this? I am able to log in to linux using my AD creds and I am also able to obtain a ticket by running kinit command. 
I will try to get logs from SQL team but I think last time they told me there were none so it seems that it is failing during or even before prelogin. Although in tcpdump I can see that it is reaching the SQL server. 
bit thanks for trying to help!

**Comment by tkyc** [comment] 2023-05-12 20:17
That's really strange. Just as a quick test (since you mentioned you were able to use kinit), could you try a kerberos authentication?   You'll need to remove the user and password properties and just set `authenticationScheme=JavaKerberos`. I'm just curious if this would fail too because kerberos also requires to be domain joined, but you were able to do a kinit.

**Comment by tkyc** [comment] 2023-05-12 20:25
> Is it possible that I am still missing something in the domain?

Not that I know of. From my own experience, after domain joining the machine NTLM auth should work. Also, what driver version are you on?

**Comment by lilgreenbird** [comment] 2023-05-15 08:09
hi @gpow81 

Apologies, you do need the `domain` property for NTLM authentication. Could you please tell us what driver version and SQL Server version you are using? Please note NTLM is not supported on Linux SQL Server.

Also, please provide a FINEST log that will give us more info on where the failure is occurring. Please see [Tracing driver operation](url) on how to enable logging for the driver.  

Thanks.

**Comment by gpow81** [comment] 2023-05-15 13:03
@tkyc , when I tried the kerberos authentication I got "Login failed for user … " error. I run it after successful kinit. 
I am using 12.2.0 driver 
@lilgreenbird It's 12.2.0. The mysql server is on MS Windows but I will double check that. I will try to set log to Finest which might be a bit tricky since the error happens during the installation of the product so the path of log4jd properties/xml file is not even there yet. I will try to precreate it before install. 
I will report back as soon as I have more. thank you helping out!

**Comment by tkyc** [comment] 2023-05-15 18:55
Right now, I want to suspect it's an issue with the SPN with the SQL Server, if you could get the sql server logs it should indicate if it is. Could you also confirm you sql server version? Also, for the domain user used to authenticate, can you confirm that user is added to SQL Server as a login?

**Comment by gpow81** [comment] 2023-05-17 16:59
Can you explain what you mean by having user added as a login? From my understanding it may be either SQL login or Domain login. And as far as I know this is a domain login in our case. Are you saying that it should be both? 

I am still trying to get logs. Is the SQL log only place where we can find some explanation or it would be worth looking into AD logs as well? or domain controller?

**Comment by gpow81** [comment] 2023-05-17 19:52
Problem has been solved.  I was told that user was missing some group membership.  
My final jdbc string was 
jdbc:sqlserver://server:port;DatabaseName=db_name;encrypt=false;integratedSecurity=true;domain=MYDOMAIN;authenticationScheme=NTLM 
The user and password was provided in next prompt coming from the product installation wizard without the MYDOMAIN\ prefix. 
Thank you all for your help!

**Comment by lilgreenbird** [comment] 2023-05-17 20:52
ah that's good to know! we will go ahead and close this issue please let us know if you have more questions

**Closed by lilgreenbird** 2023-05-17 20:52 UTC
Labels: Waiting for Response
