### ISSUE TITLE
[QUESTION] How do I connect to a server which forces TLSv1.0 encryption?

### ISSUE THREAD

**Issue by eladitzhakian** [microsoft/mssql-jdbc#2305] opened 2024-01-26 09:39 UTC
## Question
There's an old SQL server which uses TLSv1.0 that I need to connect to. After struggling with the CLI tool `sqlcmd` I was able to connect to the server using `-N disable` which to my understanding disables encryption and skips the handshake. Unfortunately I haven't been able to do the same with MSSQL JDBC. Setting `encrypt=false` does not seem to do the trick.

Is there a way to completely go around the SSL handshake? Or make the driver use TLSv1.0?

**Comment by Jeffery-Wasty** [comment] 2024-01-26 17:15
Hi @eladitzhakian,

Setting `sslProtocol=TLSv1` is what you're looking for .

For more information, please see [SSL Protocol](https://github.com/microsoft/mssql-jdbc/wiki/SSLProtocol#why-was-this-connection-property-introduced) in out Wiki.

**Comment by Jeffery-Wasty** [comment] 2024-01-30 18:30
Hi @eladitzhakian,

Has this worked for you? Without further communication, we'll assume the issue is resolved, and move forward with closing the issue.

**Comment by Jeffery-Wasty** [comment] 2024-02-05 18:14
Closing for inactivity.

**Closed by Jeffery-Wasty** 2024-02-05 18:14 UTC
