### ISSUE TITLE
java.sql.Timestamp handled inconsistently by datetimeoffset

### ISSUE THREAD

**Issue by navpil** [Microsoft/mssql-jdbc#758] opened 2018-07-24 12:32 UTC
## Driver version or jar name
6.4.0.jre8

## SQL Server version
13.0.4422

## Client operating system
Windows 10 Enterprise (1607)

## Java/JVM version
jdk1.8.0_102 (Oracle)

## Table schema
create table times (
    id varchar(255) not null,
    start_time datetimeoffset
)

## Problem description
I want to store DateTime into the DB so that it can be used internationally. So I picked the `datetimeoffset`.
When I use the `java.sql.Timestamp` the zone information is removed, so when I store 'Mon Jul 23 16:09:14 EEST 2018' it is being simply stored as '2018-07-23 16:09:14.0000000 +00:00'.
But when I retrieve this column, then I get 'Mon Jul 23 19:09:14 EEST 2018'. So it treats the datetimeoffset as UTC offset. The problem is that when I store Timestamp I get another Timestamp back.

Using `microsoft.sql.DateTimeOffset` is not an option, I prefer using standard java types.

## Expected behavior and actual behavior
I expect to store time information and get the same time back.
Please note - if you're in UTC time the code will work correctly. Please move to another timezone.

## Repro code

    import java.sql.Connection;
    import java.sql.DriverManager;
    import java.sql.PreparedStatement;
    import java.sql.ResultSet;
    import java.sql.SQLException;
    import java.sql.Timestamp;
    import java.util.Date;
    import java.util.NoSuchElementException;
    import java.util.Random;

    public class Main {

        public static void main(String args[]) throws Exception {
            Date now = new Date();
            Timestamp timestampToSave = new Timestamp(now.getTime());
            Timestamp timestampRetrieved = saveAndGet(timestampToSave);
            showDate(timestampToSave);
            showDate(timestampRetrieved);
            System.out.println("Times are the same: " +
                    (timestampToSave.getTime() == timestampRetrieved.getTime()));
        }

        private static Timestamp saveAndGet(Timestamp timestamp) throws SQLException {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=mssqldatetimes";
            try (Connection c = DriverManager.getConnection(url, "admin", "Qwerty1234")) {
                String uniqueId = "id" + new Random().nextInt();
                String saveSql = "insert into times(id, start_time) values (?, ?)";
                try (PreparedStatement save = c.prepareStatement(saveSql)) {
                    save.setString(1, uniqueId);
                    save.setTimestamp(2, timestamp);
                    save.execute();
                }
                String getSql = "select start_time from times where id = ?";
                try (PreparedStatement get = c.prepareStatement(getSql)) {
                    get.setString(1, uniqueId);
                    ResultSet resultSet = get.executeQuery();
                    if (resultSet.next()) {
                        return resultSet.getTimestamp(1);
                    }
                }
            }
            throw new NoSuchElementException();
        }

        private static void showDate(Timestamp timestampToSave) {
            System.out.printf("Timestamp: %s, Date: %s, Milliseconds: %d%n",
                    timestampToSave,
                    new Date(timestampToSave.getTime()),
                    timestampToSave.getTime());
        }

    }

**Comment by ulvii** [comment] 2018-07-26 01:03
Hi @navpil ,
The behavior is by design. 
Note that date and time parts of [`datetimeoffset `](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetimeoffset-transact-sql?view=sql-server-2017) are relative to UTC and the driver [explicitly uses UTC](https://github.com/Microsoft/mssql-jdbc/blob/07641b0ae04ad3ffcd0109ab7746207f64a16a31/src/main/java/com/microsoft/sqlserver/jdbc/DDC.java#L764) to construct `Timestamp` object when calling `getTimestamp()` on a `datetimeoffset` column. 
You should call `save.setTimestamp(2, timestamp, Calendar.getInstance(TimeZone.getTimeZone("UTC")));` instead of `save.setTimestamp(2, timestamp);` to notify the driver about underlying `datetimeoffset` column, if you decide not to use `microsoft.sql.DateTimeOffset`.

**Comment by navpil** [comment] 2018-07-26 06:39
Hi @ulvii,
Thank you for information. I haven't seen this workaround before on the web.
Just in case anyone else reads this thread I will leave the (similar) workaround I used for Hibernate. I could not make it save `Timestamp` or `Date` correctly, so I used the `java.util.Calendar` for the temporal data. This is how the `Calendar` should be created to be stored correctly in `datetimeoffset`:

    public Calendar createUtcCalendarFromDate(Date date) {
        if (date == null) {
            return null;
        }
        Calendar calendar = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
        calendar.setTime(date);
        return calendar;
    }

In case there is a better solution for Hibernate, please post it here.

**Comment by ulvii** [comment] 2018-07-26 17:39
Glad you could resolve it. I am closing the issue, please feel free to re-open it or create a new one if you have any other questions.

**Closed by ulvii** 2018-07-26 17:39 UTC

**Comment by ul8422** [comment] 2021-11-11 12:31
Hi!
Sorry, but it looks like a bug.
* `java.sql.timestamp` on one hand represents local time but on the other time it represents ~timestamp/instant.

Please look at my code and the result:
```java
        Instant date = LocalDateTime.of(2010, 1, 1, 0, 0).toInstant(ZoneOffset.UTC);

        try (Connection conn = DriverManager.getConnection(mssql.getJdbcUrl(), mssql.getUsername(), mssql.getPassword())) {
            conn.setAutoCommit(true);
            // DDL
            try (Statement statement = conn.createStatement()) {
                statement.execute("create table test_table (test_date datetimeoffset)");
            }
            // INSERT
            try (PreparedStatement preparedStatement = conn.prepareStatement("insert into test_table values (?)")) {
                preparedStatement.setTimestamp(1, Timestamp.from(date));
                preparedStatement.execute();
                System.out.println("timestamp represents LOCAL DATE on the one hand: " + Timestamp.from(date).toString());
                System.out.println("timestamp represents ~INSTANT on the other hand: " + Timestamp.from(date).getTime()
                        + " - " + date.toEpochMilli());
            }
            // FETCH
            try (Statement statement = conn.createStatement()) {
                try (ResultSet rs = statement.executeQuery("select * from test_table")) {
                    if (rs.next()) {
                        Timestamp received = rs.getTimestamp(1);
                        System.out.println("ZoneId: " + ZoneId.systemDefault());
                        System.out.println("ORIGIN: " + date);
                        System.out.println("FETCHED: " + received.toInstant());
                    } else {
                        throw new RuntimeException("TLD");
                    }
                }
            }
        }
```

Result:
```java
timestamp represents LOCAL DATE on the one hand: 2010-01-01 03:00:00.0
timestamp represents ~INSTANT on the other hand: 1262304000000 - 1262304000000
ZoneId: Europe/Moscow
ORIGIN: 2010-01-01T00:00:00Z
FETCHED: 2010-01-01T03:00:00Z
```

SO, I expected to receive "2010-01-01T00:00:00Z". Postgres does it, H2 Database does it, Oracle so does...


Thanks in advance! :)
