### ISSUE TITLE
NullPointerException when query null date column

### ISSUE THREAD

**Issue by shgohh** [microsoft/mssql-jdbc#1253] opened 2020-02-05 01:54 UTC
## Driver version
Microsoft JDBC Driver 8.2

## SQL Server version
Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64) 

## Client Operating System
Windows 10

## JAVA/JVM version
jdk-13.0.2

## Table schema
create table test_date (date_col date);
insert into test_date(date_col) values(null);

## Problem description
NullPointerException was thrown when the following query was executed:-
select * from test_date;

1. Expected behaviour: one row return, date_col column is null
2. Actual behaviour: NullPointerException was thrown
3. Error message/stack trace:
java.sql.SQLException: java.lang.NullPointerException
	at workbench.storage.reader.RowDataReader.readColumnData(RowDataReader.java:411)
	at workbench.storage.reader.RowDataReader.read(RowDataReader.java:267)
	at workbench.storage.DataStore.initData(DataStore.java:1461)
	at workbench.storage.DataStore.initData(DataStore.java:1398)
	at workbench.sql.SqlCommand.processResults(SqlCommand.java:801)
	at workbench.sql.commands.SelectCommand.execute(SelectCommand.java:148)
	at workbench.sql.StatementRunner.runStatement(StatementRunner.java:552)
	at workbench.gui.sql.SqlPanel.displayResult(SqlPanel.java:3479)
	at workbench.gui.sql.SqlPanel.runStatement(SqlPanel.java:2210)
	at workbench.gui.sql.SqlPanel$16.run(SqlPanel.java:2148)
Caused by: java.lang.NullPointerException
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.getObject(SQLServerResultSet.java:2400)
	at workbench.storage.reader.ResultSetHolder.getObject(ResultSetHolder.java:145)
	at workbench.storage.reader.RowDataReader.readDateValue(RowDataReader.java:507)
	at workbench.storage.reader.RowDataReader.readColumnData(RowDataReader.java:293)
	... 9 more
4. Any other details that can be helpful:
-

**Comment by mprins** [comment] 2020-02-05 08:22
duplicate of #1249

**Comment by shgohh** [comment] 2020-02-06 01:11
Hi @ulvii ,
Yes, problem fixed in github-1249.zip, please consider to release new version, otherwise latest version 8.2 is just useless.

**Comment by ulvii** [comment] 2020-02-27 19:44
Hi @shgohh ,

The issue is now fixed in 8.2.1 release, which can be downloaded from [Download Center](https://www.microsoft.com/en-us/download/details.aspx?id=100855), [Maven](https://search.maven.org/artifact/com.microsoft.sqlserver/mssql-jdbc), [GitHub](https://github.com/microsoft/mssql-jdbc/releases/tag/v8.2.1).

**Closed by ulvii** 2020-02-27 19:44 UTC
