### ISSUE TITLE
TDSParser.parse method is throwing NullPointer Exception

### ISSUE THREAD

**Issue by rahulsavale13** [microsoft/mssql-jdbc#2531] opened 2024-10-30 06:15 UTC
## Driver version
mssql-jdbc-9.2.1.jre11

## SQL Server version
Microsoft SQL Server 2022 (RTM-CU15-GDR) (KB5046059) - 16.0.4150.1 (X64)   Sep 25 2024 17:34:41   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Datacenter 10.0 <X64> (Build 20348: ) (Hypervisor)

## Client Operating System
Windows 2022

## JAVA/JVM version
jdk11.0.9_12

The application installer is not able to upgrade the database and throwing below error -

#
2024-10-30 06:54:07,599 218826 ERROR [rome.database.DatabaseSetupManager] [processing thread]: FLYWAY UPGRADE ERROR: 
java.lang.NullPointerException: null
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:61)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:26)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.processExecuteResults(SQLServerStatement.java:1287)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.processResponse(SQLServerPreparedStatement.java:530)
	at com.microsoft.sqlserver.jdbc.TDSCommand.close(IOBuffer.java:7488)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.discardLastExecutionResults(SQLServerStatement.java:142)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.closeInternal(SQLServerStatement.java:653)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.closeInternal(SQLServerPreparedStatement.java:328)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.close(SQLServerStatement.java:668)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getColumns(SQLServerDatabaseMetaData.java:661)
	at org.flywaydb.core.internal.dbsupport.Table.hasColumn(Table.java:134)
	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.upgradeIfNecessary(MetaDataTableImpl.java:68)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1368)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
	at org.flywaydb.core.RomeFlyway.runUpgrade(RomeFlyway.java:202)
	at org.flywaydb.core.RomeFlyway.upgrade(RomeFlyway.java:137)
	at rome.database.DatabaseSetupManager.upgrade(DatabaseSetupManager.java:98)
	at rome.database.DatabaseSetupManager.run(DatabaseSetupManager.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.izforge.izpack.panels.process.ProcessPanelWorker$ExecutableClass.run(ProcessPanelWorker.java:757)
	at com.izforge.izpack.panels.process.ProcessPanelWorker$ProcessingJob.run(ProcessPanelWorker.java:471)
	at com.izforge.izpack.panels.process.ProcessPanelWorker.runJob(ProcessPanelWorker.java:415)
	at com.izforge.izpack.panels.process.ProcessPanelWorker.run(ProcessPanelWorker.java:350)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by tkyc** [comment] 2024-10-30 16:24
What's the flyway version you're using?

**Comment by lilgreenbird** [comment] 2024-11-01 00:12
We do not support Flyway or other 3rdparty products please let us know how you are using the driver ie provide us with repro code to reproduce the issue. I would suggest to try again with a more recent version of the driver as well since we've had a lot of changes since the 9.2.1 release. You can get the latest 12.6.4 stable reason [here](https://github.com/microsoft/mssql-jdbc/releases/tag/v12.6.4). If you still see this issue, please let us know how you are using the driver to reproduce the error.

**Comment by rahulsavale13** [comment] 2024-11-01 01:48
Our app installer is using flyway 4.0.3 version for new database creation or database upgrade.
We tried performing database upgrade using mssql-jdbc-12.8.1.jre11.jar but still got reported error.


We are not able to reproduce this issue on any of our local/CI environment using mssql-jdbc-9.2.1.jre11 or mssql-jdbc-12.8.1.jre11.jar.

This issue is occurring only on one of our customers. 

Maybe I will have to get on call with customer and find out the values being passed internally to this SP EXEC sp_columns_100 ?,?,?,?,?,?.

**Comment by Jeffery-Wasty** [comment] 2024-11-22 18:27
Hi @rahulsavale13,

Can you please provide us with either repro code or additional information on how the customer is arriving at this issue, otherwise we will move forward with closing this issue.

**Comment by Jeffery-Wasty** [comment] 2024-11-26 17:23
Closing due to lack of response.

**Closed** 2024-11-26 17:22 UTC
Labels: Waiting for Response

**Comment by canglaoshidaidui** [comment] 2024-11-29 09:13
2024-11-26 15:36:59 : RootException:org.apache.flink.runtime.JobException: Recovery is suppressed by FixedDelayRestartBackoffTimeStrategy(maxNumberRestartAttempts=0, backoffTimeMS=5000)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:118)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:80)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:233)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:224)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:215)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:666)
	at org.apache.flink.runtime.scheduler.SchedulerNG.updateTaskExecutionState(SchedulerNG.java:89)
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:446)
	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:305)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:212)
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:77)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:158)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.NullPointerException
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:61)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:26)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.processExecuteResults(SQLServerStatement.java:1287)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.processResponse(SQLServerPreparedStatement.java:530)
	at com.microsoft.sqlserver.jdbc.TDSCommand.close(IOBuffer.java:7488)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.discardLastExecutionResults(SQLServerStatement.java:142)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.closeInternal(SQLServerStatement.java:653)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.closeInternal(SQLServerPreparedStatement.java:328)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.close(SQLServerStatement.java:668)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getColumns(SQLServerDatabaseMetaData.java:661)


我在线上遇到类似问题 sql server 2005、mssql-jdbc-6.2.1.jre8 。最终发现是其他连接器中包含了一个高版本mssql驱动（9.2.1）。排除后程序一切正常，如果你也是类似状况。希望对你有所帮助。
