### ISSUE TITLE
[QUESTION] Callable statements with named parameters are using metadata instead of calling directly

### ISSUE THREAD

**Issue by jd-18723** [microsoft/mssql-jdbc#1147] opened 2019-09-18 14:28 UTC
## Question
When executing a callable statement with the Microsoft driver and using named parameters, the driver seems to call `exec sp_sproc_columns @procedure_name='proc_name'` first. It then executes the stored procedure by calling `exec sp_executesql N'EXEC proc_name @P0,@P1, etc.`.

When I do the same thing (named parameters on a callable statement) with another driver, I see that the driver executes the stored procedure by running `exec proc_name @param1=1,@param2=2, etc.` which avoids the need for the metadata lookup with sp_sproc_columns.

I think I'm running into some performance issues that might be caused by that metadata lookup (even though it seems to be cached by the driver). Would there be any downside to the driver making use of the second pattern and avoiding the metadata lookup? It seems that SQL Server is able to figure out which parameters go where, and it's not necessary to send them through in the "correct" order.

## Relevant Issues and Pull Requests
Maybe related to #272? Not sure.

**Comment by peterbae** [comment] 2019-09-19 16:41
Hi @jd-18723, thanks for contacting us. We are aware of this improvement the driver can make, as this issue is being tracked in #244. I'll close this issue as duplicate of that one.

**Closed by peterbae** 2019-09-19 16:41 UTC
Labels: question
