### ISSUE TITLE
Not employing SQLIntegrityConstraintViolationException when hitting "Violation of PRIMARY KEY constraint"

### ISSUE THREAD

**Issue by stolsvik** [microsoft/mssql-jdbc#1478] opened 2020-12-09 09:53 UTC
(Quick comment, feel free to throw in the trash if not correct)

It seems to me that the MS SQL JDBC driver does not employ the specific types of SQLExceptions that have existed since 1.6. Specifically, this should, IMO, have thrown a SQLIntegrityConstraintViolationException, but evidently it just throws a `SQLServerException extends java.sql.SQLException`:

```
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_mats_socket_inbox_02'. Cannot insert duplicate key in object 'dbo.mats_socket_inbox_02'. The duplicate key value is (a80cF0xvLJOthmZf, 18).
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:602)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:505)
```

**Comment by ulvii** [comment] 2020-12-09 18:23
Hi @stolsvik , this seems like duplicate of #1199

**Comment by stolsvik** [comment] 2020-12-10 11:39
@ulvii Certainly does. Suggest close duplicate. (And suggest to fix it, one year later.. I was not surprised that jTDS do not employ these specialized Exceptions, but I was _very_ surprised that a modern, new JDBC driver does not.)

**Comment by ulvii** [comment] 2020-12-10 19:03
Hi @stolsvik ,
I am closing this issue as a duplicate, please feel free to add a comment on #1199 .

**Closed by ulvii** 2020-12-10 19:03 UTC
