### ISSUE TITLE
 SQL bulk copy gives error when a column has an incorrect default value defined

### ISSUE THREAD

**Issue by tommy38hk** [microsoft/mssql-jdbc#1437] opened 2020-09-25 10:24 UTC
When a table has an incorrect default value, SQL bulk copy will run into error

CREATE TABLE dbo.[TEST](
	[col_1] [numeric](22, 0) NOT NULL,
	[col_2] [nchar](1) NULL,
 CONSTRAINT [TEST_PK] PRIMARY KEY CLUSTERED 
(
	[col_1] ASC
))
ALTER TABLE dbo.[TEST]ADD  CONSTRAINT [INCORRECT_DEFAULT]  DEFAULT ('(''N'') ') FOR [col_2]
GO

insert into dbo.test
values
(1,'U'),(2,'X')

 com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated in table 'mydb.dbo.TEST', column 'col_2'. Truncated value: '('.

Here's the code
public void bulkInsert (String catalog, String schema, String tableName) throws SQLException {
ResultSet rsSourceData;
String selectColumns = getSelectColumns(catalog, schema, tableName);
String fullTableName = catalog+"."+schema+"."+tableName;
String sourceSQL="select "+selectColumns+" from "+fullTableName;

    try (Connection sourceConnection = jdbcTemplateSource.getDataSource().getConnection();
         Connection destinationConnection = jdbcTemplateTarget.getDataSource().getConnection();

         Statement stmt = sourceConnection.createStatement();

         SQLServerBulkCopy bulkCopy = new SQLServerBulkCopy(destinationConnection)) {
        log.info(fullTableName);
        log.info(sourceSQL);
       
        rsSourceData = stmt.executeQuery(sourceSQL);
        ResultSetMetaData rsmd = rsSourceData.getMetaData();
        int columnCount = rsmd.getColumnCount();

        for (int i = 1; i <= columnCount; i++ ) {
            String name =rsmd.getColumnName(i);
                bulkCopy.addColumnMapping(name,name);
        }

        bulkCopy.setDestinationTableName(fullTableName);

        SQLServerBulkCopyOptions copyOptions = new SQLServerBulkCopyOptions();
        copyOptions.isKeepIdentity();
        copyOptions.setBatchSize(102400);
        copyOptions.setCheckConstraints(true);
        copyOptions.setBulkCopyTimeout(0);
        bulkCopy.setBulkCopyOptions(copyOptions);
        // Write from the source to the destination.
        bulkCopy.writeToServer(rsSourceData);

        // Perform a final count on the destination
        // table to see how many rows were added.
        int countAfter = getRowCount(stmt, fullTableName);
    } catch (SQLException e) {
        if (e.toString().indexOf("Violation of PRIMARY KEY constraint")!=-1) {
            log.warn("Ignroing "+e.toString());
        }
        else {
            throw new SQLException(e);
        }
    }
}

**Comment by lilgreenbird** [comment] 2020-09-28 20:56
hi @tommy38hk 

In this case the issue is that you are trying to insert a value that doesn't fit into the nchar column so SQL server is giving you an error telling you what's wrong. If you tried to do something similar in SSMS you will get the same error.

**Comment by tommy38hk** [comment] 2020-09-29 11:13
But you can see my source table does not have any records exceeding the column size. It looks like Sql bulk is preinserting a default before copying the actual rows. It only works if I remove the constraint. You should be able to replicate this by inserting the following rows in the source table

insert into dbo.test
values
(1,'U'),(2,'X')

**Comment by lilgreenbird** [comment] 2020-09-30 00:56
yes but as you pointed out the default value is wrong and you would get an error if it's used. I think bulkcopy is checking the constraint and it's giving you the error you would have gotten which I don't think is a bad thing.

**Comment by tommy38hk** [comment] 2020-10-01 09:09
Yes and no
I do not own that database and no rights to alter the table
The source data does not have data violating the rule. I can use SQL inserts without errors.

**Comment by ulvii** [comment] 2020-10-01 16:52
@tommy38hk ,
There is a fundamental issue on your schema and it is recommended to get it fixed. Your schema specifies a default value and the default value gets added to all new records IF no other value is specified. So if you were to execute `insert into test (col_1) values (1)` you would run into the same issue, which defeats the purpose of `ALTER TABLE dbo.[TEST]ADD CONSTRAINT [INCORRECT_DEFAULT] DEFAULT ('(''N'') ') FOR [col_2]`.

> The source data does not have data violating the rule.

This is the SQL Server behavior, there is not much the driver can do about it.

**Comment by ulvii** [comment] 2020-10-22 20:43
I just tried this scenario with [BCP](https://docs.microsoft.com/en-us/sql/tools/bcp-utility?view=sql-server-ver15)  and received the same error message.

```
Starting copy...
SQLState = 22005, NativeError = 0
Error = [Microsoft][ODBC Driver 17 for SQL Server]Invalid character value for cast specification
SQLState = 37000, NativeError = 2628
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]String or binary data would be truncated in table 'tempdb.dbo.TEST2', column 'col_2'. Truncated value: '('.
SQLState = 01000, NativeError = 3621
Warning = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated.

BCP copy in failed
```
Closing the issue, as this is not a driver issue. Please let us know if you have further questions.

**Closed by ulvii** 2020-10-22 20:43 UTC
