### ISSUE TITLE
Connecting azure SQL Server using generated Active directory access token

### ISSUE THREAD

**Issue by shivamdabas** [microsoft/mssql-jdbc#1724] opened 2021-12-22 14:28 UTC
I was trying to connect to azure sql server using AD access token . I have written my prelogin packet and getting proper response for that but in my login packet I'm receiving response as "Login failed because Azure Dns Caching feature extension is malformed." but I'm only sending FEDAUTH as only feature and bFedAuthLibrary as library Security Token. Any suggestions on this?

**Comment by v-zhangw** [comment] 2021-12-22 17:51
Hello @shivamdabas,

Usually when folks encounter issues with using access tokens to authenticate, it is due to not having all the required dependencies for the driver and/or MSAL4J (can be found in our pom file), or an issue on azure.

However, it is very difficult to really say what the issue is without some more information.

Can you please give us:

- The stacktrace of the JDBC error
- What version of the driver you are using
- Your connection string
- If possible, a short repro/code snippet of the issue

Regards,
Wei

**Comment by shivamdabas** [comment] 2021-12-22 19:24
hi, @v-zhangw 
Thanks for the reply, I was working on my own ODBC code in C++ and implementing similar active directory sql server authentication using access token, Here's my code snippet with some hardcoded values and I'm getting the response from server but it's an error as mentioned earlier. Any help would be appreciated. 

`
	conn->out_type = LOGIN_PACKET;
	int offset = 94;    // start of data following SMB index.
	int packet_size = offset + serverNameLen + libraryLen + languageLen + clientHostNameLen + appNameLen + databaseLen 
		+ 4; // for +4 for ib extension;

	// aeOffset value should be when fedauth struct starts
	int aeOffset = packet_size;
        // conn->auth.data contains access token already generated from Active directory and conn->auth.size it's size
	int auth_len = conn->auth.data ? conn->auth.size : 0;
	packet_size += auth_len ? auth_len : (userNameLen + passwordLen);
	// +10 for struct FEDAUTH size for access token struct
       packet_size += 10;
	 

	PUT_int32(conn, packet_size);
	PUT_int32(conn, conn->tds_version);
	PUT_int32(conn, conn->block_size);
	PUT_int32(conn, 0xF8F28306);    // Client program version. DiIk see MS-TDS LOGIN7 example
	PUT_int32(conn, getpid());      // threadid?
	PUT_int32(conn, 0);             // connection id

	enum {
		USE_DB = 0x20, INIT_DB_WARN = 0x40, SET_LANG_ON = 0x80, LOGIN_OPTION3_FEATURE_EXTENSION = 0x10,
		TDS_FEATURE_EXT_AE = 0x04, COLUMNENCRYPTION_VERSION1 = 0x01, TDS_FEATURE_EXT_FEDAUTH = 0x02};
	//option flag 1
	PUT_uint8(conn, USE_DB | INIT_DB_WARN | SET_LANG_ON); // LittleEndian, Ascii, IEEE-Float DumpLoad 
														  //option flag 2
														  //PUT_uint8(conn, auth_len ? 0x83 : 0x03); // INIT_LANG_FATAL=1, ODBC_ON=2, USER_NORMAL=4, INTEGRATED_SECURITY=80
	PUT_uint8(conn, 0x03);
	//type flag
	PUT_uint8(conn, SQL_DFLT | (conn->readonly ? 0x20 : 0));   // fSQLType = SQL_DFLT; SQL_TSQL=1 fOLEDB=16 fReadOnlyIntent = 32
															   //option flag 3
	PUT_uint8(conn, LOGIN_OPTION3_FEATURE_EXTENSION);     // fChangePassword=!1, fSendYukonBinaryXML=!2, fUserInstance=!4 fUnknownCollationHandling=!8, fExtension=!16

										  //Note:  Win32 (gmtime,localtime) use the same static struct tm.
	time_t now = time(0);
	struct tm* tmp = localtime(&now);
	int gmt_offset = 60 * tmp->tm_hour + tmp->tm_min;
	tmp = gmtime(&now);
	gmt_offset -= 60 * tmp->tm_hour + tmp->tm_min;

	if (gmt_offset >= 12 * 60)
	{
		gmt_offset -= 24 * 60;
	}

	PUT_int32(conn, gmt_offset);
	PUT_int32(conn, 1033);  // LCID: en-us

							//XXX make this more like PUT_SMB in submit_prelogin
							// host name
	PUT_int16(conn, (int16_t)offset); PUT_int16(conn, clientHostNameLen / 2); offset += clientHostNameLen;

	if (auth_len)
	{
		PUT_int16(conn, 0); PUT_int16(conn, 0); // NULL username
		PUT_int16(conn, 0); PUT_int16(conn, 0); // NULL password
	}
	else
	{
		// username
		PUT_int16(conn, (int16_t)offset); PUT_int16(conn, userNameLen / 2); offset += userNameLen;
		PUT_int16(conn, (int16_t)offset); PUT_int16(conn, passwordLen / 2); offset += passwordLen;
	}

	PUT_int16(conn, (int16_t)offset); PUT_int16(conn, appNameLen / 2); offset += appNameLen;
	PUT_int16(conn, (int16_t)offset); PUT_int16(conn, serverNameLen / 2); offset += serverNameLen;
	//PUT_int16(conn, 0);               PUT_int16(conn, 0); // MS-TDS 2.2.6.3 LOGIN7 "Unused"
    // ibExtension
	PUT_int16(conn, (int16_t)offset); PUT_int16(conn, 4); offset += 4;
	PUT_int16(conn, (int16_t)offset); PUT_int16(conn, libraryLen / 2);  offset += libraryLen;
	PUT_int16(conn, (int16_t)offset); PUT_int16(conn, languageLen / 2); offset += languageLen; // to be written 0
	PUT_int16(conn, (int16_t)offset); PUT_int16(conn, databaseLen / 2); offset += databaseLen;

	put_bytes(conn, nomacaddr, 6); //?!

	PUT_int16(conn, 0); PUT_int16(conn, 0);   // authentication
	PUT_int16(conn, (int16_t)offset); PUT_int16(conn, 0); // db file srsly
	PUT_int16(conn, 0); PUT_int16(conn, 0); // new password
	PUT_int16(conn, 0);               PUT_int16(conn, 0); // "SSPI" ?

	put_bytes(conn, clientHostName, clientHostNameLen);
	if (!conn->auth.data)
	{
		put_bytes(conn, userName, userNameLen);

		// Obfuscate password:
		int i;
		for (i = 0; i < passwordLen; i++)
		{
			password[i] = ((password[i] << 4) | (password[i] >> 4)) ^ 0xA5;
		}

		put_bytes(conn, password, passwordLen);
	}

	put_bytes(conn, appName, appNameLen);
	put_bytes(conn, serverName, serverNameLen);
	//ibExtension
	PUT_int32(conn, aeOffset);
	put_bytes(conn, library, libraryLen);
	put_bytes(conn, language, languageLen);
	put_bytes(conn, database, databaseLen);

// sending only fedAuth feature data
	PUT_uint8(conn, TDS_FEATURE_EXT_FEDAUTH);
	PUT_int32(conn, auth_len + sizeof(int) + 1);
	//options
	PUT_uint8(conn, ((0x01 << 1) | 0X01));
	// type of auth
	PUT_int32(conn, auth_len);
        put_bytes(conn, conn->auth.data, conn->auth.size);
`

**Comment by tkyc** [comment] 2021-12-23 20:02
Hi @shivamdabas, apologies. Your issue isn't related to the function of the JDBC driver. I'll be closing this issue.

**Closed by tkyc** 2021-12-23 20:02 UTC
Labels: question, Waiting for response

**Comment by lilgreenbird** [comment] 2021-12-23 20:10
hi @shivamdabas 

this repo is specific to the Microsoft JDBC Driver for SQL Server only. It sounds like you require support for the ODBC Driver for SQL Server. I would suggest to connect MS Support for that.
