### ISSUE TITLE
SQLServerDataTable. AddRow (Object.. values), why TimeStamp need be converted to String type?

### ISSUE THREAD

**Issue by rabbit-mom** [Microsoft/mssql-jdbc#159] opened 2017-02-27 09:54 UTC
SQLServerDataTable. AddRow (Object.. values), why TimeStamp need be converted to String type?When using this data in the table time type (for example, TVP insert), will need to type conversion back time, is it not bother?

**Comment by v-xiangs** [comment] 2017-02-27 17:14
hello @rabbit-mom , thank your for filing this issue. However, we are not able to reproduce this scenario. If possible, could you please provide more details?

**Comment by v-suhame** [comment] 2017-02-27 17:46
@rabbit-mom SQL Server has a list of supported String literal formats for each Temporal data types, for example these are the [supported literal format](https://msdn.microsoft.com/en-us/library/bb677243.aspx#Anchor_1) for [Time](https://msdn.microsoft.com/en-us/library/bb677243.aspx). To avoid the overhead of parsing each of these literal types, JDBC driver converts them into string and passes it to the SQL Server to handle the conversion.

**Comment by rabbit-mom** [comment] 2017-02-28 05:33
This problem I have found the root cause. I am using the JDBC TVP to insert a datatable in a SQLServer database, when using SQLServerDataTable. AddRow (), field order need to order according to the dictionary, namely of the stored procedure TVP order parameters declared in the field

**Comment by v-xiangs** [comment] 2017-02-28 23:41
@rabbit-mom Thank you for your response. Just want to clarify with you. Do you mean, when you use `SQLServerDataTable#addRow(value1, value2, ...)`, the order of values needs to follow the order of columns in the table?

Also, just wondering, did you see any exceptions from your project? for example: 
`com.microsoft.sqlserver.jdbc.SQLServerException: Conversion failed when converting date and/or time from character string.`

**Comment by rabbit-mom** [comment] 2017-03-01 03:03
I have asked  my colleagues, this order is our company's design,it has nothing to do with the framework.Thank you for your enthusiastic response, if subsequent have any questions I will ask again, thank you once again.

**Comment by rabbit-mom** [comment] 2017-03-01 03:04
@v-xiangs  I have asked my colleagues, this order is our company's design,it has nothing to do with the framework.Thank you for your enthusiastic response, if subsequent have any questions I will ask again, thank you once again.

**Comment by v-xiangs** [comment] 2017-03-01 17:20
@rabbit-mom thank you for explaining the cause with us. Since it is not an issue inside the mssql-jdbc project, I am going to close this issue. Feel free to re-open it if anything goes on. Thank you.

**Closed by v-xiangs** 2017-03-01 17:20 UTC
Labels: Waiting for response
