### ISSUE TITLE
`datetimeoffset` type is not mapped to a `java.sql.Types`

### ISSUE THREAD

**Issue by NathanEckert** [microsoft/mssql-jdbc#1976] opened 2022-11-23 11:20 UTC
## Driver version

10.2.1.jre11

## SQL Server version

Docker image 2019-CU18-ubuntu-20.04

## Client Operating System

Ubuntu 22.04.1 LTS

## JAVA/JVM version

Java 11 : Eclipse Temurin version 11.0.16

## Table schema

Any schema

## Problem description

When you're holding a `ResultSet` of a table containing a column with type `datetimeoffset`, it is not mapped properly to a `JDBCType`
`
```java
final ResultSet columns = connection.getMetaData()
						.getColumns(dbPattern, schemaPattern, tablePattern, null)) 
while (columns.next() {
    int typeInt = columns.getInt("DATA_TYPE");
    JDBCType jdbcType = JDBCType.valueOf(typeInt)
}
```

The previous code throw an error, in `JDBCType#valueOf()`, as the return code is -155 for `datetimeoffset`, which is not contained in `java.sql.Types`

## Expected behavior

The return type should be mapped properly, probably to 2014 (`Types.TIMESTAMP_WITH_TIMEZONE`)

## Actual behavior

Output code is -155

## Error message/stack trace
None

**Comment by Jeffery-Wasty** [comment] 2022-11-23 18:23
We'll take a look into this and get back to you with out results, thanks.

**Comment by tkyc** [comment] 2022-11-24 23:58
The question is a bit confusing because to map `datetimeoffset` to a `java.sql.type` it would mean a change in the `java.sql` API as you're using `JDBCType.valueof` which isn't part of the mssql-jdbc API.

To me, the problem is that the driver doesn't expose a public `JDBCType` API. Internally we do map `datetimeoffset` to our own JDBCType. So, whether we should expose that is up for discussion. I'm marking this as a future enhancement for triaging.

**Comment by lilgreenbird** [comment] 2022-11-29 00:47
This is as designed and documented in [Data type mappings table](https://learn.microsoft.com/en-us/sql/connect/jdbc/using-basic-data-types?view=sql-server-ver16#data-type-mappings). This will not be changed as doing so will break functionality for those who rely on this value.

**Closed** 2022-12-07 02:33 UTC
Labels: As designed
