### ISSUE TITLE
Login failed for user '<token-identified principal>'. Token is expired.

### ISSUE THREAD

**Issue by jpcsliiv** [microsoft/mssql-jdbc#1944] opened 2022-10-30 13:45 UTC
## Driver version
`mssql-jdbc-11.2.1.jre11`

## SQL Server version
Azure SQL

## Client Operating System
Linux on Azure App Service.

## JAVA/JVM version
Java 11
Spring Boot 2.7.5
Hikaricp 5.0.1

## Hikari configuration
`  datasource:
    url: jdbc:sqlserver://${DATABASE_SERVER_NAME}:1433;database=${DATABASE_NAME};Authentication=ActiveDirectoryMSI
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 20`
Note: default 

## Problem description
The connections to the database are acquired and work correctly for several hours. 
After some time, Hikari tries to create a new connection for the pool using the SQLServerDriver, and it receives an expired token as specified in the stack trace, when calling `SQLServerConnection.sendFedAuthToken(...)`
`Login failed for user '<token-identified principal>'. Token is expired.`
Once the App service is restarted manually, the connections are recreated.
Same issue as described in #1908 by @akleemans

## Error message/stack trace
`2022-10-29T05:26:54.664576128Z Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user '<token-identified principal>'. Token is expired. ClientConnectionId:2787d61f-5f69-476c-8df7-ce83dbb3ec57
2022-10-29T05:26:54.664580428Z 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664584428Z 	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:300) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664588428Z 	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:133) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664592428Z 	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664596628Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendFedAuthToken(SQLServerConnection.java:5616) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664600728Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection$FedAuthTokenCommand.doExecute(SQLServerConnection.java:5394) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664604828Z 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664609929Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5422) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664614029Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:5302) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664618029Z 	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:306) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664622029Z 	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:126) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664626129Z 	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664630029Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6295) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664634129Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4907) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664638129Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4845) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664642229Z 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664646229Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3912) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664650330Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3358) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664657530Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2950) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664661630Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2790) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664665930Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1663) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664670030Z 	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1064) ~[mssql-jdbc-11.2.1.jre11.jar!/:na]
2022-10-29T05:26:54.664674030Z 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121) ~[HikariCP-5.0.1.jar!/:na]
2022-10-29T05:26:54.664678130Z 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359) ~[HikariCP-5.0.1.jar!/:na]
2022-10-29T05:26:54.664682130Z 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[HikariCP-5.0.1.jar!/:na]
2022-10-29T05:26:54.664686031Z 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470) ~[HikariCP-5.0.1.jar!/:na]
2022-10-29T05:26:54.664689931Z 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:733) ~[HikariCP-5.0.1.jar!/:na]
2022-10-29T05:26:54.664693831Z 	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-5.0.1.jar!/:na]
2022-10-29T05:26:54.664697931Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]`

## Comments
I've noticed that the error response contains the error Id 18456, which is not considered a transient error; hence the connection cannot be retried. Is this because the error 18456 could mean wrong credentials? but is it also used for expired token?
I've also noticed the same issue in the .net SDK
https://github.com/dotnet/SqlClient/issues/617#issuecomment-654319568

**Comment by Jeffery-Wasty** [comment] 2022-10-31 19:18
Hi @jpcsliiv,

You mention that this is the same error as #1908, can you try the solutions proposed in that thread, to eliminate the possibility that this is a Hikari issue? I see you're already on the latest version, 5.0.1, the other solutions were:

- [checking the number of active connections](https://github.com/brettwooldridge/HikariCP/wiki/JDBC-Logging#microsoft-sql-server) at point of failure, to confirm whether the connections are being returned to the pool correctly?
- increase the size of the pool and see what effect this has on the failure?

**Comment by alromos** [comment] 2022-11-15 13:04
Hi @Jeffery-Wasty 
It looks like we are facing the same issue in our application.
Configuration is almost the same.
> Driver version: **11.2.1.jre17**
> Spring Boot version: **2.7.1**
> HikariCP version: **5.0.0**
> Authentication: **ActiveDirectoryMSI**

Hikari CP properties:
> spring.datasource.hikari.maximum-pool-size=50
> spring.datasource.hikari.minimum-idle=10
> spring.datasource.hikari.idle-timeout=300000
> spring.datasource.hikari.connection-timeout=10000

And the issue symptoms and exception stacktrace are identical.
Could you let me know what exact logs do you need? I'm going to enable the `FINER` logging for `SQLServerConnection` in lower environment however I won't be able to share the client's logs with you, I may only grab some information from the logs for you.

**Comment by Jeffery-Wasty** [comment] 2022-11-15 17:21
There should be information about the token time, either time of creation or expiry. In the above, we're creating a new connection, but I'm worried that a token is being reused. Please look for keyword 'token' and see if there is any time related information.

**Comment by David-Engel** [comment] 2022-11-16 21:08
Managed Identity token caching was added to the driver in version 11.2. The cache is supposed to clear the token at the lesser of msiTokenCacheTtl (1 hour by default) or 5 minutes prior to the token's expiry. You can try adding `msiTokenCacheTtl=0` to your connection string to disable it and eliminate that as a possible cause of the issue. FINER logging should also show whether or not a cached token is being used and what the driver thinks its expiration date is.

**Comment by Jeffery-Wasty** [comment] 2022-11-16 21:16
Yes, thank you David. Since both of you are using 11.2.1, this is something you can try as well.

**Comment by alromos** [comment] 2022-11-21 07:31
@Jeffery-Wasty @David-Engel 
JFYI
I managed to enable FINER logging. I'm still waiting for the issue to reproduce and will provide an update when it happens. So far I can see the expected entries in logs confirming token caching works as expected:

> **2022-11-21T06:33:00.35Z** Obtained new Managed Identity auth token: accessToken hashCode: 1949657705 expiresOn: 2075-10-11T20:48:17.350Z
> 2022-11-21T06:03:27.067Z Using cached Managed Identity auth token: accessToken hashCode: 1949657705 expiresOn: 2075-10-11T19:47:59.593Z
> **2022-11-21T05:32:42.593Z** Obtained new Managed Identity auth token: accessToken hashCode: 1949657705 expiresOn: 2075-10-11T19:47:59.593Z

And I don't have an ability to append `msiTokenCacheTtl=0` to connection string without providing a proof that the change will resolve the issue.

**Comment by alromos** [comment] 2022-11-21 16:25
@Jeffery-Wasty 
The issue happened again and I managed to capture some logs. However it looks like there is no much valuable information here.
Token expiration time is still OK, since I see the following lines when the issue happened:
```
Using cached Managed Identity auth token: accessToken hashCode: 1949657705 expiresOn: 2075-10-12T04:13:17.888Z
```
Right before the exception is thrown I see this:
```
ConnectionID:1866 ClientConnectionId: f6ea8029-23cb-4ea3-b046-b759cd7f646b Sending federated authentication token.
```
And then the exception is thrown:
```
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user '<token-identified principal>'. Token is expired. ClientConnectionId:f6ea8029-23cb-4ea3-b046-b759cd7f646b
```
So, it looks like the exception message may be incorrect. Should I enable some additional logging to grab more details?

Also I noticed that the issue got resolved without any interaction from our side when the new token was obtained:
```
Obtained new Managed Identity auth token: accessToken hashCode: 71147383 expiresOn: 2075-10-13T05:56:09.205Z
```
I can see that token's hash and expiration time has changed. So there is a chance `expiresOn` value in the log doesn't match actual token expiration time and it may be a cause of the issue. I'm surprised it expires in **2075** :) And now I think that @Jeffery-Wasty's suggestion may actually help me to resolve the issue.

**Comment by lilgreenbird** [comment] 2022-11-23 00:04
as David mentioned, setting msiTokenCacheTtl=0 would disable the cache so if your suspicion is that an expired cached token is used, then this would definitely rule out that possibility.

**Comment by alromos** [comment] 2022-11-28 11:15
JFYI
I haven't seen the token expiration errors for 4 days after setting
```
spring.datasource.hikari.data-source-properties.msiTokenCacheTtl=0
```

I still think there is an issue with token caching and it should be fixed or at least the token caching should be disabled by default until the issue is fixed.

**Comment by lilgreenbird** [comment] 2022-11-28 21:34
hi @alromos 

This option is now obsolete and has been deprecated as of [12.1.0 release ](https://github.com/microsoft/mssql-jdbc/releases/tag/v12.1.0). Caching is now being handled by SQL Server directly the driver does not do any caching of the token at all.

**Comment by graemefoster** [comment] 2022-11-29 10:22
@lilgreenbird , when will 12.1.0 be GA? It still shows as preview. 

I’ve got the same issue with token timeout but am unable to switch to a preview library.

**Comment by lilgreenbird** [comment] 2023-01-24 19:42
closing due to inactivity, pls feel free to request re-opening if you have more questions

**Closed by lilgreenbird** 2023-01-24 19:42 UTC
Labels: Waiting for Response
