### ISSUE TITLE
Executing a PreparedStatement with SET SHOWPLAN_ALL ON or SET SHOWPLAN_XML ON does not return a ResultSet.

### ISSUE THREAD

**Issue by rtwruck** [Microsoft/mssql-jdbc#778] opened 2018-08-08 20:31 UTC
## Driver version or jar name
mssql-jdbc-7.0.0.jre8.jar

## SQL Server version
12.00.5571

## Client operating system
Linux

## Java/JVM version
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

## Table schema
any

## Problem description
Executing a PreparedStatement with SET SHOWPLAN_ALL ON or SET SHOWPLAN_XML ON does not return a ResultSet.
It makes no difference whether prepareStatement is called before or after issuing the SET statement.
A ResultSet with the expected plan is returned when using createStatement().execute(sqlText) - but that obviously does not work when the statement takes parameters.
In addition, there's a NullPointerException when you call PreparedStatement.getParameterMetaData() with SET SHOWPLAN in effect, presumably because the returned ResultSet contains the plan:
	at com.microsoft.sqlserver.jdbc.SQLServerParameterMetaData.parseQueryMeta(SQLServerParameterMetaData.java:211)
	at com.microsoft.sqlserver.jdbc.SQLServerParameterMetaData.<init>(SQLServerParameterMetaData.java:602)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getParameterMetaData(SQLServerPreparedStatement.java:3057)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getParameterMetaData(SQLServerPreparedStatement.java:3068)

## Expected behavior and actual behavior
Expected:
connection.createStatement().execute("SET SHOWPLAN_ALL ON") == false &&
connection.prepareStatement(sqlText).execute() == true
Actual:
connection.createStatement().execute("SET SHOWPLAN_ALL ON") == false &&
connection.prepareStatement(sqlText).execute() == false

## Repro code
See above.

**Comment by rene-ye** [comment] 2018-08-08 21:37
Hi @rtwruck, this is intended behavior as SQL Server does not return estimated execution plans for the execution of stored procedures. When executing a Prepared Statement from the driver, the stored procedure `sp_executesql 'user_sql'` is called. [When SET SHOWPLAN_ALL is ON, SQL Server returns execution information for each statement without executing it, and Transact-SQL statements are not executed](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-showplan-all-transact-sql?view=sql-server-2017). If SHOWPLAN_ALL is ON, executing a simple select statement `SELECT * FROM table` will yield the following results: 
![glifao](https://user-images.githubusercontent.com/6042742/43865563-c86824ae-9b17-11e8-8fce-2c56e06c5d24.png)

Whereas executing the same statement with `sp_executesql` will yield the following:
![iqsguq](https://user-images.githubusercontent.com/6042742/43865592-e024b44a-9b17-11e8-8921-44b211191a87.png)

As you can see, the server does not attempt to estimate the execution of the stored procedure call. Some drivers have tried to circumvent this behavior by parsing the prepared statement and executing it silently as a regular statement, but the mssql-jdbc driver does not do this as it's hacky and difficult to maintain (e.g. doesn't support parameterized queries).

**Comment by cheenamalhotra** [comment] 2018-08-14 21:52
Hi @rtwruck ,

As @rene-ye mentioned above, `PreparedStatement.executeQuery()` doesn't return a ResultSet after enabling 'SHOWPLAN' is because of the way our driver executes a PreparedStatement, using `sp_executesql` or `sp_prepexec` or `sp_execute`. In either of the three procedure calls, SQL Server does not return any ResultSet when 'SHOWPLAN' is enabled.

On the contrary, enabled 'SHOWPLAN' retrieves ResultSet with jTDS driver (for non-parameterized queries only) because jTDS driver prepares a statement with `sp_prepare` and decides based on query parameters how to execute the user query. If no parameters are defined, it uses the same path as `Statement.execute()`, passing the query directly to SQL Server (which returns a ResultSet). However, it doesn't retrieve a ResultSet for parameterized queries as well.

We would recommend using Statement APIs only for retrieving execution plan as parameterized queries do not provide any execution plan in either case. Also, the issue about `NullPointerException` will be fixed in PR #780 with another issue fix involving `SQLServerParameterMetadata` class.

**Comment by cheenamalhotra** [comment] 2018-09-25 22:39
Hi @rtwruck 

PR #780 has been merged that fixes Null Pointer Exceptions reported in this issue. Closing the issue.

**Closed by cheenamalhotra** 2018-09-25 22:39 UTC
